spool dq_target_dev.log

 CREATE TABLE "C##DQ_TARGET_DEV"."TB_CD" 
   (	"CD_GRP_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"CD_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"CD_NM" VARCHAR2(100), 
	"CD_DESC" VARCHAR2(4000)
   ) ;

  CREATE TABLE "C##DQ_TARGET_DEV"."TB_CD_GRP" 
   (	"CD_GRP_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"CD_GRP_NM" VARCHAR2(100), 
	"CD_GRP_DESC" VARCHAR2(4000)
   ) ;

  CREATE TABLE "C##DQ_TARGET_DEV"."TB_USER" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"DEP_ID" NUMBER, 
	"POSITION_CODE" VARCHAR2(25), 
	"USER_NM" VARCHAR2(100) NOT NULL ENABLE, 
	"LOGIN_ID" VARCHAR2(36), 
	"USER_PWD" VARCHAR2(150), 
	"USER_IP" VARCHAR2(100), 
	"EMAIL" VARCHAR2(50), 
	"CELL_PHONE" VARCHAR2(24), 
	"ACTIVE_YN" VARCHAR2(1), 
	"OFF_DUTY_CODE" VARCHAR2(100), 
	"LAST_USE_DATE" VARCHAR2(14), 
	"EXPIRED_DATE" VARCHAR2(14), 
	"CRE_ID" NUMBER, 
	"CRE_DT" VARCHAR2(14), 
	"DEL_YN" VARCHAR2(1), 
	"DEL_ID" NUMBER, 
	"DEL_DT" VARCHAR2(14)
   );
   
  INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('DEL_YN','삭제여부',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('ACTIVE_YN','활성여부',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('EXECUTE_YN','실행여부',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('MAIL','메일',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('DEP_ID','부서아이디','DEP_TP_CD');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('POSITION_CODE','직급코드','POSITION');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('CONN_SITE','유관기관및단체','유관기관및단체');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('FAMILY_SITE','코네틱 패밀리사이트','코네틱 패밀리사이트');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('CS_CATE','컨설턴트 분야','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('SP_CATE','전문인력 분야','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('CS_CMP_CATE','컨설팅 기업 분야','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('CS_BIZ_GRP','컨설팅 기업 업종','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('CS_CMP_AREA','컨설팅 기업 지역','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('CS_OFF_AREA','오프라인 컨설팅 희망 지역','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('PRD_TYPE','에코디자인 제품 분류','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('IDEA_KWD','에코디자인 아이디어 키워드','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('IPR_TYPE','에코디자인 지식재산권','에코디자인 지식재산권');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('ENV_ISSUE','에코디자인 환경이슈','에코디자인 환경이슈');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('HS_TYPE','친환경병원 분야','친환경병원 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('GC_AREA','녹색기업 지역','녹색기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('NR_SPRT','알림/자료 기업지원사업','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('EMAIL','이메일','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('PH_ZONE','전화번호 국번','전화번호 국번');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('MOB_ZONE','핸드폰번호 국번','핸드폰번호 국번');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('SITE_CTYPE','유관기관 및 단체','유관기관 및 단체');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('SITE_FTYPE','코네틱 패밀리사이트','코네틱 패밀리사이트');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('IPR_ST','지식재산권 상태','지식재산권 상태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('JOB_CATE','종사분야','종사분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('BLNG_TYPE','소속구분','소속구분');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('HS_TEST','자가진단 체크리스트 항목','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('CMP_TYPE','기업형태','기업형태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('MBIZ_TYPE','기업회원 업종','기업회원 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('G0004','자가진단 체크리스트 항목','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('G0003','회원 구분','회원 구분');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD_GRP (CD_GRP_ID,CD_GRP_NM,CD_GRP_DESC) VALUES ('CM_BD','공통게시판 항목','공통게시판 항목');


INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('DEP_ID','1','마케팅',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('DEP_ID','2','영업',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('DEP_ID','3','개발',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('DEP_ID','4','품질관리',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('DEP_ID','5','기술지원',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('DEP_ID','6','인사',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('POSITION_CODE','S','사원','STAFF');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('POSITION_CODE','A','대리','Assistant Manager');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('POSITION_CODE','M','과장','Manager');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('POSITION_CODE','DGM','차장','Deputy General Manager');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('POSITION_CODE','DM','부장','Department Manager');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('POSITION_CODE','MD','이사','Managing Director');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('DEL_YN','Y','예',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('DEL_YN','N','아니오',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ACTIVE_YN','Y','예',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ACTIVE_YN','N','아니오',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EXE_YN','Y','예',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EXE_YN','N','아니오',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('COMMON','Y','예',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('POSITION_CODE','ED','상무','Executive Director');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('POSITION_CODE','CEO','대표이사','CEO');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR04','충남/대전','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR05','경북/대구','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR06','전남/광주','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR07','전북','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR08','충북','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR09','강원','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR10','제주','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR11','해외','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR01','지역환경기술개발센터연합회','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR02','인천지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR03','경기지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR04','시흥지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR05','울산지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR06','전남지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR07','강원지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR08','대구지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR09','안산지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR10','충남지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR11','대전지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR12','전북지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR13','경북지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR14','충북지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR15','경남지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR16','광주지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR17','제주지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR18','부산지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_OFF_AREA','HR19','서울지역환경기술개발센터','오프라인 컨설팅 희망 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA01','가정/사무용품','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA02','건축/건설','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA03','공공사업용 자재/장비','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA04','금속/무기재료/요업','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA05','농업/수산업/축업','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA06','산업 용품/설비','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA07','서비스','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA08','신재생 에너지','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA09','용기/포장','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA10','음료/식품','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA11','일반/정밀 기계','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA12','자가발전','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA13','자동차','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA14','전기전자','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA15','정보통신기기','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA16','제도개선','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA17','조선','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA18','폐기물','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA19','화학','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA20','환경관련 특수장비/기술','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA21','캠핑/아웃도어','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PRD_TYPE','IDEA22','기타','에코디자인 제품 분류');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD01','공기질 개선','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD02','공유(Sharing)','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD03','구조 개선','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD04','냉/난방 효율 개선','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD05','도시 농업 활성화','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD06','무전원','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD07','사용 수명 연장','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD08','생분해성 향상','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD09','생산성 향상','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD10','생산자/소비자 경제성 향상','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD11','소음 개선','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD12','소재 개선','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD13','수자원 저감','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD14','수질 개선','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD15','신재생 에너지 이용','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD16','악취 개선','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD17','에너지 저감','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD18','운송 효율 개선','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD19','자원 저감','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD20','재활용 효율 향상','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD21','폐기물 저감/자원화','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD22','폐기물의 친환경적 처리','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IDEA_KWD','KWD23','기타','에코디자인 아이디어 키워드');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IPR_TYPE','IPR01','특허권','에코디자인 지식재산권');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IPR_TYPE','IPR02','실용신안권','에코디자인 지식재산권');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IPR_TYPE','IPR03','디자인권','에코디자인 지식재산권');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IPR_TYPE','IPR04','상표권','에코디자인 지식재산권');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ENV_ISSUE','ISS01','자원 사용량 저감','에코디자인 환경이슈');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ENV_ISSUE','ISS02','에너지 효율 향상','에코디자인 환경이슈');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ENV_ISSUE','ISS03','유해물질 대체','에코디자인 환경이슈');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ENV_ISSUE','ISS04','재사용/재활용 물질 사용','에코디자인 환경이슈');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ENV_ISSUE','ISS05','재활용/재사용성 향상','에코디자인 환경이슈');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ENV_ISSUE','ISS06','장수명화','에코디자인 환경이슈');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ENV_ISSUE','ISS07','재활용률 향상','에코디자인 환경이슈');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ENV_ISSUE','ISS08','바이오 원료 사용','에코디자인 환경이슈');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('ENV_ISSUE','ISS09','기타','에코디자인 환경이슈');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('HS_TYPE','HS02','화학물질','친환경병원 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('HS_TYPE','HS03','폐기물','친환경병원 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('HS_TYPE','HS04','에너지','친환경병원 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('HS_TYPE','HS08','건축','친환경병원 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('HS_TYPE','HS09','녹색구매','친환경병원 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('HS_TYPE','HS10','기타','친환경병원 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT01','환경산업','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT02','재활용','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT03','융자/보증','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT04','수출','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT05','전시/박람회','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT06','특허/인증','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT07','기술/경영','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT08','은행','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT09','보험','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT10','융자','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('NR_SPRT','SPRT11','대출','알림/자료 기업지원사업');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM01','hanmail.net','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM02','hanafos.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM03','hotmail.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM04','naver.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM05','nate.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM06','dreamwiz.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM07','empal.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM08','freechal.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM09','gmail.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM10','korea.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM11','lycos.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM12','msn.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM13','paran.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM14','yahoo.com','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM15','konetic.or.kr','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('EMAIL','EM16','keiti.re.kr','이메일');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH01','2','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH02','31','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH03','32','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH04','33','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH05','41','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH06','42','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH07','43','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH08','44','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH09','51','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH10','52','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH11','53','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH12','54','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH13','55','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH14','61','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH15','62','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH16','63','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('PH_ZONE','PH17','64','유선전화 지역번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('MOB_ZONE','MOB01','10','휴대전화 식별번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('MOB_ZONE','MOB02','11','휴대전화 식별번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('MOB_ZONE','MOB03','16','휴대전화 식별번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('MOB_ZONE','MOB04','17','휴대전화 식별번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('MOB_ZONE','MOB05','18','휴대전화 식별번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('MOB_ZONE','MOB06','19','휴대전화 식별번호');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SITE_CTYPE','CONN01','환경부 및 소속기관','유관기관 및 단체');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SITE_CTYPE','CONN02','공공기관','유관기관 및 단체');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SITE_CTYPE','CONN03','관련기관/단체/협회','유관기관 및 단체');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SITE_FTYPE','FMLY01','환경연구분야','코네틱 패밀리사이트');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SITE_FTYPE','FMLY02','녹색산업 육성분야','코네틱 패밀리사이트');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SITE_FTYPE','FMLY03','녹색제품 경영분야','코네틱 패밀리사이트');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SITE_FTYPE','FMLY04','해외시장정보분야','코네틱 패밀리사이트');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SITE_FTYPE','FMLY05','무역거래지원','코네틱 패밀리사이트');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SITE_FTYPE','FMLY06','기타','코네틱 패밀리사이트');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IPR_ST','ST01','미출원','지식재산권 상태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IPR_ST','ST02','출원중','지식재산권 상태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('IPR_ST','ST03','등록완료','지식재산권 상태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','NOTICE','공지사항','알림/자료');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','SUPPORT','기업지원사업','알림/자료');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','REFERENCE','자료실','알림/자료>자료실');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','STATS','통계','알림/자료>자료실');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','DS_BIZ','2018년 사업참여자','알림/자료>커뮤니티');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','DS_BIZ','이전년도 사업참여자','알림/자료>커뮤니티');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','TOPIC','안건','알림/자료>커뮤니티');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','RESULT','결과','알림/자료>커뮤니티');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','EXAM','우수사례','환경경영>우수 환경경영 사례');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','POLICY','정책','환경경영>정책/동향');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','TREND','동향','환경경영>정책/동향');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('BLNG_TYPE','1','환경산업체','기업 형태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('BLNG_TYPE','2','일반기업체','기업 형태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('BLNG_TYPE','3','정부/지자체','기업 형태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('BLNG_TYPE','4','공공기관','기업 형태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('BLNG_TYPE','5','대학/연구소','기업 형태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('BLNG_TYPE','6','유관기관/단체','기업 형태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('BLNG_TYPE','7','학생 및 개인','기업 형태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('BLNG_TYPE','99','기타','기업 형태');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','1','비전, 전력 및 방침','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','2','목표 및 계획','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','3','추진조직','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','4','환경경영 교육','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','5','활동성과평가','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','REGULATE','규제대응','환경경영>규제대응');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','HOSPT','친환경병원','친환경병원');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','INTVW','환경경영인인터뷰','환경경영인인터뷰');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CM_BD','SCHEDULE','일정','일정');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('HS_TYPE','HS11','환경경영','친환경병원 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP23','축산폐수','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP24','폐기물소각 및 매립','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('FAMILY_SITE','FAMILY6','기타',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('FAMILY_SITE','FAMILY5','무역거래지원',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('FAMILY_SITE','FAMILY4','해외시장정보분야',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('FAMILY_SITE','FAMILY3','녹색제품 경영분야',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('FAMILY_SITE','FAMILY2','녹색산업 육성분야',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('FAMILY_SITE','FAMILY1','환경연구분야',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CONN_SITE','CONN3','관련기관/단체/협회',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CONN_SITE','CONN2','공공기관',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CONN_SITE','CONN1','환경부 및 소속기관',NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','6','친환경 식자재','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','7','녹색제품 구매','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','8','사회책임활동','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','9','외부 커뮤니케이션','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','10','내부 커뮤니케이션','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','11','녹지공간 활용','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','12','쾌적한 실내환경','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','13','에너지,온실가스 성과관리','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','14','에너지절감활동','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','15','용수 성과관리','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','16','용수절감활동','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','17','환경오염물질 및 재활용 성과관리','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0004','18','환경오염물질 저감 및 재활용 활동','자가진단 체크리스트 항목');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0003','1','일반회원','회원구분');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0003','2','참여병원회원','회원구분');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0003','3','협약병원회원','회원구분');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0003','4','기술관리자','회원구분');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('G0003','5','시스템관리자','회원구분');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS01','폐수','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS02','하수','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS03','가축분뇨','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS04','정수(상수도)','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS05','소각','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS06','매립','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS07','자원화','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS08','대기','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS09','소음진동','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS10','토양환경','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS11','측정분석','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS12','환경경영','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS13','사업지원(인허가)','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS14','기타컨설팅','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS15','악취','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS16','기후변화','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS17','생활환경','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS18','환경규제','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS19','제품인증','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CATE','CS20','오프라인','컨설턴트 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP01','환경경영','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP02','친환경개발','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP03','기후변화대책','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP04','실내공기정화','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP05','대기총량규제','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP06','환경분쟁조정','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP07','신규화학물질','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP08','환경영향평가','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP09','환경신기술평가','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP10','친환경상품인증','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP11','오염방지기술','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP12','측정기술','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('SP_CATE','SP99','기타','전문인력 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP01','수질','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP02','대기','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP03','폐기물/재활용','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP04','소음/진동','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP05','오/폐수','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP06','상하수도','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP07','중수도','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP08','악취','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP09','토양','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP10','에너지','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP11','하천/해양','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP12','자연생태','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP13','유독물/화학약품','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP14','환경규제/인증','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP15','자가측정','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP16','환경분쟁','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP17','인/허가','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP18','환경영향평가','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP19','환경독성/노출평가','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP20','원료재생','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP21','환경기술평가','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP22','환경경영','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_CATE','CP99','기타','컨설팅 기업 분야');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_BIZ_GRP','BG01','방지시설업','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_BIZ_GRP','BG02','설계/시공업','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_BIZ_GRP','BG03','설비시설제조업','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_BIZ_GRP','BG04','측정분석장치제조업','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_BIZ_GRP','BG05','에너지','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_BIZ_GRP','BG06','복원/재활용업','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_BIZ_GRP','BG07','서비스/대행업','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_BIZ_GRP','BG08','경영컨설팅','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_BIZ_GRP','BG09','제품/소재제조업','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_BIZ_GRP','BG10','기타','컨설팅 기업 업종');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR01','서울','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR02','경기/인천','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('CS_CMP_AREA','AR03','경남/부산','컨설팅 기업 지역');
INSERT INTO "C##DQ_TARGET_DEV".TB_CD (CD_GRP_ID,CD_ID,CD_NM,CD_DESC) VALUES ('DEP_ID','7','경영지원',NULL);


INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (1,7,'S','감우성','Lee','NkN2UzYTNiNjYwNGQwZA==','172.16.4.25','Lee@gtone.co.kr','010-7894-1757','Y','Annual leave','20220423165748','20221231235959',1,'20180326141915','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (2,2,'A','강남길','Willie','NkN3UzYTNiNjYwNGQwZA==','172.16.4.26','Willie@gmail.com',NULL,'Y','sick leave','20220423165748','20221231235959',1,'20200928100609','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (3,3,'M','강동원','Quinton','NkN4UzYTNiNjYwNGQwZA==','172.16.4.27','Quinton@naver.com','01078941758','N','Annual leave','20220523165748','20221231235959',1,'20070430180000','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (4,4,'DGM','권상우','Victor','NkN5UzYTNiNjYwNGQwZA==','172.16.4.28','Victor@gtone.co.kr','8201078941758','N','Half day leave','20220523165748','20221231235959',1,'20150625112740','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (5,5,'DM','김강우','Abbott','NkN6UzYTNiNjYwNGQwZA==','172.16.4.29','Abbott@gtone.co.kr','없음','Y',NULL,'20220523165748','20221231235959',1,'20150625112813','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (6,6,'MD','김래원','Bruce','NkN7UzYTNiNjYwNGQwZA==','172.16.4.30','Bruce@gtone.co.kr','내선교환~2','Y','Annual leave','20220523165748','20221231235959',1,'20150609092511','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (7,3,'S','김혜성','Bud','NkN8UzYTNiNjYwNGQwZA==','172.16.4.31','Bud@gtone.co.kr','010-7894-1763','N',NULL,'20220623165748','20221231235959',1,'20151119090546','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (8,4,'S','김윤석','Christopher','NkN9UzYTNiNjYwNGQwZA==','172.16.4.32','Christopher@gtone.co.kr','010-7894-1764','N',NULL,'20220623165748','20221231235959',1,'20151119090636','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (9,5,'A','류승범','Philip','NkN10UzYTNiNjYwNGQwZA==','172.16.4.33','Philip@gtone.co.kr','010-7894-1765','N',NULL,'20220723165748','20221231235959',1,'20140203151458','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (10,3,'A','류승수','Kareem','NkN11UzYTNiNjYwNGQwZA==','172.16.4.34','Kareem@gtone.co.kr','010-7894-1766','Y',NULL,'20220723165748','20221231235959',1,'20140917140501','Y',1,'20220730165748');
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (11,4,'M','류시원','Danny','NkN12UzYTNiNjYwNGQwZA==','172.16.4.35','Danny@gtone.co.kr','010-7894-1767','Y',NULL,'20220723165748','20231231235959',1,'20120628115853','Y',1,'20220730165748');
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (12,5,'DGM','류준열','Jake','NkN13UzYTNiNjYwNGQwZA==','172.16.4.36','Jake@gtone.co.kr','010-7894-1768','N',NULL,'20221023165748','20231231235959',1,'20120628115906','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (13,3,'DM','박상원','Walter','NkN14UzYTNiNjYwNGQwZA==','172.16.4.37','Walter@gtone.co.kr','010-7894-1769','N',NULL,'20221023165748','20231231235959',1,'20120628115927','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (14,4,'S','ㅇㅣㅇㅕㄴㅇㅣㄴ','Zachary','NkN15UzYTNiNjYwNGQwZA==','172.16.4.38','Zachary@gtone.co.kr','010-7894-1770','Y',NULL,'20221023165748','20231231235959',1,'20120628115939','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (15,5,'A','박용우','Tim','NkN16UzYTNiNjYwNGQwZA==','172.16.4.39','Tim@gtone.co.kr','010-7894-1771','Y',NULL,'20221123165748','20231231235959',1,'20120628115949','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (16,1,'M','박용하','F.Murray','NkN17UzYTNiNjYwNGQwZA==','172.16.4.40','F.Murray@gtone.co.kr','010-7894-1772','N',NULL,'20221123165748','20231231235959',1,'20120628120002','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (17,6,'DGM','박해일','Jon','NkN18UzYTNiNjYwNGQwZA==','172.16.4.41','Jon@gtone.co.kr','010-7894-1773','N',NULL,'20221123165748','20211231235959',1,'20130611095453','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (18,2,'DM','박보영','admin','NkN19UzYTNiNjYwNGQwZA==','172.16.4.42','admin@gtone.co.kr','010-7894-1774','1',NULL,'20221023165748','20211231235959',1,'20130611095453','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (19,1,'DGM','수지','suji','NkN20UzYTNiNjYwNGQwZA==','ae81::b4c2:c6a3:d234:e5ae%25','suji@gtone.co.kr','010-7894-1775','Y','Maternity leave','20221123165748','20211231235959',1,'20130611095453','N',NULL,NULL);
INSERT INTO "C##DQ_TARGET_DEV".TB_USER (USER_ID,DEP_ID,POSITION_CODE,USER_NM,LOGIN_ID,USER_PWD,USER_IP,EMAIL,CELL_PHONE,ACTIVE_YN,OFF_DUTY_CODE,LAST_USE_DATE,EXPIRED_DATE,CRE_ID,CRE_DT,DEL_YN,DEL_ID,DEL_DT) VALUES (20,6,'DM','김다미','dami','NkN21UzYTNiNjYwNGQwZA==',NULL,'dami@gtone.co.kr','010-7894-1776','Y',NULL,'20221023165748','20211231235959',1,'20130611095453','N',NULL,NULL);


COMMIT;

spool off;

exit;