INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211019, 1, 'Load Table', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821113, 0, 'Sql File', 'Y', 8211, '', '', 'Y', 'Y', 0, 0, 0, 'Sql File', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821119, 0, 'Sql Node', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'Sql Node', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821122, 0, 'INI Table', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'INI Table', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821123, 0, 'INI Column', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'INI Column', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821124, 0, 'From Table', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'COPY Table', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821125, 0, 'From Column', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'COPY Column', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211012, 1, 'INI Use Table', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211013, 1, 'INI Use Column', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211014, 1, 'Redshift Use Table', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211015, 1, 'Redshift Use Column', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821126, 0, 'Redshift Table', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'Redshift Table', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821127, 0, 'Redshift Column', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'Redshift Column', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211016, 1, 'From Use Table', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211017, 1, 'From Use Column', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO cm_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211018, 1, 'Load Colun', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821112, 0, 'Json File', 'Y', 8211, '', '', 'Y', 'Y', 0, 0, 0, 'Json File', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821114, 0, 'Config File', 'Y', 8211, '', '', 'Y', 'Y', 0, 0, 0, 'Config File', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821115, 0, 'Project Name', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'Project Name', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821116, 0, 'UpProject', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'UpProject', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821117, 0, 'OutPut Node', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'OutPut Node', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821118, 0, 'Project Type', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'Project Type', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821120, 0, 'Param Key Node', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'Param Key Node', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821121, 0, 'Jenkis Stage', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'Jenkis Stage', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821128, 0, 'Ini File', 'Y', 8211, '', '', 'Y', 'Y', 0, 0, 0, 'Ini File', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821129, 0, 'Ini Node', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'Ini Node', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'N', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821130, 0, 'File Node', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'File Node', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821153, 0, 'JSON File', 'Y', 8211, '', '', 'Y', 'Y', 0, 0, 0, 'JSON File', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821154, 0, 'Table', 'Y', 8211, '', '', 'Y', 'Y', 0, 0, 0, 'Table', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (821155, 0, 'Column', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, 'Column', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211002, 1, 'Target File', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211003, 1, 'Output File', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211004, 1, 'Input File', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211005, 1, 'Call Script', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211006, 1, 'Param Value', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211007, 1, 'Jenkins sh 1st Parameter', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211008, 1, 'Jenkins sh 2nd Parameter', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211009, 1, 'Jenkins sh 3rd Parameter', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211010, 1, 'Call Powershell', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211011, 1, 'Jenkins sh run', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211020, 1, 'Ini Node Value', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'Y', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8211028, 1, 'Use SQL File', 'Y', 8211, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

INSERT INTO CM_TYPE
  (TYPE_ID, TYPE_GUBUN, TYPE_NAME, DISPLAY_YN, COMPILER_CODE, TYPE_DESC, TYPE_DESC2, IS_FILE, IS_TARGET, LTL_TGT_ID, LANG_CODE, CALLEE_TYPE_ID, DISPLAY_NAME, IS_FA_TARGET, IS_CLASSDIAGRAM, IS_CLASS, IS_CLASSOPERATION, CLASS_REL_CODE, IS_LIFELINE, IS_ACTIVATION, IS_MESSAGE_LINE, IS_FD_OBJECT, DISPLAY_CHECK_YN, IS_CT_TARGET, IS_PRT_SRC_VIEW, ARGB, HISTORY_YN, MART_YN, CUSTOM_YN)
VALUES
  (8212003, 1, 'call JSON', 'Y', 8212, '', '', 'N', 'N', 0, 0, 0, '', 'N', 'N', '', '', 0, 'N', 'N', 'N', '', 'Y', '', 'N', '', 'N', 'N', 'Y');

