

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (8211012, '', 'Y', '', '', '', 'B', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (8211014, '', 'Y', '', '', 'T', 'F', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (8211013, '', '', '', 'Y', '', 'B', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (8211015, '', '', '', 'Y', 'C', 'F', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (8211016, '', 'Y', '', '', '', 'B', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (8211017, '', '', '', 'Y', '', 'B', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (821126, 'Y', '', '', '', '', '', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (821127, '', '', 'Y', '', '', '', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (8211018, '', '', '', 'Y', '', '', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (8211019, '', 'Y', '', '', '', '', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (821123, '', '', 'Y', '', '', '', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN )
VALUES
  (821122, 'Y', '', '', '', '', '', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (821124, 'Y', '', '', '', '', '', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (821125, '', '', 'Y', '', '', '', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (821113, 'Y', '', '', '', '', '', '', '', '');

INSERT INTO DL_TYPE
  (TYPE_ID, IS_DATASET, IS_DATASET_DPD, IS_ATTRIBUTE, IS_ATTRIBUTE_DPD, DATABASE_DPD_TYPE, DPD_DIRECTION, INCLUDE_ALL_CHILD, NEED_FROM_NODE, SHORT_YN)
VALUES
  (821119, 'Y', '', '', '', '', '', '', '', '');

UPDATE DL_TYPE a
SET a.table_short_yn = 'Y'
WHERE type_id IN ( 821122 , 821126 );

UPDATE DL_TYPE a
SET a.TABLE_DISPLAY_YN = 'Y'
WHERE type_id IN ( 821122  );

COMMIT;