
  CREATE TABLE "IFTMS3001" 
   (	"YM" VARCHAR2(100 BYTE), 
	"JOIN_REGION_CLS" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"BILL_CD" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"AU_TEL_NO_H" VARCHAR2(10 BYTE), 
	"SUBS_POSTAL_CD" VARCHAR2(10 BYTE), 
	"SUBS_PREF_CD" VARCHAR2(10 BYTE), 
	"SUBS_CITY_CD" VARCHAR2(10 BYTE), 
	"CONTACT_CLS" VARCHAR2(10 BYTE), 
	"SUBS_AGE" NUMBER(10,0), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"TARGET_BIRTH_DT" VARCHAR2(10 BYTE), 
	"TAX_FREE_CLS" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_USE_PRD" NUMBER(10,0), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_REGIST_DT" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LUMP_CLS" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(10 BYTE), 
	"SERIAL_NO" VARCHAR2(10 BYTE), 
	"EQUIP_RK" VARCHAR2(10 BYTE), 
	"USE_MODEL_START_DT" VARCHAR2(10 BYTE), 
	"USE_MODEL_USE_PERIOD" NUMBER(10,0), 
	"CHRG_START_DT" VARCHAR2(10 BYTE), 
	"COUNTING_START_DT" VARCHAR2(10 BYTE), 
	"SVC_STATUS_L_CLS" VARCHAR2(10 BYTE), 
	"SVC_STATUS_S_CLS" VARCHAR2(10 BYTE), 
	"SUSPENSION_DT" VARCHAR2(10 BYTE), 
	"RE_USE_DT" VARCHAR2(10 BYTE), 
	"SUBS_TRANS_DT" VARCHAR2(10 BYTE), 
	"SUBS_REOPEN_DT" VARCHAR2(10 BYTE), 
	"CLOSE_DT" VARCHAR2(10 BYTE), 
	"CLOSE_REASON" VARCHAR2(10 BYTE), 
	"OPERATION_DAYS" NUMBER(10,0), 
	"USE_PRD_TOTAL" NUMBER(10,0), 
	"SVC_CLS" VARCHAR2(10 BYTE), 
	"CALL_WIDE_FLG" VARCHAR2(10 BYTE), 
	"GROUP_DSC_FLG" VARCHAR2(10 BYTE), 
	"MULTI_Y_DSC_CLS" VARCHAR2(10 BYTE), 
	"WIN_MULTI_CABLE_DSC_FLG" VARCHAR2(10 BYTE), 
	"AU_HOME_DSC_REGIST_FLG" VARCHAR2(10 BYTE), 
	"PRIORITY_JOINER_FLG" VARCHAR2(10 BYTE), 
	"PRICE_CALL_STOP_TOTAL_CNT" NUMBER(10,0), 
	"TEMP_STOP" NUMBER(10,0), 
	"MODEL_CHANGE_CNT" NUMBER(10,0), 
	"MODEL_TROUBLE_CNT" NUMBER(10,0), 
	"TROUBLE_CNT_TOTAL" NUMBER(10,0), 
	"USED_MODEL_CLS" VARCHAR2(10 BYTE), 
	"WIDE_SPT_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SUBS_STUDENT_AGE" NUMBER(10,0), 
	"MARU_BUSI_DSC_FLG" VARCHAR2(10 BYTE), 
	"OTHER_COMPANY_JOIN_CLS" VARCHAR2(10 BYTE), 
	"FROM_COMPANY_CD" VARCHAR2(10 BYTE), 
	"TO_COMPANY_CD" VARCHAR2(10 BYTE), 
	"G_CALL_DSC_CLS" VARCHAR2(10 BYTE), 
	"PERMISSION_CLS" VARCHAR2(10 BYTE), 
	"HITORI_FLG" VARCHAR2(10 BYTE), 
	"MARU_BUSI_CO_CLS" VARCHAR2(10 BYTE), 
	"SHOP_PURCHASE_METHOD" VARCHAR2(10 BYTE), 
	"RESULT_TRANS_DT" VARCHAR2(10 BYTE), 
	"BF_TRANS_RESULT_CLS" VARCHAR2(10 BYTE), 
	"AF_TRANS_RESULT_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"COLLABO_COMPANY_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3001"."YM" IS 'Year & Month';
   COMMENT ON COLUMN "IFTMS3001"."JOIN_REGION_CLS" IS 'Grade of Jonin Region';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_RK" IS 'Agent PK';
   COMMENT ON COLUMN "IFTMS3001"."BILL_CD" IS 'BIlling Code';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_TYPE" IS 'Agent Type';
   COMMENT ON COLUMN "IFTMS3001"."AU_TEL_NO_H" IS 'AU Tel Number';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_POSTAL_CD" IS 'Agent Postal Code';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_PREF_CD" IS 'Agent Preference Code';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_CITY_CD" IS 'Agent City Code';
   COMMENT ON COLUMN "IFTMS3001"."CONTACT_CLS" IS 'Grade of Contact';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_AGE" IS 'Agent Age';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_GENDER_CLS" IS 'Agent Sex';
   COMMENT ON COLUMN "IFTMS3001"."TARGET_BIRTH_DT" IS 'Due Date';
   COMMENT ON COLUMN "IFTMS3001"."TAX_FREE_CLS" IS 'Tax Free Grade';
   COMMENT ON COLUMN "IFTMS3001"."CUR_PRICE_PLAN_CD" IS 'Current Price Plan Code';
   COMMENT ON COLUMN "IFTMS3001"."CUR_PRICE_PLAN_START_DT" IS 'Current Price Plan Start Date';
   COMMENT ON COLUMN "IFTMS3001"."CUR_PRICE_PLAN_USE_PRD" IS 'Current Price Plan Use Preiod';
   COMMENT ON COLUMN "IFTMS3001"."NEW_PRICE_PLAN_CD" IS 'New Price Plan Code';
   COMMENT ON COLUMN "IFTMS3001"."NEW_PRICE_PLAN_REGIST_DT" IS 'New Price Plan Registration Date';
   COMMENT ON COLUMN "IFTMS3001"."NEW_PRICE_PLAN_START_DT" IS 'New Price Plan Start Date';
   COMMENT ON COLUMN "IFTMS3001"."NEW_JOIN_ACCEPT_SV_AGENCY_CD" IS 'New Join Acceptance Service Agent Code';
   COMMENT ON COLUMN "IFTMS3001"."NEW_JOIN_ACCEPT_SHOP_CD" IS 'New Join Accpetance Shop Code';
   COMMENT ON COLUMN "IFTMS3001"."NEW_JOIN_DELIVERY_SV_AGENCY_CD" IS 'New Join Delivery Service AGent Code';
   COMMENT ON COLUMN "IFTMS3001"."NEW_JOIN_DELIVERY_SHOP_CD" IS 'New Join Delivery Shop Code';
   COMMENT ON COLUMN "IFTMS3001"."LATEST_ACCEPT_SV_AGENCY_CD" IS 'Latest Accpetance Service Agent Code';
   COMMENT ON COLUMN "IFTMS3001"."LATEST_ACCEPT_SHOP_CD" IS 'Lastest Acceptance Shop Code';
   COMMENT ON COLUMN "IFTMS3001"."LATEST_DELIVERY_SV_AGENCY_CD" IS 'Latest Delivery Service Agent Code';
   COMMENT ON COLUMN "IFTMS3001"."LATEST_DELIVERY_SHOP_CD" IS 'Latest Delivery Shop Code';
   COMMENT ON COLUMN "IFTMS3001"."LUMP_CLS" IS 'Lump Grade';
   COMMENT ON COLUMN "IFTMS3001"."TYPE" IS 'Type';
   COMMENT ON COLUMN "IFTMS3001"."SERIAL_NO" IS 'Serial Number';
   COMMENT ON COLUMN "IFTMS3001"."EQUIP_RK" IS 'Equipment Grade';
   COMMENT ON COLUMN "IFTMS3001"."USE_MODEL_START_DT" IS 'Start Date of Using Model';
   COMMENT ON COLUMN "IFTMS3001"."USE_MODEL_USE_PERIOD" IS 'Model Use Period';
   COMMENT ON COLUMN "IFTMS3001"."CHRG_START_DT" IS 'Charge Start Date';
   COMMENT ON COLUMN "IFTMS3001"."COUNTING_START_DT" IS 'Counting Start Date';
   COMMENT ON COLUMN "IFTMS3001"."SVC_STATUS_L_CLS" IS 'Service Status L Grade';
   COMMENT ON COLUMN "IFTMS3001"."SVC_STATUS_S_CLS" IS 'Service Status S Grade';
   COMMENT ON COLUMN "IFTMS3001"."SUSPENSION_DT" IS 'Suspension Date';
   COMMENT ON COLUMN "IFTMS3001"."RE_USE_DT" IS 'Reuse Date';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_TRANS_DT" IS 'Agent Transaction Date';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_REOPEN_DT" IS 'Agent Reopen Date';
   COMMENT ON COLUMN "IFTMS3001"."CLOSE_DT" IS 'Close Date';
   COMMENT ON COLUMN "IFTMS3001"."CLOSE_REASON" IS 'Close Reason';
   COMMENT ON COLUMN "IFTMS3001"."OPERATION_DAYS" IS 'Operation Days';
   COMMENT ON COLUMN "IFTMS3001"."USE_PRD_TOTAL" IS 'Total Use Period';
   COMMENT ON COLUMN "IFTMS3001"."SVC_CLS" IS 'Service Grade';
   COMMENT ON COLUMN "IFTMS3001"."CALL_WIDE_FLG" IS 'Call Wide Flag';
   COMMENT ON COLUMN "IFTMS3001"."GROUP_DSC_FLG" IS 'Group Description Flag';
   COMMENT ON COLUMN "IFTMS3001"."MULTI_Y_DSC_CLS" IS 'Multi Year Description Grade';
   COMMENT ON COLUMN "IFTMS3001"."WIN_MULTI_CABLE_DSC_FLG" IS 'Multi Cable Description Flag';
   COMMENT ON COLUMN "IFTMS3001"."AU_HOME_DSC_REGIST_FLG" IS 'AU Home Description Registration Flag';
   COMMENT ON COLUMN "IFTMS3001"."PRIORITY_JOINER_FLG" IS 'Priority Joiner Flag';
   COMMENT ON COLUMN "IFTMS3001"."PRICE_CALL_STOP_TOTAL_CNT" IS 'Total Count of Price Call Stop';
   COMMENT ON COLUMN "IFTMS3001"."TEMP_STOP" IS 'Temporary Stop';
   COMMENT ON COLUMN "IFTMS3001"."MODEL_CHANGE_CNT" IS 'Model Change Count';
   COMMENT ON COLUMN "IFTMS3001"."MODEL_TROUBLE_CNT" IS 'Model Trouble Count';
   COMMENT ON COLUMN "IFTMS3001"."TROUBLE_CNT_TOTAL" IS 'Total Trouble Count';
   COMMENT ON COLUMN "IFTMS3001"."USED_MODEL_CLS" IS 'Used Model Grade';
   COMMENT ON COLUMN "IFTMS3001"."WIDE_SPT_APPLY_FLG" IS 'Wide Spot Apply Flag';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_STUDENT_AGE" IS 'Student Age';
   COMMENT ON COLUMN "IFTMS3001"."MARU_BUSI_DSC_FLG" IS 'Business Description Flag';
   COMMENT ON COLUMN "IFTMS3001"."OTHER_COMPANY_JOIN_CLS" IS 'Other Company Join Grade';
   COMMENT ON COLUMN "IFTMS3001"."FROM_COMPANY_CD" IS 'Orginal Company Code';
   COMMENT ON COLUMN "IFTMS3001"."TO_COMPANY_CD" IS 'New Company Code';
   COMMENT ON COLUMN "IFTMS3001"."G_CALL_DSC_CLS" IS 'Call Description Grade';
   COMMENT ON COLUMN "IFTMS3001"."PERMISSION_CLS" IS 'Permission Grade';
   COMMENT ON COLUMN "IFTMS3001"."HITORI_FLG" IS 'History Flag';
   COMMENT ON COLUMN "IFTMS3001"."MARU_BUSI_CO_CLS" IS 'Business Code Grade';
   COMMENT ON COLUMN "IFTMS3001"."SHOP_PURCHASE_METHOD" IS 'Shop Purchase Method';
   COMMENT ON COLUMN "IFTMS3001"."RESULT_TRANS_DT" IS 'Result Transaction Date';
   COMMENT ON COLUMN "IFTMS3001"."BF_TRANS_RESULT_CLS" IS 'BF Transaction Result Grade';
   COMMENT ON COLUMN "IFTMS3001"."AF_TRANS_RESULT_CLS" IS 'AF Transaction Result Grade';
   COMMENT ON COLUMN "IFTMS3001"."FIRST_CHRG_START_DT" IS 'First Charge Start Date';
   COMMENT ON COLUMN "IFTMS3001"."COLLABO_COMPANY_FLG" IS 'Collaboration Company Flag';
   COMMENT ON TABLE "IFTMS3001"  IS 'Market Structure 3001';


  CREATE TABLE "IFTMS3002" 
   (	"AF_TRANS_JOIN_ACCEPT_SHOP_CD" VARCHAR2(100 BYTE), 
	"AF_TRANS_JOIN_ACCEPT_SV_CD" VARCHAR2(10 BYTE), 
	"AF_TRANS_SUBS_REGION_CD" VARCHAR2(10 BYTE), 
	"AF_TRANS_SUBS_REGION_CLS" VARCHAR2(10 BYTE), 
	"COLLABO_COMPANY_FLG" VARCHAR2(10 BYTE), 
	"CUR_DSC_OP4_CD" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"DEMO_CLS" VARCHAR2(10 BYTE), 
	"EZWEB_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"INTEGRATE_BILL_ACCOUNT" VARCHAR2(10 BYTE), 
	"JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"JOIN_ACCEPT_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"JOIN_DELIVERY_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"LAST_INSERT_DT" VARCHAR2(10 BYTE), 
	"LAST_INSERT_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LAST_UIM_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LAST_UIM_MODEL_SALE_DT" VARCHAR2(10 BYTE), 
	"LATEST_INSERT_DT" VARCHAR2(10 BYTE), 
	"LATEST_INSERT_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LATEST_UIM_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LATEST_UIM_MODEL_SALE_DT" VARCHAR2(10 BYTE), 
	"LATEST_USE_MODEL_EQUIP_RK" VARCHAR2(10 BYTE), 
	"LATEST_USE_MODEL_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"MVNO_CLS" VARCHAR2(10 BYTE), 
	"NEW_DSC_OP4CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"OLD_BILL_CD" VARCHAR2(10 BYTE), 
	"PAY_GROUP" VARCHAR2(10 BYTE), 
	"PCKT_SINGLE_CLS" VARCHAR2(10 BYTE), 
	"SMVL_ABO_REASON" VARCHAR2(10 BYTE), 
	"SMVL_ABO_YM" VARCHAR2(10 BYTE), 
	"SMVL_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"SMVL_ACCEPT_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"SMVL_APPLI_ACCEPT_DT" VARCHAR2(10 BYTE), 
	"SMVL_APPLI_FLG" VARCHAR2(10 BYTE), 
	"SMVL_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_AUTO_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_GROUP_CD" VARCHAR2(10 BYTE), 
	"SMVL_LINK_CLS" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_ABO_REASON" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_CLS" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_END_DT" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_START_DT" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_CLS_CD" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_END_M" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_END_PLAN_M" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_START_DT" VARCHAR2(10 BYTE), 
	"SMVL_START_YM" VARCHAR2(10 BYTE), 
	"SUBS_AGE" VARCHAR2(10 BYTE), 
	"SUBS_DIV_FLG" VARCHAR2(10 BYTE), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"SUBS_REGION_CD" VARCHAR2(10 BYTE), 
	"SUBS_REGION_CLS" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"SUBS_STUDENT_AGE" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"SVC_CLS" VARCHAR2(10 BYTE), 
	"SVC_STATUS_L_CLS" VARCHAR2(10 BYTE), 
	"SVC_STATUS_S_CLS" VARCHAR2(10 BYTE), 
	"TARGET_AGE" VARCHAR2(10 BYTE), 
	"TARGET_STUDENT_AGE" VARCHAR2(10 BYTE), 
	"USED_MODEL_CLS" VARCHAR2(10 BYTE), 
	"USE_MODEL_START_DT" VARCHAR2(10 BYTE), 
	"YM" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3002"."AF_TRANS_JOIN_ACCEPT_SHOP_CD" IS 'AF Transaction Join Acceptance Shop Code';
   COMMENT ON COLUMN "IFTMS3002"."AF_TRANS_JOIN_ACCEPT_SV_CD" IS 'AF Transaction Join Acceptance Service Code';
   COMMENT ON COLUMN "IFTMS3002"."AF_TRANS_SUBS_REGION_CD" IS 'AF Transaction Agent Region Code';
   COMMENT ON COLUMN "IFTMS3002"."AF_TRANS_SUBS_REGION_CLS" IS 'AF Transaction Agent Region Grade';
   COMMENT ON COLUMN "IFTMS3002"."COLLABO_COMPANY_FLG" IS 'Collaboration Company Flag';
   COMMENT ON COLUMN "IFTMS3002"."CUR_DSC_OP4_CD" IS 'Current Description Operation Code';
   COMMENT ON COLUMN "IFTMS3002"."CUR_PRICE_PLAN_CD" IS 'Current Price Plan Code';
   COMMENT ON COLUMN "IFTMS3002"."DEMO_CLS" IS 'Demo Grade';
   COMMENT ON COLUMN "IFTMS3002"."EZWEB_CLS" IS 'Web Grade';
   COMMENT ON COLUMN "IFTMS3002"."FIRST_CHRG_START_DT" IS 'First Chage Start Date';
   COMMENT ON COLUMN "IFTMS3002"."INTEGRATE_BILL_ACCOUNT" IS 'Integrated Billing Account';
   COMMENT ON COLUMN "IFTMS3002"."JOIN_ACCEPT_SHOP_CD" IS 'Join Acceptance Shop Code';
   COMMENT ON COLUMN "IFTMS3002"."JOIN_ACCEPT_SUPERVISOR_CD" IS 'Join Acceptance Supervisor Code';
   COMMENT ON COLUMN "IFTMS3002"."JOIN_DELIVERY_SHOP_CD" IS 'Join Delivery Shop Code';
   COMMENT ON COLUMN "IFTMS3002"."JOIN_DELIVERY_SUPERVISOR_CD" IS 'Join Delivery Supervisor Code';
   COMMENT ON COLUMN "IFTMS3002"."LAST_INSERT_DT" IS 'Last Inserting Date';
   COMMENT ON COLUMN "IFTMS3002"."LAST_INSERT_EQUIP_SYS_RK" IS 'Last Inserting Equipment System Rank';
   COMMENT ON COLUMN "IFTMS3002"."LAST_UIM_EQUIP_SYS_RK" IS 'Last UIM Equipment System Rank';
   COMMENT ON COLUMN "IFTMS3002"."LAST_UIM_MODEL_SALE_DT" IS 'Last UIM Model Sale Date';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_INSERT_DT" IS 'Latest Inserting Date';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_INSERT_EQUIP_SYS_RK" IS 'Latest Inerting Equipment System Rank';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_UIM_EQUIP_SYS_RK" IS 'Latest UIM Equipment System Rank';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_UIM_MODEL_SALE_DT" IS 'Latest UIM Model Sale Date';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_USE_MODEL_EQUIP_RK" IS 'Latest Use Model Equipment Rank';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_USE_MODEL_EQUIP_SYS_RK" IS 'Latest Use Model Equipment System Rank';
   COMMENT ON COLUMN "IFTMS3002"."MVNO_CLS" IS 'MVNO Grade';
   COMMENT ON COLUMN "IFTMS3002"."NEW_DSC_OP4CD" IS 'New Description';
   COMMENT ON COLUMN "IFTMS3002"."NEW_PRICE_PLAN_CD" IS 'New Price Plan Code';
   COMMENT ON COLUMN "IFTMS3002"."OLD_BILL_CD" IS 'Old Billing Code';
   COMMENT ON COLUMN "IFTMS3002"."PAY_GROUP" IS 'Payment Group';
   COMMENT ON COLUMN "IFTMS3002"."PCKT_SINGLE_CLS" IS 'Pocket Single Grade';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ABO_REASON" IS 'ABO Reason';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ABO_YM" IS 'ABO Year & Month';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ACCEPT_SHOP_CD" IS 'Accpetance Shop Code';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ACCEPT_SUPERVISOR_CD" IS 'Acceptance Supervisor Code';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_APPLI_ACCEPT_DT" IS 'Application Acceptance Date';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_APPLI_FLG" IS 'Application Flag';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_APPLY_FLG" IS 'Application Flag2';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_AUTO_APPLY_FLG" IS 'Auto Application Flag';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_GROUP_CD" IS 'Group Code';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_LINK_CLS" IS 'Link Grade';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ROUTER_DSC_ABO_REASON" IS 'Router ABO Reason';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ROUTER_DSC_CLS" IS 'Router Description';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ROUTER_DSC_END_DT" IS 'Router End Date';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ROUTER_DSC_START_DT" IS 'Router Start Date';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_SP_DSC_APPLY_FLG" IS 'SP Application Flag';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_SP_DSC_CLS_CD" IS 'SP Grade Code';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_SP_DSC_END_M" IS 'SP End Month';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_SP_DSC_END_PLAN_M" IS 'SP End Plan';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_SP_DSC_START_DT" IS 'SP Start Date';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_START_YM" IS 'SM Start Month & Year';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_AGE" IS 'Agent Age';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_DIV_FLG" IS 'Agent Division Flag';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_GENDER_CLS" IS 'Agent Gener';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_REGION_CD" IS 'Agent Region COde';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_REGION_CLS" IS 'Agent Resion Grade';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_RK" IS 'Agent Rank';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_STUDENT_AGE" IS 'Agent Student Age';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_TYPE" IS 'Agent Type';
   COMMENT ON COLUMN "IFTMS3002"."SVC_CLS" IS 'Service Grade';
   COMMENT ON COLUMN "IFTMS3002"."SVC_STATUS_L_CLS" IS 'Service Status L Grade';
   COMMENT ON COLUMN "IFTMS3002"."SVC_STATUS_S_CLS" IS 'Service Status S Grade';
   COMMENT ON COLUMN "IFTMS3002"."TARGET_AGE" IS 'Target Age';
   COMMENT ON COLUMN "IFTMS3002"."TARGET_STUDENT_AGE" IS 'Target Student Age';
   COMMENT ON COLUMN "IFTMS3002"."USED_MODEL_CLS" IS 'Used Model Grade';
   COMMENT ON COLUMN "IFTMS3002"."USE_MODEL_START_DT" IS 'Used Model Start Date';
   COMMENT ON COLUMN "IFTMS3002"."YM" IS 'Year & Month';
   COMMENT ON TABLE "IFTMS3002"  IS 'Market Structure 3002';


  CREATE TABLE "IFTMS3003" 
   (	"SUPERVISOR_CD" VARCHAR2(100 BYTE), 
	"SHOP_CD" VARCHAR2(10 BYTE), 
	"SHOP_NAME" VARCHAR2(10 BYTE), 
	"SHOP_SHORT_NAME" VARCHAR2(10 BYTE), 
	"REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_NAME" VARCHAR2(10 BYTE), 
	"SHOP_HANDLE_CD" VARCHAR2(10 BYTE), 
	"SHOP_POSTAL_CD" VARCHAR2(10 BYTE), 
	"SHOP_PREF_CD" VARCHAR2(10 BYTE), 
	"SHOP_CITY_CD" VARCHAR2(10 BYTE), 
	"SHOP_CLS" VARCHAR2(10 BYTE), 
	"INSTAL_SALE_CLS" VARCHAR2(10 BYTE), 
	"AU_AGENCY_CLS" VARCHAR2(10 BYTE), 
	"MVNO_CLS" VARCHAR2(10 BYTE), 
	"GROUP_CD_SV" VARCHAR2(10 BYTE), 
	"GROUP_CD_SHOP" VARCHAR2(10 BYTE), 
	"GROUP_CLS" VARCHAR2(10 BYTE), 
	"DIST_AF_SHOP" VARCHAR2(10 BYTE), 
	"MONOPOLY_CLS" VARCHAR2(10 BYTE)
   )
   ;

   COMMENT ON COLUMN "IFTMS3003"."SUPERVISOR_CD" IS 'Supervisor Code';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_CD" IS 'Shop Code';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_NAME" IS 'Shop Name';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_SHORT_NAME" IS 'Store Name';
   COMMENT ON COLUMN "IFTMS3003"."REGION_CD" IS 'Region Code';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_REGION_CD" IS 'Shop Region Code';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_REGION_NAME" IS 'Shop Region Name';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_HANDLE_CD" IS 'Shop Handle Code';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_POSTAL_CD" IS 'Shop Postal Code';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_PREF_CD" IS 'Shop Free Code';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_CITY_CD" IS 'Shop City Code';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_CLS" IS 'Shop Grade';
   COMMENT ON COLUMN "IFTMS3003"."INSTAL_SALE_CLS" IS 'Installation Sales Grade';
   COMMENT ON COLUMN "IFTMS3003"."AU_AGENCY_CLS" IS 'AU Agent Grade';
   COMMENT ON COLUMN "IFTMS3003"."MVNO_CLS" IS 'MVNO Grade';
   COMMENT ON COLUMN "IFTMS3003"."GROUP_CD_SV" IS 'Service Group Code';
   COMMENT ON COLUMN "IFTMS3003"."GROUP_CD_SHOP" IS 'Shop Group Code';
   COMMENT ON COLUMN "IFTMS3003"."DIST_AF_SHOP" IS 'AF Shop';
   COMMENT ON COLUMN "IFTMS3003"."MONOPOLY_CLS" IS 'Monopoly Grade';
   COMMENT ON TABLE "IFTMS3003"  IS 'Market Structure 3003';


  CREATE TABLE "IFTMS3004" 
   (	"YM" VARCHAR2(100 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"AU_ID_PWD_UPD_DT" VARCHAR2(10 BYTE), 
	"AU_ID_PWD_UPD_TM" VARCHAR2(10 BYTE), 
	"PWD_INITIAL_CHANGE_CLS" VARCHAR2(10 BYTE), 
	"APPLY_LOCK_CLS" VARCHAR2(10 BYTE), 
	"APPLY_LOCK_REASON_CLS" VARCHAR2(10 BYTE), 
	"AU_ID_TRANS_DETER_CLS" VARCHAR2(10 BYTE), 
	"ALIAS_AU_ID_CHG_CNT" NUMBER(10,0), 
	"AU_ID_INTERGRATE_SP_CNT" NUMBER(10,0), 
	"IOT_ID_CLS" VARCHAR2(10 BYTE), 
	"ACTIVE_DT" VARCHAR2(10 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE), 
	"CHURN_IN_DT" VARCHAR2(10 BYTE), 
	"CHURN_IN_SUBS_RK" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3004"."YM" IS 'Year and Month';
   COMMENT ON COLUMN "IFTMS3004"."AU_ID" IS 'AU ID';
   COMMENT ON COLUMN "IFTMS3004"."AU_ID_PWD_UPD_DT" IS 'AU ID Password Update Date';
   COMMENT ON COLUMN "IFTMS3004"."AU_ID_PWD_UPD_TM" IS 'AU ID Password Update Time';
   COMMENT ON COLUMN "IFTMS3004"."PWD_INITIAL_CHANGE_CLS" IS 'Password Change Grade';
   COMMENT ON COLUMN "IFTMS3004"."APPLY_LOCK_CLS" IS 'Application Lock Grade';
   COMMENT ON COLUMN "IFTMS3004"."APPLY_LOCK_REASON_CLS" IS 'Application Lock Reason';
   COMMENT ON COLUMN "IFTMS3004"."AU_ID_TRANS_DETER_CLS" IS 'AU ID Transaction Grade';
   COMMENT ON COLUMN "IFTMS3004"."ALIAS_AU_ID_CHG_CNT" IS 'Alias AU ID Change Count';
   COMMENT ON COLUMN "IFTMS3004"."AU_ID_INTERGRATE_SP_CNT" IS 'AU ID Integrated SP Count';
   COMMENT ON COLUMN "IFTMS3004"."IOT_ID_CLS" IS 'IoT ID Grade';
   COMMENT ON COLUMN "IFTMS3004"."ACTIVE_DT" IS 'Activated Date';
   COMMENT ON COLUMN "IFTMS3004"."ACTIVE_TM" IS 'Activated Time';
   COMMENT ON COLUMN "IFTMS3004"."INVALID_DT" IS 'Invalid Date';
   COMMENT ON COLUMN "IFTMS3004"."INVALID_TM" IS 'Invalid Time';
   COMMENT ON COLUMN "IFTMS3004"."INVALID_FLG" IS 'Invalid Flag';
   COMMENT ON COLUMN "IFTMS3004"."CHURN_IN_DT" IS 'Import Date';
   COMMENT ON COLUMN "IFTMS3004"."CHURN_IN_SUBS_RK" IS 'Import Agent Rank';
   COMMENT ON TABLE "IFTMS3004"  IS 'Market Structure 3004';


  CREATE TABLE "IFTMS3005" 
   (	"ACTIVE_DT" VARCHAR2(100 BYTE), 
	"APPROVAL_TICKET_ID" VARCHAR2(10 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"BIRTH_DT" VARCHAR2(10 BYTE), 
	"CUST_CLS" VARCHAR2(10 BYTE), 
	"CUST_FIRST_REGIST_DT" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"CUST_MAIL1_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"CUST_MAIL2_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"CUST_PWD_UPD_DT" VARCHAR2(10 BYTE), 
	"CUST_PWD_UPD_TM" VARCHAR2(10 BYTE), 
	"DELE_AU_SUBS_RK" VARCHAR2(10 BYTE), 
	"EZ_MAIL_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"GENDER_CLS" VARCHAR2(10 BYTE), 
	"IDENTIFICATION_DT" VARCHAR2(10 BYTE), 
	"IDENTIFICATION_LEVEL" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE), 
	"PWD_INITIAL_CHANGE_CLS" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3005"."ACTIVE_DT" IS 'Activated Date';
   COMMENT ON COLUMN "IFTMS3005"."APPROVAL_TICKET_ID" IS 'Ticket ID';
   COMMENT ON COLUMN "IFTMS3005"."AU_ID" IS 'AU ID';
   COMMENT ON COLUMN "IFTMS3005"."BIRTH_DT" IS 'Birthday';
   COMMENT ON COLUMN "IFTMS3005"."CUST_CLS" IS 'Customer Grade';
   COMMENT ON COLUMN "IFTMS3005"."CUST_FIRST_REGIST_DT" IS 'First Customer Registration Date';
   COMMENT ON COLUMN "IFTMS3005"."CUST_ID" IS 'Customer ID';
   COMMENT ON COLUMN "IFTMS3005"."CUST_MAIL1_NOTICE_FLG" IS 'Customer Notice Flag';
   COMMENT ON COLUMN "IFTMS3005"."CUST_MAIL2_NOTICE_FLG" IS 'Customer Notice Flag2';
   COMMENT ON COLUMN "IFTMS3005"."CUST_PWD_UPD_DT" IS 'Customer Password Update Date';
   COMMENT ON COLUMN "IFTMS3005"."CUST_PWD_UPD_TM" IS 'Customer Password Update Time';
   COMMENT ON COLUMN "IFTMS3005"."DELE_AU_SUBS_RK" IS 'AU Agent Rank';
   COMMENT ON COLUMN "IFTMS3005"."EZ_MAIL_NOTICE_FLG" IS 'Mail Notification Flag';
   COMMENT ON COLUMN "IFTMS3005"."GENDER_CLS" IS 'Gender Grade';
   COMMENT ON COLUMN "IFTMS3005"."IDENTIFICATION_DT" IS 'Idfication Date';
   COMMENT ON COLUMN "IFTMS3005"."IDENTIFICATION_LEVEL" IS 'Identification Level';
   COMMENT ON COLUMN "IFTMS3005"."INVALID_DT" IS 'Invalid Date';
   COMMENT ON COLUMN "IFTMS3005"."INVALID_FLG" IS 'Invalid Flag';
   COMMENT ON COLUMN "IFTMS3005"."PWD_INITIAL_CHANGE_CLS" IS 'Password Change Grade';
   COMMENT ON TABLE "IFTMS3005"  IS 'Market Structure 3005';


  CREATE TABLE "IFTMS3006" 
   (	"ACTIVE_DT" VARCHAR2(100 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"SUBS_CLS" VARCHAR2(10 BYTE), 
	"SUBS_ID" VARCHAR2(10 BYTE), 
	"SUBS_LINK_STATUS_CD" VARCHAR2(10 BYTE), 
	"YM" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3006"."ACTIVE_DT" IS 'Activated Date';
   COMMENT ON COLUMN "IFTMS3006"."ACTIVE_TM" IS 'Activated Time';
   COMMENT ON COLUMN "IFTMS3006"."CUST_ID" IS 'Customer ID';
   COMMENT ON COLUMN "IFTMS3006"."INVALID_DT" IS 'Invalid Date';
   COMMENT ON COLUMN "IFTMS3006"."INVALID_FLG" IS 'Invalid Flag';
   COMMENT ON COLUMN "IFTMS3006"."INVALID_TM" IS 'Invalid Time';
   COMMENT ON COLUMN "IFTMS3006"."SUBS_CLS" IS 'Agent Grade';
   COMMENT ON COLUMN "IFTMS3006"."SUBS_ID" IS 'Agent ID';
   COMMENT ON COLUMN "IFTMS3006"."SUBS_LINK_STATUS_CD" IS 'Agent Link Status Code';
   COMMENT ON COLUMN "IFTMS3006"."YM" IS 'Year & Month';
   COMMENT ON TABLE "IFTMS3006"  IS 'Market Structure 3006';


  CREATE TABLE "IFTMS3007" 
   (	"ACTIVE_DT" VARCHAR2(100 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"DELE_SUBS_ID" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"SUBS_CLS" VARCHAR2(10 BYTE), 
	"YM" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3007"."ACTIVE_DT" IS 'Activated Date';
   COMMENT ON COLUMN "IFTMS3007"."ACTIVE_TM" IS 'Activated Time';
   COMMENT ON COLUMN "IFTMS3007"."CUST_ID" IS 'Customer ID';
   COMMENT ON COLUMN "IFTMS3007"."DELE_SUBS_ID" IS 'Agent ID';
   COMMENT ON COLUMN "IFTMS3007"."INVALID_DT" IS 'Invalid Date';
   COMMENT ON COLUMN "IFTMS3007"."INVALID_FLG" IS 'Invalid Flag';
   COMMENT ON COLUMN "IFTMS3007"."INVALID_TM" IS 'Invalid Time';
   COMMENT ON COLUMN "IFTMS3007"."SUBS_CLS" IS 'Agent Grade';
   COMMENT ON COLUMN "IFTMS3007"."YM" IS 'Year & Month';
   COMMENT ON TABLE "IFTMS3007"  IS 'Market Structure 3007';


  CREATE TABLE "K_MONTH_AUID" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"AU_ID_PWD_UPD_DT" VARCHAR2(10 BYTE), 
	"AU_ID_PWD_UPD_TM" VARCHAR2(10 BYTE), 
	"PWD_INITIAL_CHANGE_CLS" VARCHAR2(10 BYTE), 
	"APPLY_LOCK_CLS" VARCHAR2(10 BYTE), 
	"APPLY_LOCK_REASON_CLS" VARCHAR2(10 BYTE), 
	"AU_ID_TRANS_DETER_CLS" VARCHAR2(10 BYTE), 
	"ALIAS_AU_ID_CHG_CNT" NUMBER(10,0), 
	"AU_ID_INTERGRATE_SP_CNT" NUMBER(10,0), 
	"IOT_ID_CLS" VARCHAR2(10 BYTE), 
	"ACTIVE_DT" VARCHAR2(10 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE), 
	"CHURN_IN_DT" VARCHAR2(10 BYTE), 
	"CHURN_IN_SUBS_RK" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "K_MONTH_AUID"."ACQ_DT" IS 'Acquired Date';
   COMMENT ON COLUMN "K_MONTH_AUID"."YM" IS 'Year & Month';
   COMMENT ON COLUMN "K_MONTH_AUID"."AU_ID" IS 'AU ID';
   COMMENT ON COLUMN "K_MONTH_AUID"."AU_ID_PWD_UPD_DT" IS 'AU ID Password Update Date';
   COMMENT ON COLUMN "K_MONTH_AUID"."AU_ID_PWD_UPD_TM" IS 'AU ID Password Update Time';
   COMMENT ON COLUMN "K_MONTH_AUID"."PWD_INITIAL_CHANGE_CLS" IS 'Password Change Grade';
   COMMENT ON COLUMN "K_MONTH_AUID"."APPLY_LOCK_CLS" IS 'Application Lock Grade';
   COMMENT ON COLUMN "K_MONTH_AUID"."APPLY_LOCK_REASON_CLS" IS 'Application Lock Reason Grade';
   COMMENT ON COLUMN "K_MONTH_AUID"."AU_ID_TRANS_DETER_CLS" IS 'AU ID Transaction Grade';
   COMMENT ON COLUMN "K_MONTH_AUID"."ALIAS_AU_ID_CHG_CNT" IS 'AU ID Change Count';
   COMMENT ON COLUMN "K_MONTH_AUID"."AU_ID_INTERGRATE_SP_CNT" IS 'AU ID Integrated SP Count';
   COMMENT ON COLUMN "K_MONTH_AUID"."IOT_ID_CLS" IS 'IoT ID Grade';
   COMMENT ON COLUMN "K_MONTH_AUID"."ACTIVE_DT" IS 'Activated Date';
   COMMENT ON COLUMN "K_MONTH_AUID"."ACTIVE_TM" IS 'Activated Time';
   COMMENT ON COLUMN "K_MONTH_AUID"."INVALID_DT" IS 'Invalid Date';
   COMMENT ON COLUMN "K_MONTH_AUID"."INVALID_TM" IS 'Invalid Time';
   COMMENT ON COLUMN "K_MONTH_AUID"."INVALID_FLG" IS 'Invalid Flag';
   COMMENT ON COLUMN "K_MONTH_AUID"."CHURN_IN_DT" IS 'Import Date';
   COMMENT ON COLUMN "K_MONTH_AUID"."CHURN_IN_SUBS_RK" IS 'Import Agent Rank';
   COMMENT ON TABLE "K_MONTH_AUID"  IS 'K_월AUID';


  CREATE TABLE "K_MONTH_CUST_INF" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"SUBS_REGION_CLS" VARCHAR2(10 BYTE), 
	"SUBS_REGION_CD" VARCHAR2(10 BYTE), 
	"SVC_STATUS_L_CLS" VARCHAR2(10 BYTE), 
	"SVC_STATUS_S_CLS" VARCHAR2(10 BYTE), 
	"OLD_BILL_CD" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"SUBS_AGE" NUMBER(10,0), 
	"SUBS_STUDENT_AGE" NUMBER(10,0), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"JOIN_ACCEPT_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"JOIN_DELIVERY_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"AF_TRANS_SUBS_REGION_CLS" VARCHAR2(10 BYTE), 
	"AF_TRANS_SUBS_REGION_CD" VARCHAR2(10 BYTE), 
	"AF_TRANS_JOIN_ACCEPT_SV_CD" VARCHAR2(10 BYTE), 
	"AF_TRANS_JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"LAST_UIM_MODEL_SALE_DT" VARCHAR2(10 BYTE), 
	"LAST_UIM_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LATEST_UIM_MODEL_SALE_DT" VARCHAR2(10 BYTE), 
	"LATEST_UIM_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LAST_INSERT_DT" VARCHAR2(10 BYTE), 
	"LAST_INSERT_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LATEST_INSERT_DT" VARCHAR2(10 BYTE), 
	"LATEST_INSERT_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"SUBS_DIV_FLG" VARCHAR2(10 BYTE), 
	"MVNO_CLS" VARCHAR2(10 BYTE), 
	"TARGET_STUDENT_AGE" NUMBER(10,0), 
	"TARGET_AGE" NUMBER(10,0), 
	"DEMO_CLS" VARCHAR2(10 BYTE), 
	"PAY_GROUP" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"CUR_DSC_OP4_CD" VARCHAR2(10 BYTE), 
	"COLLABO_COMPANY_FLG" VARCHAR2(10 BYTE), 
	"USED_MODEL_CLS" VARCHAR2(10 BYTE), 
	"USE_MODEL_START_DT" VARCHAR2(10 BYTE), 
	"SVC_CLS" VARCHAR2(10 BYTE), 
	"EZWEB_CLS" VARCHAR2(10 BYTE), 
	"SMVL_GROUP_CD" VARCHAR2(10 BYTE), 
	"SMVL_START_YM" VARCHAR2(10 BYTE), 
	"SMVL_ABO_YM" VARCHAR2(10 BYTE), 
	"SMVL_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_APPLI_FLG" VARCHAR2(10 BYTE), 
	"SMVL_ABO_REASON" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_CLS" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_START_DT" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_END_DT" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_ABO_REASON" VARCHAR2(10 BYTE), 
	"SMVL_APPLI_ACCEPT_DT" VARCHAR2(10 BYTE), 
	"SMVL_ACCEPT_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"SMVL_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"SMVL_AUTO_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_LINK_CLS" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_START_DT" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_END_M" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_END_PLAN_M" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_CLS_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"NEW_DSC_OP4CD" VARCHAR2(10 BYTE), 
	"LATEST_USE_MODEL_EQUIP_RK" VARCHAR2(10 BYTE), 
	"LATEST_USE_MODEL_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"PCKT_SINGLE_CLS" VARCHAR2(10 BYTE), 
	"INTEGRATE_BILL_ACCOUNT" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "K_MONTH_CUST_INF"."ACQ_DT" IS 'Monthly Customer Info. Acquired Date';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_RK" IS 'Monthly Customer Info. Agent Rank';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."YM" IS 'Monthly Customer Info. Year & Month';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_REGION_CLS" IS 'Monthly Customer Info. Agent Region Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_REGION_CD" IS 'Monthly Customer Info. Agent Regsion Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SVC_STATUS_L_CLS" IS 'Monthly Customer Info. Service Status L Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SVC_STATUS_S_CLS" IS 'Monthly Customer Info. Service Status S Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."OLD_BILL_CD" IS 'Monthly Customer Info. Old Billing Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_TYPE" IS 'Monthly Customer Info. Agent Type';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_AGE" IS 'Monthly Customer Info. Agent Age';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_STUDENT_AGE" IS 'Monthly Customer Info. Student Age';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_GENDER_CLS" IS 'Monthly Customer Info. Agent Gender Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."FIRST_CHRG_START_DT" IS 'Monthly Customer Info. First Charge Date';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."JOIN_ACCEPT_SUPERVISOR_CD" IS 'Monthly Customer Info. Supervisor Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."JOIN_ACCEPT_SHOP_CD" IS 'Monthly Customer Info. Shop Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."JOIN_DELIVERY_SUPERVISOR_CD" IS 'Monthly Customer Info. Delivery Supervisor Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."JOIN_DELIVERY_SHOP_CD" IS 'Monthly Customer Info. Delivery Shop Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."AF_TRANS_SUBS_REGION_CLS" IS 'Monthly Customer Info. Agent Region Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."AF_TRANS_SUBS_REGION_CD" IS 'Monthly Customer Info. Agent Transaction Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."AF_TRANS_JOIN_ACCEPT_SV_CD" IS 'Monthly Customer Info Service Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."AF_TRANS_JOIN_ACCEPT_SHOP_CD" IS 'Monthly Customer Info. Transaction Shop Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LAST_UIM_MODEL_SALE_DT" IS 'Monthly Customer Info. UIM Model';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LAST_UIM_EQUIP_SYS_RK" IS 'Monthly Customer Info. UIM Equipment';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_UIM_MODEL_SALE_DT" IS 'Monthly Customer Info. Model Sales Date';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_UIM_EQUIP_SYS_RK" IS 'Monthly Customer Info. System Rank';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LAST_INSERT_DT" IS 'Monthly Customer Info. Insert Date';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LAST_INSERT_EQUIP_SYS_RK" IS 'Monthly Customer Info. Equipment Rank';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_INSERT_DT" IS 'Monthly Customer Info. Latest Insert Date';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_INSERT_EQUIP_SYS_RK" IS 'Monthly Customer Info. Equipment System';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_DIV_FLG" IS 'Monthly Customer Info. Division Flag';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."MVNO_CLS" IS 'Monthly Customer Info. MVNO Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."TARGET_STUDENT_AGE" IS 'Monthly Customer Info. Student Age';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."TARGET_AGE" IS 'Monthly Customer Info. Target Age';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."DEMO_CLS" IS 'Monthly Customer Info. Demo Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."PAY_GROUP" IS 'Monthly Customer Info. Payment Group';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."CUR_PRICE_PLAN_CD" IS 'Monthly Customer Info. Price Plan Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."CUR_DSC_OP4_CD" IS 'Monthly Customer Info. Operation Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."COLLABO_COMPANY_FLG" IS 'Monthly Customer Info. Collaboration Company Flag';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."USED_MODEL_CLS" IS 'Monthly Customer Info. Model Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."USE_MODEL_START_DT" IS 'Monthly Customer Info. Model Start Date';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SVC_CLS" IS 'Monthly Customer Info. Service Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."EZWEB_CLS" IS 'Monthly Customer Info. Web Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_GROUP_CD" IS 'Monthly Customer Info. Group Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_START_YM" IS 'Monthly Customer Info. Start Year & Month';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ABO_YM" IS 'Monthly Customer Info. ABO Year & Month';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_APPLY_FLG" IS 'Monthly Customer Info. Application Flag';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_APPLI_FLG" IS 'Monthly Customer Info. APplication Flag2';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ABO_REASON" IS 'Monthly Customer Info. ABO Reason';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ROUTER_DSC_CLS" IS 'Monthly Customer Info. Router Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ROUTER_DSC_START_DT" IS 'Monthly Customer Info. Router Start Date';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ROUTER_DSC_END_DT" IS 'Monthly Customer Info. Router End Date';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ROUTER_DSC_ABO_REASON" IS 'Monthly Customer Info. ABO Reason';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_APPLI_ACCEPT_DT" IS 'Monthly Customer Info. Acceptance Date';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ACCEPT_SUPERVISOR_CD" IS 'Monthly Customer Info. Supervisor Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ACCEPT_SHOP_CD" IS 'Monthly Customer Info. Acceptance Shop Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_AUTO_APPLY_FLG" IS 'Monthly Customer Info. Application Flag';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_LINK_CLS" IS 'Monthly Customer Info. Link Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_SP_DSC_APPLY_FLG" IS 'Monthly Customer Info. Application SP Flag';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_SP_DSC_START_DT" IS 'Monthly Customer Info. SP Start Date';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_SP_DSC_END_M" IS 'Monthly Customer Info. SP End Month';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_SP_DSC_END_PLAN_M" IS 'Monthly Customer Info. SP End Plan';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_SP_DSC_CLS_CD" IS 'Monthly Customer Info. Grade Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."NEW_PRICE_PLAN_CD" IS 'Monthly Customer Info. New Price Plan Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."NEW_DSC_OP4CD" IS 'Monthly Customer Info. Operation Code';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_USE_MODEL_EQUIP_RK" IS 'Monthly Customer Info. Model Equipment';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_USE_MODEL_EQUIP_SYS_RK" IS 'Monthly Customer Info. Point Single Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."PCKT_SINGLE_CLS" IS 'Monthly Customer Info. Single Grade';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."INTEGRATE_BILL_ACCOUNT" IS 'Monthly Customer Info. Billing Account';
   COMMENT ON TABLE "K_MONTH_CUST_INF"  IS 'Monthly Customer Info.';


  CREATE TABLE "K_MONTH_DELE_SUBS" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"SUBS_CLS" VARCHAR2(10 BYTE), 
	"DELE_SUBS_ID" VARCHAR2(10 BYTE), 
	"ACTIVE_DT" VARCHAR2(10 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."ACQ_DT" IS 'Acquired Date';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."YM" IS 'Year & Month';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."CUST_ID" IS 'Customer ID';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."SUBS_CLS" IS 'Agent Grade';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."DELE_SUBS_ID" IS 'Delete Agent ID';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."ACTIVE_DT" IS 'Activated Date';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."ACTIVE_TM" IS 'Activated Time';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."INVALID_DT" IS 'Invalid Date';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."INVALID_TM" IS 'Invalid Time';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."INVALID_FLG" IS 'Invalid Flag';
   COMMENT ON TABLE "K_MONTH_DELE_SUBS"  IS 'Monthly Delete Agent';


  CREATE TABLE "K_MONTH_SITE_CUST" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"CUST_CLS" VARCHAR2(10 BYTE), 
	"BIRTH_DT" VARCHAR2(10 BYTE), 
	"GENDER_CLS" VARCHAR2(10 BYTE), 
	"IDENTIFICATION_LEVEL" VARCHAR2(10 BYTE), 
	"IDENTIFICATION_DT" VARCHAR2(10 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"CUST_PWD_UPD_DT" VARCHAR2(10 BYTE), 
	"CUST_PWD_UPD_TM" VARCHAR2(10 BYTE), 
	"PWD_INITIAL_CHANGE_CLS" VARCHAR2(10 BYTE), 
	"CUST_MAIL1_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"CUST_MAIL2_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"EZ_MAIL_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"DELE_AU_SUBS_RK" VARCHAR2(10 BYTE), 
	"APPROVAL_TICKET_ID" VARCHAR2(10 BYTE), 
	"CUST_FIRST_REGIST_DT" VARCHAR2(10 BYTE), 
	"ACTIVE_DT" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."ACQ_DT" IS 'Acquired Date';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."YM" IS 'Year & Month';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_ID" IS 'Customer ID';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_CLS" IS 'Customer Grade';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."BIRTH_DT" IS 'Birthday';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."GENDER_CLS" IS 'Gender Grade';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."IDENTIFICATION_LEVEL" IS 'ID Level';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."IDENTIFICATION_DT" IS 'Identification Date';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."AU_ID" IS 'AU ID';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_PWD_UPD_DT" IS 'Password Update Date';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_PWD_UPD_TM" IS 'Password Update Time';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."PWD_INITIAL_CHANGE_CLS" IS 'Password Initial Change';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_MAIL1_NOTICE_FLG" IS 'Mail Noti Flag';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_MAIL2_NOTICE_FLG" IS 'Mail Noti Flag2';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."EZ_MAIL_NOTICE_FLG" IS 'Mail Noti Flag3';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."DELE_AU_SUBS_RK" IS 'Agent Rank';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."APPROVAL_TICKET_ID" IS 'Ticket ID';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_FIRST_REGIST_DT" IS 'First Registration Date';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."ACTIVE_DT" IS 'Activated Date';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."INVALID_DT" IS 'Invalid Date';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."INVALID_FLG" IS 'Invalid Flag';
   COMMENT ON TABLE "K_MONTH_SITE_CUST"  IS 'Monthly Customer Site';


  CREATE TABLE "K_MONTH_SITE_CUST_LINK" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"SUBS_CLS" VARCHAR2(10 BYTE), 
	"SUBS_ID" VARCHAR2(10 BYTE), 
	"LINK_DS" VARCHAR2(10 BYTE), 
	"ACTIVE_DT" VARCHAR2(10 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"SUBS_LINK_STATUS_CD" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."ACQ_DT" IS 'Acauired Date';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."YM" IS 'Year & Month';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."CUST_ID" IS 'Customer ID';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."SUBS_CLS" IS 'Agent Grade';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."SUBS_ID" IS 'Agent ID';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."LINK_DS" IS 'Link Description';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."ACTIVE_DT" IS 'Activated Date';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."ACTIVE_TM" IS 'Activated Time';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."INVALID_DT" IS 'Invalid Date';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."INVALID_TM" IS 'Invalid Time';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."SUBS_LINK_STATUS_CD" IS 'Link Status Code';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."INVALID_FLG" IS 'Invalid Flag';
   COMMENT ON TABLE "K_MONTH_SITE_CUST_LINK"  IS 'Monthly Site Link';


  CREATE TABLE "MONTH_0_KEY" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"CUR_CLOSE_FLG" VARCHAR2(10 BYTE), 
	"DELE_AU_SUBS_JOIN_FLG" VARCHAR2(10 BYTE), 
	"M" VARCHAR2(10 BYTE), 
	"MONTH_SUSPENSION_FLG" VARCHAR2(10 BYTE), 
	"MONTH_SVC_FLG" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"SUSPENSION_CLOSE_FLG" VARCHAR2(10 BYTE), 
	"Y" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_0_KEY"."ACQ_DT" IS 'Acquired Date';
   COMMENT ON COLUMN "MONTH_0_KEY"."AU_ID" IS 'AU ID';
   COMMENT ON COLUMN "MONTH_0_KEY"."CUR_CLOSE_FLG" IS 'Close Flag';
   COMMENT ON COLUMN "MONTH_0_KEY"."DELE_AU_SUBS_JOIN_FLG" IS 'Join Flag';
   COMMENT ON COLUMN "MONTH_0_KEY"."M" IS 'Month';
   COMMENT ON COLUMN "MONTH_0_KEY"."MONTH_SUSPENSION_FLG" IS 'Suspension Flag';
   COMMENT ON COLUMN "MONTH_0_KEY"."MONTH_SVC_FLG" IS 'Monthly Service Flag';
   COMMENT ON COLUMN "MONTH_0_KEY"."SUBS_RK" IS 'Agent Key';
   COMMENT ON COLUMN "MONTH_0_KEY"."SUBS_TYPE" IS 'Agent Type';
   COMMENT ON COLUMN "MONTH_0_KEY"."SUSPENSION_CLOSE_FLG" IS 'Suspension Close Flag';
   COMMENT ON COLUMN "MONTH_0_KEY"."Y" IS 'Year';
   COMMENT ON TABLE "MONTH_0_KEY"  IS 'Monthly Key';


  CREATE TABLE "MONTH_1_GENDER_AGE" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"M" VARCHAR2(10 BYTE), 
	"SUBS_AGE" VARCHAR2(10 BYTE), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"SUBS_STUDENT_AGE" VARCHAR2(10 BYTE), 
	"USER_AGE" VARCHAR2(10 BYTE), 
	"USER_STUDENT_AGE" VARCHAR2(10 BYTE), 
	"Y" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."ACQ_DT" IS 'Acquired Date';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."AU_ID" IS 'AU ID';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."M" IS 'Month';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."SUBS_AGE" IS 'Agent Age';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."SUBS_GENDER_CLS" IS 'Gender Grade';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."SUBS_STUDENT_AGE" IS 'Agent Student Age';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."USER_AGE" IS 'User Age';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."USER_STUDENT_AGE" IS 'User Student Age';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."Y" IS 'Year';
   COMMENT ON TABLE "MONTH_1_GENDER_AGE"  IS 'Age';


  CREATE TABLE "MONTH_2_HOUSE_AREA" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_PREF_CD" VARCHAR2(10 BYTE), 
	"M" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_PREF_CD" VARCHAR2(10 BYTE), 
	"Y" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."ACQ_DT" IS 'Acquired ID';
   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."AU_ID" IS 'AU ID';
   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."LATEST_DELIVERY_PREF_CD" IS 'Delivery Code';
   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."M" IS 'Month';
   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."NEW_JOIN_ACCEPT_PREF_CD" IS 'Acceptance Code';
   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."Y" IS 'House Area';
   COMMENT ON TABLE "MONTH_2_HOUSE_AREA"  IS 'Month2 House Area';


  CREATE TABLE "MONTH_32_MOBILE_USE_SITU" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"AU_HOME_DSC_REGIST_FLG" VARCHAR2(10 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"CLOSE_DT" VARCHAR2(10 BYTE), 
	"CLOSE_REASON" VARCHAR2(10 BYTE), 
	"CONTACT_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"FROM_COMPANY_CD" VARCHAR2(10 BYTE), 
	"JOIN_REGION_CLS" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_CHANNEL1" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_CHANNEL2" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_MVNO_CLS" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CHANNEL1" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CHANNEL2" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CITY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_MVNO_CLS" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"M" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CHANNEL1" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CHANNEL2" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CITY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_MVNO_CLS" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_REGIST_DT" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"PRIORITY_JOINER_FLG" VARCHAR2(10 BYTE), 
	"SVC_STATUS_GROUP_CLS" VARCHAR2(10 BYTE), 
	"TO_COMPANY_CD" VARCHAR2(10 BYTE), 
	"Y" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."ACQ_DT" IS 'Acquired Date';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."AU_HOME_DSC_REGIST_FLG" IS 'AU Home Registration Flag';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."AU_ID" IS 'AU ID';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."CLOSE_DT" IS 'Close Date';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."CLOSE_REASON" IS 'Close Reason';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."CONTACT_CLS" IS 'Contact Grade';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."FIRST_CHRG_START_DT" IS 'First Charge Start Date';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."FROM_COMPANY_CD" IS 'Company Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."JOIN_REGION_CLS" IS 'Join Region';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_ACCEPT_CHANNEL1" IS 'Channel1';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_ACCEPT_CHANNEL2" IS 'Channel2';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_ACCEPT_MVNO_CLS" IS 'MVNO Grade';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_ACCEPT_SHOP_CD" IS 'Acceptance Shop Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_ACCEPT_SV_AGENCY_CD" IS 'Service Agent Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_CHANNEL1" IS 'Latest Delivery Channel1';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_CHANNEL2" IS 'Latest Delivery Channel2';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_CITY_CD" IS 'Delivery City Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_MVNO_CLS" IS 'Delivery Grade';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_SHOP_CD" IS 'Delivery Shop Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_SV_AGENCY_CD" IS 'Service Agent Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."M" IS 'Month';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_CHANNEL1" IS 'Acceptance Channel1';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_CHANNEL2" IS 'Acceptance Channel2';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_CITY_CD" IS 'Acceptance City Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_MVNO_CLS" IS 'Acceptance MV Grade';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_SHOP_CD" IS 'Shop Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_SV_AGENCY_CD" IS 'Service Agent Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_DELIVERY_SHOP_CD" IS 'Delivery Shop Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_DELIVERY_SV_AGENCY_CD" IS 'Delivery Service Agent Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_PRICE_PLAN_CD" IS 'New Price Plan Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_PRICE_PLAN_REGIST_DT" IS 'New Price Plan Registration Date';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_PRICE_PLAN_START_DT" IS 'New Price Plan Start Date';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."PRIORITY_JOINER_FLG" IS 'Priority Joiner Flag';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."SVC_STATUS_GROUP_CLS" IS 'Service Status Group Grade';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."TO_COMPANY_CD" IS 'Company Code';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."Y" IS 'Year';
   COMMENT ON TABLE "MONTH_32_MOBILE_USE_SITU"  IS 'Monthly Mobile Usage';


  CREATE TABLE "MONTH_AU_CUST_AUID_MST" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"LINK_CLS" VARCHAR2(10 BYTE), 
	"DELE_AU_SUBS_JOIN_FLG" VARCHAR2(10 BYTE), 
	"PWD_INITIAL_CHANGE_CLS" VARCHAR2(10 BYTE), 
	"DELE_SUBS_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."ACQ_DT" IS 'Acquired Date';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."AU_ID" IS 'AU ID';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."CUST_ID" IS 'Customer ID';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."SUBS_RK" IS 'Agent Rank';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."LINK_CLS" IS 'Link Grade';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."DELE_AU_SUBS_JOIN_FLG" IS 'AU Agent Flag';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."PWD_INITIAL_CHANGE_CLS" IS 'Password Initial Change';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."DELE_SUBS_FLG" IS 'Agent Flag';
   COMMENT ON TABLE "MONTH_AU_CUST_AUID_MST"  IS 'AU ID Master';


  CREATE TABLE "MONTH_CUST_INF_BASE" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"JOIN_REGION_CLS" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"CONTACT_CLS" VARCHAR2(10 BYTE), 
	"SUBS_AGE" NUMBER(10,0), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_USE_PRD" NUMBER(10,0), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_REGIST_DT" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"SVC_STATUS_L_CLS" VARCHAR2(10 BYTE), 
	"SUSPENSION_DT" VARCHAR2(10 BYTE), 
	"CLOSE_DT" VARCHAR2(10 BYTE), 
	"CLOSE_REASON" VARCHAR2(10 BYTE), 
	"AU_HOME_DSC_REGIST_FLG" VARCHAR2(10 BYTE), 
	"PRIORITY_JOINER_FLG" VARCHAR2(10 BYTE), 
	"SUBS_STUDENT_AGE" NUMBER(10,0), 
	"FROM_COMPANY_CD" VARCHAR2(10 BYTE), 
	"TO_COMPANY_CD" VARCHAR2(10 BYTE), 
	"PERMISSION_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"USER_AGE" NUMBER(10,0), 
	"USER_STUDENT_AGE" NUMBER(10,0), 
	"SVC_STATUS_GROUP_CLS" VARCHAR2(10 BYTE), 
	"SUSPENSION_CLOSE_FLG" VARCHAR2(10 BYTE), 
	"SUBS_DEPART_FLG" VARCHAR2(10 BYTE), 
	"SIMPLE_USAGE_CLS" VARCHAR2(10 BYTE), 
	"SIMPLE_USAGE_PRD" NUMBER(10,0), 
	"SPT_SPC_USAGE_RENEWAL_PRD" NUMBER(10,0)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."ACQ_DT" IS 'Acquired Date';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."JOIN_REGION_CLS" IS 'Join Region Grade';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_RK" IS 'Agent Rank';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_TYPE" IS 'Agent Type';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CONTACT_CLS" IS 'Contact Grade';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_AGE" IS 'Agent Age';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_GENDER_CLS" IS 'Gender Grade';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CUR_PRICE_PLAN_CD" IS 'Price Plan Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CUR_PRICE_PLAN_START_DT" IS 'Price Pan Start Date';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CUR_PRICE_PLAN_USE_PRD" IS 'Price Plan Period';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."NEW_PRICE_PLAN_CD" IS 'New Price Plan Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."NEW_PRICE_PLAN_REGIST_DT" IS 'New Price Plan Registration Date';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."NEW_PRICE_PLAN_START_DT" IS 'New Price Plan Start Date';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SVC_STATUS_L_CLS" IS 'Service Status L Grade';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUSPENSION_DT" IS 'Suspension Date';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CLOSE_DT" IS 'Close Date';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CLOSE_REASON" IS 'Close Reason';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."AU_HOME_DSC_REGIST_FLG" IS 'AU Home Flag';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."PRIORITY_JOINER_FLG" IS 'Priority Flag';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_STUDENT_AGE" IS 'Agent Student Age';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."FROM_COMPANY_CD" IS 'Original Company';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."TO_COMPANY_CD" IS 'Target Company';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."PERMISSION_CLS" IS 'Permission Grade';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."FIRST_CHRG_START_DT" IS 'First Charge Start Date';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."USER_AGE" IS 'User Age';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."USER_STUDENT_AGE" IS 'User Student Age';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SVC_STATUS_GROUP_CLS" IS 'Service Status Group';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUSPENSION_CLOSE_FLG" IS 'Suspension Close Flag';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_DEPART_FLG" IS 'Agent Department Flag';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SIMPLE_USAGE_CLS" IS 'Simple Usage Grade';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SIMPLE_USAGE_PRD" IS 'Simple Usage Product';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SPT_SPC_USAGE_RENEWAL_PRD" IS 'Renewal Product';
   COMMENT ON TABLE "MONTH_CUST_INF_BASE"  IS 'Base Customer Info';


  CREATE TABLE "MONTH_CUST_INF_SHOP" 
   (	"ACQ_DT" VARCHAR2(200 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CHANNEL1" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CHANNEL2" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_MVNO_CLS" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_PREF_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CITY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_CHANNEL1" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_CHANNEL2" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_MVNO_CLS" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_PREF_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_CITY_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_CHANNEL1" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_CHANNEL2" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_MVNO_CLS" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_PREF_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_CITY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CHANNEL1" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CHANNEL2" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_MVNO_CLS" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_PREF_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CITY_CD" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."ACQ_DT" IS 'Acquired Date';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."SUBS_RK" IS 'Aget RanK';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_SV_AGENCY_CD" IS 'New Acceptance Service Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_SHOP_CD" IS 'New Join Shop Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_CHANNEL1" IS 'New Join Acceptance Channel1';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_CHANNEL2" IS 'New Join Acceptance Channel2';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_MVNO_CLS" IS 'New Join Acceptance MVNO Grade';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_PREF_CD" IS 'New Join Preference Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_CITY_CD" IS 'New Join City Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_SV_AGENCY_CD" IS 'New Join Delivery Service Agent Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_SHOP_CD" IS 'New Join Delivery Shop Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_CHANNEL1" IS 'New Join Delivery Channel1';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_CHANNEL2" IS 'New Join Delivery Channel2';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_MVNO_CLS" IS 'New Join Delivery MVNO Grade';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_PREF_CD" IS 'New Join Delivery Preference Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_CITY_CD" IS 'New Join Delivery City Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_SV_AGENCY_CD" IS 'Latest Acceptance Service Agent Code' ;
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_SHOP_CD" IS 'Latest Acceptance Shop Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_CHANNEL1" IS 'Latest Acceptance Channel1';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_CHANNEL2" IS 'Latest Acceptance Channel2';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_MVNO_CLS" IS 'Latest Acceptance MVNO Grade';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_PREF_CD" IS 'Latest Acceptance Preference Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_CITY_CD" IS 'Latest Acceptance City Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_SV_AGENCY_CD" IS 'Latest Delivery Service Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_SHOP_CD" IS 'Latest Delivery Shop Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_CHANNEL1" IS 'Latest Delivery Channel1';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_CHANNEL2" IS 'Latest Delivery Channel2';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_MVNO_CLS" IS 'Latest Delivery MVNO Grade';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_PREF_CD" IS 'Latest Delivery Preference Code';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_CITY_CD" IS 'Latest Delivery City Code';
   COMMENT ON TABLE "MONTH_CUST_INF_SHOP"  IS 'Monthly Shop';


  CREATE TABLE "MONTH_SHOP_MST" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"SHOP_CD" VARCHAR2(10 BYTE), 
	"SHOP_NAME" VARCHAR2(10 BYTE), 
	"SHOP_SHORT_NAME" VARCHAR2(10 BYTE), 
	"REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_NAME" VARCHAR2(10 BYTE), 
	"SHOP_HANDLE_CD" VARCHAR2(10 BYTE), 
	"SHOP_POSTAL_CD" VARCHAR2(10 BYTE), 
	"SHOP_PREF_CD" VARCHAR2(10 BYTE), 
	"SHOP_CITY_CD" VARCHAR2(10 BYTE), 
	"SHOP_CLS" VARCHAR2(10 BYTE), 
	"INSTAL_SALE_CLS" VARCHAR2(10 BYTE), 
	"AU_AGENCY_CLS" VARCHAR2(10 BYTE), 
	"MVNO_CLS" VARCHAR2(10 BYTE), 
	"GROUP_CD_SV" VARCHAR2(10 BYTE), 
	"GROUP_CD_SHOP" VARCHAR2(10 BYTE), 
	"GROUP_CLS" VARCHAR2(10 BYTE), 
	"DIST_AF_SHOP" VARCHAR2(10 BYTE), 
	"MONOPOLY_CLS" VARCHAR2(10 BYTE), 
	"SALES_CHANNEL1" VARCHAR2(10 BYTE), 
	"SALES_CHANNEL2" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_SHOP_MST"."ACQ_DT" IS 'Acquired ID';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SUPERVISOR_CD" IS 'Supervisor Code';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_CD" IS 'Shop Code';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_NAME" IS 'Shop Name';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_SHORT_NAME" IS 'Shop Short Name';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."REGION_CD" IS 'Region Code';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_REGION_CD" IS 'Shop Region Code';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_REGION_NAME" IS 'Shop Region Name';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_HANDLE_CD" IS 'Shop Handle Code';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_POSTAL_CD" IS 'Shop Postal Code';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_PREF_CD" IS 'Shop Preference Code';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_CITY_CD" IS 'Shop City Code';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_CLS" IS 'Shop Grade';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."INSTAL_SALE_CLS" IS 'Sales Grade';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."AU_AGENCY_CLS" IS 'AU Agent Grade';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."MVNO_CLS" IS 'MVNO Grade';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."GROUP_CD_SV" IS 'Service Group Code';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."GROUP_CD_SHOP" IS 'Shop Group Code';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."GROUP_CLS" IS 'Group Grade';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."DIST_AF_SHOP" IS 'AF Shop';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."MONOPOLY_CLS" IS 'Mono Grade';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SALES_CHANNEL1" IS 'Sales Channel1';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SALES_CHANNEL2" IS 'Sales Channel2';
   COMMENT ON TABLE "MONTH_SHOP_MST"  IS 'Monthly Shop Master';


  CREATE TABLE "REDSHIFT_MST" 
   (	"AU_ID" VARCHAR2(320 BYTE), 
	"SUBS_RK" VARCHAR2(32 BYTE), 
	"ITEM_SUBS_ID" VARCHAR2(40 BYTE), 
	"JOIN_DT" DATE, 
	"JOIN_TM" VARCHAR2(8 BYTE), 
	"CLOSE_DT" DATE, 
	"CLOSE_TM" VARCHAR2(8 BYTE), 
	"FIRST_ACTIVATION_DT" DATE, 
	"FIRST_ACTIVATION_DT_I" DATE, 
	"FREE_TRIAL_FLG" VARCHAR2(4 BYTE), 
	"TICKET_FLG" VARCHAR2(4 BYTE), 
	"AUTO_CLOSE_FLG" VARCHAR2(4 BYTE), 
	"Z_FLG" VARCHAR2(4 BYTE), 
	"SUBS_TYPE" VARCHAR2(4 BYTE), 
	"CS_RESULT_FLG" VARCHAR2(4 BYTE), 
	"JOIN_ROUTE" VARCHAR2(4 BYTE), 
	"JOIN_CLS" VARCHAR2(8 BYTE), 
	"JOIN_REGION_CLS" VARCHAR2(4 BYTE), 
	"JOIN_OS_CLS" VARCHAR2(4 BYTE), 
	"JOIN_DV_CLS" VARCHAR2(4 BYTE), 
	"JOIN_EQUIP_RK" VARCHAR2(12 BYTE), 
	"CLOSE_OS_CLS" VARCHAR2(4 BYTE), 
	"CLOSE_DV_CLS" VARCHAR2(4 BYTE), 
	"CLOSE_EQUIP_RK" VARCHAR2(12 BYTE), 
	"CHARGE_OS_CLS" VARCHAR2(4 BYTE), 
	"CHARGE_DV_CLS" VARCHAR2(4 BYTE), 
	"CHARGE_EQUIP_RK" VARCHAR2(12 BYTE), 
	"NOW_OS_CLS" VARCHAR2(4 BYTE), 
	"NOW_DV_CLS" VARCHAR2(4 BYTE), 
	"NOW_EQUIP_RK" VARCHAR2(12 BYTE), 
	"SFA_DATE" DATE, 
	"SIN_FLG" VARCHAR2(4 BYTE), 
	"SFA_APPLICATION_NO" VARCHAR2(36 BYTE), 
	"SFA_SHOP_CD" VARCHAR2(12 BYTE), 
	"SFA_SUPERVISOR_CD" VARCHAR2(16 BYTE), 
	"APPLICATION_NO" VARCHAR2(36 BYTE), 
	"SHOP_CD" VARCHAR2(12 BYTE), 
	"SUPERVISOR_CD" VARCHAR2(16 BYTE), 
	"FT_RETIRE_FLG" VARCHAR2(4 BYTE), 
	"JOIN_CNT" NUMBER(24,0), 
	"PAST_JOIN_FLG" VARCHAR2(4 BYTE), 
	"JOIN_FLG" VARCHAR2(4 BYTE), 
	"SUPERVISOR_SYSTEM_ID" VARCHAR2(24 BYTE), 
	"REGION_NM13" VARCHAR2(40 BYTE), 
	"SHOP_BRANCH_CD" VARCHAR2(12 BYTE), 
	"SHOP_BRANCH_NM" VARCHAR2(80 BYTE), 
	"AGENCY_CD" VARCHAR2(16 BYTE), 
	"AGENCY_NM" VARCHAR2(200 BYTE), 
	"SUPERVISOR_NM" VARCHAR2(200 BYTE), 
	"SHOP_NM" VARCHAR2(200 BYTE), 
	"CHANNEL_NM" VARCHAR2(48 BYTE), 
	"SUBS_STATUS_CLS" VARCHAR2(4 BYTE), 
	"STUDENT_AGE" NUMBER(24,0), 
	"AGE_RNG" VARCHAR2(32 BYTE), 
	"GENDER_CLS" VARCHAR2(40 BYTE), 
	"AU_FIRST_ACTIVATION_DT" DATE, 
	"EQUIP_SYS_RK" VARCHAR2(12 BYTE), 
	"EQUIP_MODEL_CD" VARCHAR2(80 BYTE), 
	"SMART_PHONE_FLG" VARCHAR2(4 BYTE), 
	"EQUIP_TYPE" VARCHAR2(24 BYTE), 
	"OS_CLS" VARCHAR2(28 BYTE), 
	"PAYMENT_CLS" VARCHAR2(4 BYTE), 
	"CUR_PRICE_PLAN_RK" VARCHAR2(16 BYTE), 
	"ENTRY_COUNTY_NM" VARCHAR2(32 BYTE), 
	"ENTRY_POSTAL_CD" VARCHAR2(32 BYTE), 
	"JOIN_DV_IDDISCRDIV" VARCHAR2(4 BYTE), 
	"NOW_DV_IDDISCRDIV" VARCHAR2(4 BYTE), 
	"CLOSE_DV_IDDISCRDIV" VARCHAR2(4 BYTE)
   )
   ;

   COMMENT ON COLUMN "REDSHIFT_MST"."AU_ID" IS 'AU ID';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUBS_RK" IS 'Agent Rank';
   COMMENT ON COLUMN "REDSHIFT_MST"."ITEM_SUBS_ID" IS 'Item Agent ID';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_DT" IS 'Join Date';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_TM" IS 'Join Time';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_DT" IS 'Close Date';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_TM" IS 'Close Time';
   COMMENT ON COLUMN "REDSHIFT_MST"."FIRST_ACTIVATION_DT" IS 'First Activation Date';
   COMMENT ON COLUMN "REDSHIFT_MST"."FIRST_ACTIVATION_DT_I" IS 'First Activation date2';
   COMMENT ON COLUMN "REDSHIFT_MST"."FREE_TRIAL_FLG" IS 'Free Trial Flag';
   COMMENT ON COLUMN "REDSHIFT_MST"."TICKET_FLG" IS 'Ticket Flag';
   COMMENT ON COLUMN "REDSHIFT_MST"."AUTO_CLOSE_FLG" IS 'Auto Close Flag';
   COMMENT ON COLUMN "REDSHIFT_MST"."Z_FLG" IS 'Z Flag';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUBS_TYPE" IS 'Agent Type';
   COMMENT ON COLUMN "REDSHIFT_MST"."CS_RESULT_FLG" IS 'Customer Support Result';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_ROUTE" IS 'Join Router';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_CLS" IS 'Join Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_REGION_CLS" IS 'Join Region Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_OS_CLS" IS 'Join OS Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_DV_CLS" IS 'Join DV Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_EQUIP_RK" IS 'Join Equipment Rank';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_OS_CLS" IS 'Close OS Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_DV_CLS" IS 'Close DV Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_EQUIP_RK" IS 'Close Equipment Rank';
   COMMENT ON COLUMN "REDSHIFT_MST"."CHARGE_OS_CLS" IS 'Charge OS Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."CHARGE_DV_CLS" IS 'Charge DV Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."CHARGE_EQUIP_RK" IS 'Charge Equipment Rank';
   COMMENT ON COLUMN "REDSHIFT_MST"."NOW_OS_CLS" IS 'Current OS Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."NOW_DV_CLS" IS 'Current DV Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."NOW_EQUIP_RK" IS 'Current Equipment Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."SFA_DATE" IS 'SFA Date';
   COMMENT ON COLUMN "REDSHIFT_MST"."SIN_FLG" IS 'Sign Flag';
   COMMENT ON COLUMN "REDSHIFT_MST"."SFA_APPLICATION_NO" IS 'SFA Application Number';
   COMMENT ON COLUMN "REDSHIFT_MST"."SFA_SHOP_CD" IS 'SFA Shop Code';
   COMMENT ON COLUMN "REDSHIFT_MST"."SFA_SUPERVISOR_CD" IS 'SFA Supervisor Code';
   COMMENT ON COLUMN "REDSHIFT_MST"."APPLICATION_NO" IS 'Application Number';
   COMMENT ON COLUMN "REDSHIFT_MST"."SHOP_CD" IS 'Shop Code';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUPERVISOR_CD" IS 'Supervisor Code';
   COMMENT ON COLUMN "REDSHIFT_MST"."FT_RETIRE_FLG" IS 'Tuture Retirement Flag';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_CNT" IS 'Join Count';
   COMMENT ON COLUMN "REDSHIFT_MST"."PAST_JOIN_FLG" IS 'Past Join Flag';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_FLG" IS 'Join Flag';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUPERVISOR_SYSTEM_ID" IS 'Supervisor System ID';
   COMMENT ON COLUMN "REDSHIFT_MST"."REGION_NM13" IS 'Regon Name13';
   COMMENT ON COLUMN "REDSHIFT_MST"."SHOP_BRANCH_CD" IS 'Shop Branch Code';
   COMMENT ON COLUMN "REDSHIFT_MST"."SHOP_BRANCH_NM" IS 'Shop Branch Name';
   COMMENT ON COLUMN "REDSHIFT_MST"."AGENCY_CD" IS 'Agency Code';
   COMMENT ON COLUMN "REDSHIFT_MST"."AGENCY_NM" IS 'Agency Name';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUPERVISOR_NM" IS 'Supervisor Name';
   COMMENT ON COLUMN "REDSHIFT_MST"."SHOP_NM" IS 'Shop Name';
   COMMENT ON COLUMN "REDSHIFT_MST"."CHANNEL_NM" IS 'Channel Name';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUBS_STATUS_CLS" IS 'Agent Status Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."STUDENT_AGE" IS 'Student Age';
   COMMENT ON COLUMN "REDSHIFT_MST"."AGE_RNG" IS 'Agent Registration';
   COMMENT ON COLUMN "REDSHIFT_MST"."GENDER_CLS" IS 'Gender Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."AU_FIRST_ACTIVATION_DT" IS 'AU First Activation Date';
   COMMENT ON COLUMN "REDSHIFT_MST"."EQUIP_SYS_RK" IS 'Equipment System Rank';
   COMMENT ON COLUMN "REDSHIFT_MST"."EQUIP_MODEL_CD" IS 'Equipment Model Code';
   COMMENT ON COLUMN "REDSHIFT_MST"."SMART_PHONE_FLG" IS 'Smart Phone Flag';
   COMMENT ON COLUMN "REDSHIFT_MST"."EQUIP_TYPE" IS 'Equipment Type';
   COMMENT ON COLUMN "REDSHIFT_MST"."OS_CLS" IS 'OS Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."PAYMENT_CLS" IS 'Payment Grade';
   COMMENT ON COLUMN "REDSHIFT_MST"."CUR_PRICE_PLAN_RK" IS 'Current Price Plan Rank';
   COMMENT ON COLUMN "REDSHIFT_MST"."ENTRY_COUNTY_NM" IS 'Entry Count Name';
   COMMENT ON COLUMN "REDSHIFT_MST"."ENTRY_POSTAL_CD" IS 'Entry Postal Code';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_DV_IDDISCRDIV" IS 'Join Delivery ID';
   COMMENT ON COLUMN "REDSHIFT_MST"."NOW_DV_IDDISCRDIV" IS 'Current Delivery Service';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_DV_IDDISCRDIV" IS 'Close Delivery Service';
   COMMENT ON TABLE "REDSHIFT_MST"  IS 'REDSHIFT Master';


  CREATE TABLE "T_MONTH_CUST_INF" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"JOIN_REGION_CLS" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"BILL_CD" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"AU_TEL_NO_H" VARCHAR2(10 BYTE), 
	"SUBS_POSTAL_CD" VARCHAR2(10 BYTE), 
	"SUBS_PREF_CD" VARCHAR2(10 BYTE), 
	"JOIN_CITY_CD" VARCHAR2(10 BYTE), 
	"CONTACT_CLS" VARCHAR2(10 BYTE), 
	"SUBS_AGE" NUMBER(10,0), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"TARGET_BIRTH_DT" VARCHAR2(10 BYTE), 
	"TAX_FREE_CLS" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_USE_PRD" NUMBER(10,0), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_REGIST_DT" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LUMP_CLS" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(10 BYTE), 
	"SERIAL_NO" VARCHAR2(10 BYTE), 
	"EQUIP_RK" VARCHAR2(10 BYTE), 
	"USE_MODEL_START_DT" VARCHAR2(10 BYTE), 
	"USE_MODEL_USE_PERIOD" NUMBER(10,0), 
	"ANSIN_APPLY_CLS" VARCHAR2(10 BYTE), 
	"CHRG_START_DT" VARCHAR2(10 BYTE), 
	"COUNTING_START_DT" VARCHAR2(10 BYTE), 
	"SVC_STATUS_L_CLS" VARCHAR2(10 BYTE), 
	"SVC_STATUS_S_CLS" VARCHAR2(10 BYTE), 
	"SUSPENSION_DT" VARCHAR2(10 BYTE), 
	"RE_USE_DT" VARCHAR2(10 BYTE), 
	"SUBS_TRANS_DT" VARCHAR2(10 BYTE), 
	"SUBS_REOPEN_DT" VARCHAR2(10 BYTE), 
	"CLOSE_DT" VARCHAR2(10 BYTE), 
	"CLOSE_REASON" VARCHAR2(10 BYTE), 
	"OPERATION_DAYS" NUMBER(10,0), 
	"USE_PRD_TOTAL" NUMBER(10,0), 
	"MODEL_CHANGE_FLG" VARCHAR2(10 BYTE), 
	"SVC_CLS" VARCHAR2(10 BYTE), 
	"CALL_WIDE_FLG" VARCHAR2(10 BYTE), 
	"GROUP_DSC_FLG" VARCHAR2(10 BYTE), 
	"TYAKU_BUSI_FLG" VARCHAR2(10 BYTE), 
	"MULTI_Y_DSC_CLS" VARCHAR2(10 BYTE), 
	"WIN_MULTI_CABLE_DSC_FLG" VARCHAR2(10 BYTE), 
	"AU_HOME_DSC_REGIST_FLG" VARCHAR2(10 BYTE), 
	"PRIORITY_JOINER_FLG" VARCHAR2(10 BYTE), 
	"PRICE_CALL_STOP_TOTAL_CNT" NUMBER(10,0), 
	"TEMP_STOP" NUMBER(10,0), 
	"MODEL_CHANGE_CNT" NUMBER(10,0), 
	"MODEL_TROUBLE_CNT" NUMBER(10,0), 
	"TROUBLE_CNT_TOTAL" NUMBER(10,0), 
	"USED_MODEL_CLS" VARCHAR2(10 BYTE), 
	"WIDE_SPT_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SUBS_STUDENT_AGE" NUMBER(10,0), 
	"MARU_BUSI_DSC_FLG" VARCHAR2(10 BYTE), 
	"OTHER_COMPANY_JOIN_CLS" VARCHAR2(10 BYTE), 
	"FROM_COMPANY_CD" VARCHAR2(10 BYTE), 
	"TO_COMPANY_CD" VARCHAR2(10 BYTE), 
	"G_CALL_DSC_CLS" VARCHAR2(10 BYTE), 
	"PERMISSION_CLS" VARCHAR2(10 BYTE), 
	"HITORI_FLG" VARCHAR2(10 BYTE), 
	"MARU_BUSI_CO_CLS" VARCHAR2(10 BYTE), 
	"SHOP_PURCHASE_METHOD" VARCHAR2(10 BYTE), 
	"RESULT_TRANS_DT" VARCHAR2(10 BYTE), 
	"BF_TRANS_RESULT_CLS" VARCHAR2(10 BYTE), 
	"AF_TRANS_RESULT_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"COLLABO_COMPANY_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "T_MONTH_CUST_INF"."ACQ_DT" IS 'Acquired Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."YM" IS 'Year & Month';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."JOIN_REGION_CLS" IS 'Join Region Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_RK" IS 'Agent Rank';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."BILL_CD" IS 'Billing Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_TYPE" IS 'Agent Type';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."AU_TEL_NO_H" IS 'AU Telephone Number';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_POSTAL_CD" IS 'Agent Postal Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_PREF_CD" IS 'Agent Preference Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."JOIN_CITY_CD" IS 'Join City Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CONTACT_CLS" IS 'Contact Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_AGE" IS 'Agent Age';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_GENDER_CLS" IS 'Gender Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TARGET_BIRTH_DT" IS 'Birthday';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TAX_FREE_CLS" IS 'Tax Free Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CUR_PRICE_PLAN_CD" IS 'Price Plan Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CUR_PRICE_PLAN_START_DT" IS 'Price Plan Start Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CUR_PRICE_PLAN_USE_PRD" IS 'Price Plan Use Perioed';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_PRICE_PLAN_CD" IS 'New Price Plan Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_PRICE_PLAN_REGIST_DT" IS 'New Price Plan Registration Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_PRICE_PLAN_START_DT" IS 'New Price Plan Start Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_JOIN_ACCEPT_SV_AGENCY_CD" IS 'New Join Acceptance Service Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_JOIN_ACCEPT_SHOP_CD" IS 'New Join Acceptance Shop Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_JOIN_DELIVERY_SV_AGENCY_CD" IS 'New Join Delivery Service Agent Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_JOIN_DELIVERY_SHOP_CD" IS 'Now Join Delivery Shop Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."LATEST_ACCEPT_SV_AGENCY_CD" IS 'Latest Acceptance Service Agent Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."LATEST_ACCEPT_SHOP_CD" IS 'Latest Acceptance Shop Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."LATEST_DELIVERY_SV_AGENCY_CD" IS 'Latest Delivery Service Agent Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."LATEST_DELIVERY_SHOP_CD" IS 'Latest Delivery Shop Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."LUMP_CLS" IS 'Lump Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TYPE" IS 'Type';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SERIAL_NO" IS 'Serial No';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."EQUIP_RK" IS 'Equipment Rank';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."USE_MODEL_START_DT" IS 'Model Start Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."USE_MODEL_USE_PERIOD" IS 'Model Usage Period';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."ANSIN_APPLY_CLS" IS 'Application Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CHRG_START_DT" IS 'Charge Start Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."COUNTING_START_DT" IS 'Counting Start Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SVC_STATUS_L_CLS" IS 'Service Status L Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SVC_STATUS_S_CLS" IS 'Service Status S Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUSPENSION_DT" IS 'Suspension Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."RE_USE_DT" IS 'Reuse Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_TRANS_DT" IS 'Transaction Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_REOPEN_DT" IS 'Reopen Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CLOSE_DT" IS 'Close Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CLOSE_REASON" IS 'Close Reason';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."OPERATION_DAYS" IS 'Operation Days';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."USE_PRD_TOTAL" IS 'Total Period';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MODEL_CHANGE_FLG" IS 'Model Change Flag';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SVC_CLS" IS 'Service Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CALL_WIDE_FLG" IS 'Call Wide Flag';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."GROUP_DSC_FLG" IS 'Group Flag';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TYAKU_BUSI_FLG" IS 'Business Flag';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MULTI_Y_DSC_CLS" IS 'Multi Description';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."WIN_MULTI_CABLE_DSC_FLG" IS 'Multi Cable Flag';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."AU_HOME_DSC_REGIST_FLG" IS 'Home Flag';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."PRIORITY_JOINER_FLG" IS 'Priority Join Flag';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."PRICE_CALL_STOP_TOTAL_CNT" IS 'Total Count of Call Stop';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TEMP_STOP" IS 'Temporary Stop';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MODEL_CHANGE_CNT" IS 'Model Change Count';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MODEL_TROUBLE_CNT" IS 'Model Trouble Count';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TROUBLE_CNT_TOTAL" IS 'Total Trouble Count';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."USED_MODEL_CLS" IS 'Used Model Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."WIDE_SPT_APPLY_FLG" IS 'Wide Application Flag';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_STUDENT_AGE" IS 'Student Age';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MARU_BUSI_DSC_FLG" IS 'Business Flag';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."OTHER_COMPANY_JOIN_CLS" IS 'Other Company Join Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."FROM_COMPANY_CD" IS 'Original Company Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TO_COMPANY_CD" IS 'Target Company Code';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."G_CALL_DSC_CLS" IS 'Call Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."PERMISSION_CLS" IS 'Permission Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."HITORI_FLG" IS 'History Flag';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MARU_BUSI_CO_CLS" IS 'Business Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SHOP_PURCHASE_METHOD" IS 'Purchase Method';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."RESULT_TRANS_DT" IS 'Transaction Result';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."BF_TRANS_RESULT_CLS" IS 'Transaction Result Grade';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."AF_TRANS_RESULT_CLS" IS 'AF Transaction Result';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."FIRST_CHRG_START_DT" IS 'First Charge Start Date';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."COLLABO_COMPANY_FLG" IS 'Collaboration Company Flag';
   COMMENT ON TABLE "T_MONTH_CUST_INF"  IS 'Monthly Customer Information - T';


  CREATE TABLE "T_MONTH_SHOP_MST" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"SHOP_CD" VARCHAR2(10 BYTE), 
	"SHOP_NAME" VARCHAR2(10 BYTE), 
	"SHOP_SHORT_NAME" VARCHAR2(10 BYTE), 
	"REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_NAME" VARCHAR2(10 BYTE), 
	"SHOP_HANDLE_CD" VARCHAR2(10 BYTE), 
	"SHOP_POSTAL_CD" VARCHAR2(10 BYTE), 
	"SHOP_PREF_CD" VARCHAR2(10 BYTE), 
	"SHOP_CITY_CD" VARCHAR2(10 BYTE), 
	"SHOP_CLS" VARCHAR2(10 BYTE), 
	"INSTAL_SALE_CLS" VARCHAR2(10 BYTE), 
	"AU_AGENCY_CLS" VARCHAR2(10 BYTE), 
	"MVNO_CLS" VARCHAR2(10 BYTE), 
	"GROUP_CD_SV" VARCHAR2(10 BYTE), 
	"GROUP_CD_SHOP" VARCHAR2(10 BYTE), 
	"GROUP_CLS" VARCHAR2(10 BYTE), 
	"DIST_AF_SHOP" VARCHAR2(10 BYTE), 
	"MONOPOLY_CLS" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."ACQ_DT" IS 'AC date';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SUPERVISOR_CD" IS 'Supervisor Code';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_CD" IS 'Shop Code';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_NAME" IS 'Shop Name';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_SHORT_NAME" IS 'Shop Short Name';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."REGION_CD" IS 'Region Code';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_REGION_CD" IS 'Shop Region Code';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_REGION_NAME" IS 'Shop Region Name';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_HANDLE_CD" IS 'Shop Handle Code';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_POSTAL_CD" IS 'Shop Postal Code';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_PREF_CD" IS 'Shop Preference Code';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_CITY_CD" IS 'Shop City COde';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_CLS" IS 'Shop Grade';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."INSTAL_SALE_CLS" IS 'Sales Grade';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."AU_AGENCY_CLS" IS 'AU Agent Grade';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."MVNO_CLS" IS 'Grade';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."GROUP_CD_SV" IS 'Service Group Code';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."GROUP_CD_SHOP" IS 'Shop Group Code';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."GROUP_CLS" IS 'Group Grade';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."DIST_AF_SHOP" IS 'AF Shop';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."MONOPOLY_CLS" IS 'Mono Grade';
   COMMENT ON TABLE "T_MONTH_SHOP_MST"  IS 'Monthly Shop Master';


CREATE TABLE TBL1 (
  COL1 NUMBER(22) DEFAULT 1
,
  COL2 NUMBER(22),
  COL3 NUMBER(22)
);

CREATE TABLE TBL2 (
  COL1 NUMBER(22),
  COL2 NUMBER(22),
  COL3 NUMBER(22)
);