
  CREATE TABLE "IFTMS3001" 
   (	"YM" VARCHAR2(100 BYTE), 
	"JOIN_REGION_CLS" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"BILL_CD" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"AU_TEL_NO_H" VARCHAR2(10 BYTE), 
	"SUBS_POSTAL_CD" VARCHAR2(10 BYTE), 
	"SUBS_PREF_CD" VARCHAR2(10 BYTE), 
	"SUBS_CITY_CD" VARCHAR2(10 BYTE), 
	"CONTACT_CLS" VARCHAR2(10 BYTE), 
	"SUBS_AGE" NUMBER(10,0), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"TARGET_BIRTH_DT" VARCHAR2(10 BYTE), 
	"TAX_FREE_CLS" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_USE_PRD" NUMBER(10,0), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_REGIST_DT" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LUMP_CLS" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(10 BYTE), 
	"SERIAL_NO" VARCHAR2(10 BYTE), 
	"EQUIP_RK" VARCHAR2(10 BYTE), 
	"USE_MODEL_START_DT" VARCHAR2(10 BYTE), 
	"USE_MODEL_USE_PERIOD" NUMBER(10,0), 
	"CHRG_START_DT" VARCHAR2(10 BYTE), 
	"COUNTING_START_DT" VARCHAR2(10 BYTE), 
	"SVC_STATUS_L_CLS" VARCHAR2(10 BYTE), 
	"SVC_STATUS_S_CLS" VARCHAR2(10 BYTE), 
	"SUSPENSION_DT" VARCHAR2(10 BYTE), 
	"RE_USE_DT" VARCHAR2(10 BYTE), 
	"SUBS_TRANS_DT" VARCHAR2(10 BYTE), 
	"SUBS_REOPEN_DT" VARCHAR2(10 BYTE), 
	"CLOSE_DT" VARCHAR2(10 BYTE), 
	"CLOSE_REASON" VARCHAR2(10 BYTE), 
	"OPERATION_DAYS" NUMBER(10,0), 
	"USE_PRD_TOTAL" NUMBER(10,0), 
	"SVC_CLS" VARCHAR2(10 BYTE), 
	"CALL_WIDE_FLG" VARCHAR2(10 BYTE), 
	"GROUP_DSC_FLG" VARCHAR2(10 BYTE), 
	"MULTI_Y_DSC_CLS" VARCHAR2(10 BYTE), 
	"WIN_MULTI_CABLE_DSC_FLG" VARCHAR2(10 BYTE), 
	"AU_HOME_DSC_REGIST_FLG" VARCHAR2(10 BYTE), 
	"PRIORITY_JOINER_FLG" VARCHAR2(10 BYTE), 
	"PRICE_CALL_STOP_TOTAL_CNT" NUMBER(10,0), 
	"TEMP_STOP" NUMBER(10,0), 
	"MODEL_CHANGE_CNT" NUMBER(10,0), 
	"MODEL_TROUBLE_CNT" NUMBER(10,0), 
	"TROUBLE_CNT_TOTAL" NUMBER(10,0), 
	"USED_MODEL_CLS" VARCHAR2(10 BYTE), 
	"WIDE_SPT_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SUBS_STUDENT_AGE" NUMBER(10,0), 
	"MARU_BUSI_DSC_FLG" VARCHAR2(10 BYTE), 
	"OTHER_COMPANY_JOIN_CLS" VARCHAR2(10 BYTE), 
	"FROM_COMPANY_CD" VARCHAR2(10 BYTE), 
	"TO_COMPANY_CD" VARCHAR2(10 BYTE), 
	"G_CALL_DSC_CLS" VARCHAR2(10 BYTE), 
	"PERMISSION_CLS" VARCHAR2(10 BYTE), 
	"HITORI_FLG" VARCHAR2(10 BYTE), 
	"MARU_BUSI_CO_CLS" VARCHAR2(10 BYTE), 
	"SHOP_PURCHASE_METHOD" VARCHAR2(10 BYTE), 
	"RESULT_TRANS_DT" VARCHAR2(10 BYTE), 
	"BF_TRANS_RESULT_CLS" VARCHAR2(10 BYTE), 
	"AF_TRANS_RESULT_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"COLLABO_COMPANY_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3001"."YM" IS '연월';
   COMMENT ON COLUMN "IFTMS3001"."JOIN_REGION_CLS" IS '가입지역등급';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_RK" IS '대리자RK';
   COMMENT ON COLUMN "IFTMS3001"."BILL_CD" IS '청구코드';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_TYPE" IS '대리자유형';
   COMMENT ON COLUMN "IFTMS3001"."AU_TEL_NO_H" IS 'AU자택전화번호';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_POSTAL_CD" IS '대리자우편코드';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_PREF_CD" IS '대리자선호코드';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_CITY_CD" IS '대리자도시코드';
   COMMENT ON COLUMN "IFTMS3001"."CONTACT_CLS" IS '연락등급';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_AGE" IS '대리자연령';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_GENDER_CLS" IS '대리자성별';
   COMMENT ON COLUMN "IFTMS3001"."TARGET_BIRTH_DT" IS '타겟일자';
   COMMENT ON COLUMN "IFTMS3001"."TAX_FREE_CLS" IS '세금혜택등급';
   COMMENT ON COLUMN "IFTMS3001"."CUR_PRICE_PLAN_CD" IS '컬럼속성1';
   COMMENT ON COLUMN "IFTMS3001"."CUR_PRICE_PLAN_START_DT" IS '컬럼속성2';
   COMMENT ON COLUMN "IFTMS3001"."CUR_PRICE_PLAN_USE_PRD" IS '컬럼속성3';
   COMMENT ON COLUMN "IFTMS3001"."NEW_PRICE_PLAN_CD" IS '컬럼속성4';
   COMMENT ON COLUMN "IFTMS3001"."NEW_PRICE_PLAN_REGIST_DT" IS '컬럼속성5';
   COMMENT ON COLUMN "IFTMS3001"."NEW_PRICE_PLAN_START_DT" IS '컬럼속성6';
   COMMENT ON COLUMN "IFTMS3001"."NEW_JOIN_ACCEPT_SV_AGENCY_CD" IS '컬럼속성7';
   COMMENT ON COLUMN "IFTMS3001"."NEW_JOIN_ACCEPT_SHOP_CD" IS '컬럼속성8';
   COMMENT ON COLUMN "IFTMS3001"."NEW_JOIN_DELIVERY_SV_AGENCY_CD" IS '컬럼속성9';
   COMMENT ON COLUMN "IFTMS3001"."NEW_JOIN_DELIVERY_SHOP_CD" IS '컬럼속성10';
   COMMENT ON COLUMN "IFTMS3001"."LATEST_ACCEPT_SV_AGENCY_CD" IS '컬럼속성11';
   COMMENT ON COLUMN "IFTMS3001"."LATEST_ACCEPT_SHOP_CD" IS '컬럼속성12';
   COMMENT ON COLUMN "IFTMS3001"."LATEST_DELIVERY_SV_AGENCY_CD" IS '컬럼속성13';
   COMMENT ON COLUMN "IFTMS3001"."LATEST_DELIVERY_SHOP_CD" IS '컬럼속성14';
   COMMENT ON COLUMN "IFTMS3001"."LUMP_CLS" IS '컬럼속성15';
   COMMENT ON COLUMN "IFTMS3001"."TYPE" IS '컬럼속성16';
   COMMENT ON COLUMN "IFTMS3001"."SERIAL_NO" IS '컬럼속성17';
   COMMENT ON COLUMN "IFTMS3001"."EQUIP_RK" IS '컬럼속성18';
   COMMENT ON COLUMN "IFTMS3001"."USE_MODEL_START_DT" IS '컬럼속성19';
   COMMENT ON COLUMN "IFTMS3001"."USE_MODEL_USE_PERIOD" IS '컬럼속성20';
   COMMENT ON COLUMN "IFTMS3001"."CHRG_START_DT" IS '컬럼속성21';
   COMMENT ON COLUMN "IFTMS3001"."COUNTING_START_DT" IS '컬럼속성22';
   COMMENT ON COLUMN "IFTMS3001"."SVC_STATUS_L_CLS" IS '컬럼속성23';
   COMMENT ON COLUMN "IFTMS3001"."SVC_STATUS_S_CLS" IS '컬럼속성24';
   COMMENT ON COLUMN "IFTMS3001"."SUSPENSION_DT" IS '컬럼속성25';
   COMMENT ON COLUMN "IFTMS3001"."RE_USE_DT" IS '컬럼속성26';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_TRANS_DT" IS '컬럼속성27';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_REOPEN_DT" IS '컬럼속성28';
   COMMENT ON COLUMN "IFTMS3001"."CLOSE_DT" IS '컬럼속성29';
   COMMENT ON COLUMN "IFTMS3001"."CLOSE_REASON" IS '컬럼속성30';
   COMMENT ON COLUMN "IFTMS3001"."OPERATION_DAYS" IS '컬럼속성31';
   COMMENT ON COLUMN "IFTMS3001"."USE_PRD_TOTAL" IS '컬럼속성32';
   COMMENT ON COLUMN "IFTMS3001"."SVC_CLS" IS '컬럼속성33';
   COMMENT ON COLUMN "IFTMS3001"."CALL_WIDE_FLG" IS '컬럼속성34';
   COMMENT ON COLUMN "IFTMS3001"."GROUP_DSC_FLG" IS '컬럼속성35';
   COMMENT ON COLUMN "IFTMS3001"."MULTI_Y_DSC_CLS" IS '컬럼속성36';
   COMMENT ON COLUMN "IFTMS3001"."WIN_MULTI_CABLE_DSC_FLG" IS '컬럼속성37';
   COMMENT ON COLUMN "IFTMS3001"."AU_HOME_DSC_REGIST_FLG" IS '컬럼속성38';
   COMMENT ON COLUMN "IFTMS3001"."PRIORITY_JOINER_FLG" IS '컬럼속성39';
   COMMENT ON COLUMN "IFTMS3001"."PRICE_CALL_STOP_TOTAL_CNT" IS '컬럼속성40';
   COMMENT ON COLUMN "IFTMS3001"."TEMP_STOP" IS '컬럼속성41';
   COMMENT ON COLUMN "IFTMS3001"."MODEL_CHANGE_CNT" IS '컬럼속성42';
   COMMENT ON COLUMN "IFTMS3001"."MODEL_TROUBLE_CNT" IS '컬럼속성43';
   COMMENT ON COLUMN "IFTMS3001"."TROUBLE_CNT_TOTAL" IS '컬럼속성44';
   COMMENT ON COLUMN "IFTMS3001"."USED_MODEL_CLS" IS '컬럼속성45';
   COMMENT ON COLUMN "IFTMS3001"."WIDE_SPT_APPLY_FLG" IS '컬럼속성46';
   COMMENT ON COLUMN "IFTMS3001"."SUBS_STUDENT_AGE" IS '컬럼속성47';
   COMMENT ON COLUMN "IFTMS3001"."MARU_BUSI_DSC_FLG" IS '컬럼속성48';
   COMMENT ON COLUMN "IFTMS3001"."OTHER_COMPANY_JOIN_CLS" IS '컬럼속성49';
   COMMENT ON COLUMN "IFTMS3001"."FROM_COMPANY_CD" IS '컬럼속성50';
   COMMENT ON COLUMN "IFTMS3001"."TO_COMPANY_CD" IS '컬럼속성51';
   COMMENT ON COLUMN "IFTMS3001"."G_CALL_DSC_CLS" IS '컬럼속성52';
   COMMENT ON COLUMN "IFTMS3001"."PERMISSION_CLS" IS '컬럼속성53';
   COMMENT ON COLUMN "IFTMS3001"."HITORI_FLG" IS '컬럼속성54';
   COMMENT ON COLUMN "IFTMS3001"."MARU_BUSI_CO_CLS" IS '컬럼속성55';
   COMMENT ON COLUMN "IFTMS3001"."SHOP_PURCHASE_METHOD" IS '컬럼속성56';
   COMMENT ON COLUMN "IFTMS3001"."RESULT_TRANS_DT" IS '컬럼속성57';
   COMMENT ON COLUMN "IFTMS3001"."BF_TRANS_RESULT_CLS" IS '컬럼속성58';
   COMMENT ON COLUMN "IFTMS3001"."AF_TRANS_RESULT_CLS" IS '컬럼속성59';
   COMMENT ON COLUMN "IFTMS3001"."FIRST_CHRG_START_DT" IS '컬럼속성60';
   COMMENT ON COLUMN "IFTMS3001"."COLLABO_COMPANY_FLG" IS '컬럼속성61';
   COMMENT ON TABLE "IFTMS3001"  IS '복합운송시장구조3001';


  CREATE TABLE "IFTMS3002" 
   (	"AF_TRANS_JOIN_ACCEPT_SHOP_CD" VARCHAR2(100 BYTE), 
	"AF_TRANS_JOIN_ACCEPT_SV_CD" VARCHAR2(10 BYTE), 
	"AF_TRANS_SUBS_REGION_CD" VARCHAR2(10 BYTE), 
	"AF_TRANS_SUBS_REGION_CLS" VARCHAR2(10 BYTE), 
	"COLLABO_COMPANY_FLG" VARCHAR2(10 BYTE), 
	"CUR_DSC_OP4_CD" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"DEMO_CLS" VARCHAR2(10 BYTE), 
	"EZWEB_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"INTEGRATE_BILL_ACCOUNT" VARCHAR2(10 BYTE), 
	"JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"JOIN_ACCEPT_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"JOIN_DELIVERY_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"LAST_INSERT_DT" VARCHAR2(10 BYTE), 
	"LAST_INSERT_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LAST_UIM_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LAST_UIM_MODEL_SALE_DT" VARCHAR2(10 BYTE), 
	"LATEST_INSERT_DT" VARCHAR2(10 BYTE), 
	"LATEST_INSERT_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LATEST_UIM_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LATEST_UIM_MODEL_SALE_DT" VARCHAR2(10 BYTE), 
	"LATEST_USE_MODEL_EQUIP_RK" VARCHAR2(10 BYTE), 
	"LATEST_USE_MODEL_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"MVNO_CLS" VARCHAR2(10 BYTE), 
	"NEW_DSC_OP4CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"OLD_BILL_CD" VARCHAR2(10 BYTE), 
	"PAY_GROUP" VARCHAR2(10 BYTE), 
	"PCKT_SINGLE_CLS" VARCHAR2(10 BYTE), 
	"SMVL_ABO_REASON" VARCHAR2(10 BYTE), 
	"SMVL_ABO_YM" VARCHAR2(10 BYTE), 
	"SMVL_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"SMVL_ACCEPT_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"SMVL_APPLI_ACCEPT_DT" VARCHAR2(10 BYTE), 
	"SMVL_APPLI_FLG" VARCHAR2(10 BYTE), 
	"SMVL_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_AUTO_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_GROUP_CD" VARCHAR2(10 BYTE), 
	"SMVL_LINK_CLS" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_ABO_REASON" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_CLS" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_END_DT" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_START_DT" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_CLS_CD" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_END_M" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_END_PLAN_M" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_START_DT" VARCHAR2(10 BYTE), 
	"SMVL_START_YM" VARCHAR2(10 BYTE), 
	"SUBS_AGE" VARCHAR2(10 BYTE), 
	"SUBS_DIV_FLG" VARCHAR2(10 BYTE), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"SUBS_REGION_CD" VARCHAR2(10 BYTE), 
	"SUBS_REGION_CLS" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"SUBS_STUDENT_AGE" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"SVC_CLS" VARCHAR2(10 BYTE), 
	"SVC_STATUS_L_CLS" VARCHAR2(10 BYTE), 
	"SVC_STATUS_S_CLS" VARCHAR2(10 BYTE), 
	"TARGET_AGE" VARCHAR2(10 BYTE), 
	"TARGET_STUDENT_AGE" VARCHAR2(10 BYTE), 
	"USED_MODEL_CLS" VARCHAR2(10 BYTE), 
	"USE_MODEL_START_DT" VARCHAR2(10 BYTE), 
	"YM" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3002"."AF_TRANS_JOIN_ACCEPT_SHOP_CD" IS '복합운송시장구조3002컬럼속성1';
   COMMENT ON COLUMN "IFTMS3002"."AF_TRANS_JOIN_ACCEPT_SV_CD" IS '복합운송시장구조3002컬럼속성2';
   COMMENT ON COLUMN "IFTMS3002"."AF_TRANS_SUBS_REGION_CD" IS '복합운송시장구조3002컬럼속성3';
   COMMENT ON COLUMN "IFTMS3002"."AF_TRANS_SUBS_REGION_CLS" IS '복합운송시장구조3002컬럼속성4';
   COMMENT ON COLUMN "IFTMS3002"."COLLABO_COMPANY_FLG" IS '복합운송시장구조3002컬럼속성5';
   COMMENT ON COLUMN "IFTMS3002"."CUR_DSC_OP4_CD" IS '복합운송시장구조3002컬럼속성6';
   COMMENT ON COLUMN "IFTMS3002"."CUR_PRICE_PLAN_CD" IS '복합운송시장구조3002컬럼속성7';
   COMMENT ON COLUMN "IFTMS3002"."DEMO_CLS" IS '복합운송시장구조3002컬럼속성8';
   COMMENT ON COLUMN "IFTMS3002"."EZWEB_CLS" IS '복합운송시장구조3002컬럼속성9';
   COMMENT ON COLUMN "IFTMS3002"."FIRST_CHRG_START_DT" IS '복합운송시장구조3002컬럼속성10';
   COMMENT ON COLUMN "IFTMS3002"."INTEGRATE_BILL_ACCOUNT" IS '복합운송시장구조3002컬럼속성11';
   COMMENT ON COLUMN "IFTMS3002"."JOIN_ACCEPT_SHOP_CD" IS '복합운송시장구조3002컬럼속성12';
   COMMENT ON COLUMN "IFTMS3002"."JOIN_ACCEPT_SUPERVISOR_CD" IS '복합운송시장구조3002컬럼속성13';
   COMMENT ON COLUMN "IFTMS3002"."JOIN_DELIVERY_SHOP_CD" IS '복합운송시장구조3002컬럼속성14';
   COMMENT ON COLUMN "IFTMS3002"."JOIN_DELIVERY_SUPERVISOR_CD" IS '복합운송시장구조3002컬럼속성15';
   COMMENT ON COLUMN "IFTMS3002"."LAST_INSERT_DT" IS '복합운송시장구조3002컬럼속성16';
   COMMENT ON COLUMN "IFTMS3002"."LAST_INSERT_EQUIP_SYS_RK" IS '복합운송시장구조3002컬럼속성17';
   COMMENT ON COLUMN "IFTMS3002"."LAST_UIM_EQUIP_SYS_RK" IS '복합운송시장구조3002컬럼속성18';
   COMMENT ON COLUMN "IFTMS3002"."LAST_UIM_MODEL_SALE_DT" IS '복합운송시장구조3002컬럼속성19';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_INSERT_DT" IS '복합운송시장구조3002컬럼속성20';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_INSERT_EQUIP_SYS_RK" IS '복합운송시장구조3002컬럼속성21';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_UIM_EQUIP_SYS_RK" IS '복합운송시장구조3002컬럼속성22';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_UIM_MODEL_SALE_DT" IS '복합운송시장구조3002컬럼속성23';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_USE_MODEL_EQUIP_RK" IS '복합운송시장구조3002컬럼속성24';
   COMMENT ON COLUMN "IFTMS3002"."LATEST_USE_MODEL_EQUIP_SYS_RK" IS '복합운송시장구조3002컬럼속성25';
   COMMENT ON COLUMN "IFTMS3002"."MVNO_CLS" IS '복합운송시장구조3002컬럼속성26';
   COMMENT ON COLUMN "IFTMS3002"."NEW_DSC_OP4CD" IS '복합운송시장구조3002컬럼속성27';
   COMMENT ON COLUMN "IFTMS3002"."NEW_PRICE_PLAN_CD" IS '복합운송시장구조3002컬럼속성28';
   COMMENT ON COLUMN "IFTMS3002"."OLD_BILL_CD" IS '복합운송시장구조3002컬럼속성29';
   COMMENT ON COLUMN "IFTMS3002"."PAY_GROUP" IS '복합운송시장구조3002컬럼속성30';
   COMMENT ON COLUMN "IFTMS3002"."PCKT_SINGLE_CLS" IS '복합운송시장구조3002컬럼속성31';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ABO_REASON" IS '복합운송시장구조3002컬럼속성32';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ABO_YM" IS '복합운송시장구조3002컬럼속성33';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ACCEPT_SHOP_CD" IS '복합운송시장구조3002컬럼속성34';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ACCEPT_SUPERVISOR_CD" IS '복합운송시장구조3002컬럼속성35';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_APPLI_ACCEPT_DT" IS '복합운송시장구조3002컬럼속성36';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_APPLI_FLG" IS '복합운송시장구조3002컬럼속성37';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_APPLY_FLG" IS '복합운송시장구조3002컬럼속성38';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_AUTO_APPLY_FLG" IS '복합운송시장구조3002컬럼속성39';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_GROUP_CD" IS '복합운송시장구조3002컬럼속성40';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_LINK_CLS" IS '복합운송시장구조3002컬럼속성41';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ROUTER_DSC_ABO_REASON" IS '복합운송시장구조3002컬럼속성42';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ROUTER_DSC_CLS" IS '복합운송시장구조3002컬럼속성43';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ROUTER_DSC_END_DT" IS '복합운송시장구조3002컬럼속성44';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_ROUTER_DSC_START_DT" IS '복합운송시장구조3002컬럼속성45';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_SP_DSC_APPLY_FLG" IS '복합운송시장구조3002컬럼속성46';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_SP_DSC_CLS_CD" IS '복합운송시장구조3002컬럼속성47';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_SP_DSC_END_M" IS '복합운송시장구조3002컬럼속성48';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_SP_DSC_END_PLAN_M" IS '복합운송시장구조3002컬럼속성49';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_SP_DSC_START_DT" IS '복합운송시장구조3002컬럼속성50';
   COMMENT ON COLUMN "IFTMS3002"."SMVL_START_YM" IS '복합운송시장구조3002컬럼속성51';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_AGE" IS '복합운송시장구조3002컬럼속성52';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_DIV_FLG" IS '복합운송시장구조3002컬럼속성53';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_GENDER_CLS" IS '복합운송시장구조3002컬럼속성54';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_REGION_CD" IS '복합운송시장구조3002컬럼속성55';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_REGION_CLS" IS '복합운송시장구조3002컬럼속성56';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_RK" IS '복합운송시장구조3002컬럼속성57';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_STUDENT_AGE" IS '복합운송시장구조3002컬럼속성58';
   COMMENT ON COLUMN "IFTMS3002"."SUBS_TYPE" IS '복합운송시장구조3002컬럼속성59';
   COMMENT ON COLUMN "IFTMS3002"."SVC_CLS" IS '복합운송시장구조3002컬럼속성60';
   COMMENT ON COLUMN "IFTMS3002"."SVC_STATUS_L_CLS" IS '복합운송시장구조3002컬럼속성61';
   COMMENT ON COLUMN "IFTMS3002"."SVC_STATUS_S_CLS" IS '복합운송시장구조3002컬럼속성62';
   COMMENT ON COLUMN "IFTMS3002"."TARGET_AGE" IS '복합운송시장구조3002컬럼속성63';
   COMMENT ON COLUMN "IFTMS3002"."TARGET_STUDENT_AGE" IS '복합운송시장구조3002컬럼속성64';
   COMMENT ON COLUMN "IFTMS3002"."USED_MODEL_CLS" IS '복합운송시장구조3002컬럼속성65';
   COMMENT ON COLUMN "IFTMS3002"."USE_MODEL_START_DT" IS '복합운송시장구조3002컬럼속성66';
   COMMENT ON COLUMN "IFTMS3002"."YM" IS '복합운송시장구조3002컬럼속성67';
   COMMENT ON TABLE "IFTMS3002"  IS '복합운송시장구조3002';


  CREATE TABLE "IFTMS3003" 
   (	"SUPERVISOR_CD" VARCHAR2(100 BYTE), 
	"SHOP_CD" VARCHAR2(10 BYTE), 
	"SHOP_NAME" VARCHAR2(10 BYTE), 
	"SHOP_SHORT_NAME" VARCHAR2(10 BYTE), 
	"REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_NAME" VARCHAR2(10 BYTE), 
	"SHOP_HANDLE_CD" VARCHAR2(10 BYTE), 
	"SHOP_POSTAL_CD" VARCHAR2(10 BYTE), 
	"SHOP_PREF_CD" VARCHAR2(10 BYTE), 
	"SHOP_CITY_CD" VARCHAR2(10 BYTE), 
	"SHOP_CLS" VARCHAR2(10 BYTE), 
	"INSTAL_SALE_CLS" VARCHAR2(10 BYTE), 
	"AU_AGENCY_CLS" VARCHAR2(10 BYTE), 
	"MVNO_CLS" VARCHAR2(10 BYTE), 
	"GROUP_CD_SV" VARCHAR2(10 BYTE), 
	"GROUP_CD_SHOP" VARCHAR2(10 BYTE), 
	"GROUP_CLS" VARCHAR2(10 BYTE), 
	"DIST_AF_SHOP" VARCHAR2(10 BYTE), 
	"MONOPOLY_CLS" VARCHAR2(10 BYTE)
   )
   ;

   COMMENT ON COLUMN "IFTMS3003"."SUPERVISOR_CD" IS '감독자코드';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_CD" IS '샵코드';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_NAME" IS '샵이름';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_SHORT_NAME" IS '샵매장명';
   COMMENT ON COLUMN "IFTMS3003"."REGION_CD" IS '등록코드';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_REGION_CD" IS '샵등록코드';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_REGION_NAME" IS '샵등록명';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_HANDLE_CD" IS '샵핸들코드';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_POSTAL_CD" IS '샵우편코드';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_PREF_CD" IS '샵프리코드';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_CITY_CD" IS '샵도시코드';
   COMMENT ON COLUMN "IFTMS3003"."SHOP_CLS" IS '샵등급';
   COMMENT ON COLUMN "IFTMS3003"."INSTAL_SALE_CLS" IS '설치판매등급';
   COMMENT ON COLUMN "IFTMS3003"."AU_AGENCY_CLS" IS 'AU대리등급';
   COMMENT ON COLUMN "IFTMS3003"."MVNO_CLS" IS '통신사등급';
   COMMENT ON COLUMN "IFTMS3003"."GROUP_CD_SV" IS '그룹코드서비스';
   COMMENT ON COLUMN "IFTMS3003"."GROUP_CD_SHOP" IS '그룹코드샵';
   COMMENT ON COLUMN "IFTMS3003"."DIST_AF_SHOP" IS '거리AF샵';
   COMMENT ON COLUMN "IFTMS3003"."MONOPOLY_CLS" IS '통신폴리등급';
   COMMENT ON TABLE "IFTMS3003"  IS '복합운송시장구조3003';


  CREATE TABLE "IFTMS3004" 
   (	"YM" VARCHAR2(100 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"AU_ID_PWD_UPD_DT" VARCHAR2(10 BYTE), 
	"AU_ID_PWD_UPD_TM" VARCHAR2(10 BYTE), 
	"PWD_INITIAL_CHANGE_CLS" VARCHAR2(10 BYTE), 
	"APPLY_LOCK_CLS" VARCHAR2(10 BYTE), 
	"APPLY_LOCK_REASON_CLS" VARCHAR2(10 BYTE), 
	"AU_ID_TRANS_DETER_CLS" VARCHAR2(10 BYTE), 
	"ALIAS_AU_ID_CHG_CNT" NUMBER(10,0), 
	"AU_ID_INTERGRATE_SP_CNT" NUMBER(10,0), 
	"IOT_ID_CLS" VARCHAR2(10 BYTE), 
	"ACTIVE_DT" VARCHAR2(10 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE), 
	"CHURN_IN_DT" VARCHAR2(10 BYTE), 
	"CHURN_IN_SUBS_RK" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3004"."YM" IS '컬럼속성1';
   COMMENT ON COLUMN "IFTMS3004"."AU_ID" IS '컬럼속성2';
   COMMENT ON COLUMN "IFTMS3004"."AU_ID_PWD_UPD_DT" IS '컬럼속성3';
   COMMENT ON COLUMN "IFTMS3004"."AU_ID_PWD_UPD_TM" IS '컬럼속성4';
   COMMENT ON COLUMN "IFTMS3004"."PWD_INITIAL_CHANGE_CLS" IS '컬럼속성5';
   COMMENT ON COLUMN "IFTMS3004"."APPLY_LOCK_CLS" IS '컬럼속성6';
   COMMENT ON COLUMN "IFTMS3004"."APPLY_LOCK_REASON_CLS" IS '컬럼속성7';
   COMMENT ON COLUMN "IFTMS3004"."AU_ID_TRANS_DETER_CLS" IS '컬럼속성8';
   COMMENT ON COLUMN "IFTMS3004"."ALIAS_AU_ID_CHG_CNT" IS '컬럼속성9';
   COMMENT ON COLUMN "IFTMS3004"."AU_ID_INTERGRATE_SP_CNT" IS '컬럼속성10';
   COMMENT ON COLUMN "IFTMS3004"."IOT_ID_CLS" IS '컬럼속성11';
   COMMENT ON COLUMN "IFTMS3004"."ACTIVE_DT" IS '컬럼속성12';
   COMMENT ON COLUMN "IFTMS3004"."ACTIVE_TM" IS '컬럼속성13';
   COMMENT ON COLUMN "IFTMS3004"."INVALID_DT" IS '컬럼속성14';
   COMMENT ON COLUMN "IFTMS3004"."INVALID_TM" IS '컬럼속성15';
   COMMENT ON COLUMN "IFTMS3004"."INVALID_FLG" IS '컬럼속성16';
   COMMENT ON COLUMN "IFTMS3004"."CHURN_IN_DT" IS '컬럼속성17';
   COMMENT ON COLUMN "IFTMS3004"."CHURN_IN_SUBS_RK" IS '컬럼속성18';
   COMMENT ON TABLE "IFTMS3004"  IS '복합운송시장구조3004';


  CREATE TABLE "IFTMS3005" 
   (	"ACTIVE_DT" VARCHAR2(100 BYTE), 
	"APPROVAL_TICKET_ID" VARCHAR2(10 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"BIRTH_DT" VARCHAR2(10 BYTE), 
	"CUST_CLS" VARCHAR2(10 BYTE), 
	"CUST_FIRST_REGIST_DT" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"CUST_MAIL1_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"CUST_MAIL2_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"CUST_PWD_UPD_DT" VARCHAR2(10 BYTE), 
	"CUST_PWD_UPD_TM" VARCHAR2(10 BYTE), 
	"DELE_AU_SUBS_RK" VARCHAR2(10 BYTE), 
	"EZ_MAIL_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"GENDER_CLS" VARCHAR2(10 BYTE), 
	"IDENTIFICATION_DT" VARCHAR2(10 BYTE), 
	"IDENTIFICATION_LEVEL" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE), 
	"PWD_INITIAL_CHANGE_CLS" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3005"."ACTIVE_DT" IS '복합운송시장구조3005컬럼속성1';
   COMMENT ON COLUMN "IFTMS3005"."APPROVAL_TICKET_ID" IS '복합운송시장구조3005컬럼속성2';
   COMMENT ON COLUMN "IFTMS3005"."AU_ID" IS '복합운송시장구조3005컬럼속성3';
   COMMENT ON COLUMN "IFTMS3005"."BIRTH_DT" IS '복합운송시장구조3005컬럼속성4';
   COMMENT ON COLUMN "IFTMS3005"."CUST_CLS" IS '복합운송시장구조3005컬럼속성5';
   COMMENT ON COLUMN "IFTMS3005"."CUST_FIRST_REGIST_DT" IS '복합운송시장구조3005컬럼속성6';
   COMMENT ON COLUMN "IFTMS3005"."CUST_ID" IS '복합운송시장구조3005컬럼속성7';
   COMMENT ON COLUMN "IFTMS3005"."CUST_MAIL1_NOTICE_FLG" IS '복합운송시장구조3005컬럼속성8';
   COMMENT ON COLUMN "IFTMS3005"."CUST_MAIL2_NOTICE_FLG" IS '복합운송시장구조3005컬럼속성9';
   COMMENT ON COLUMN "IFTMS3005"."CUST_PWD_UPD_DT" IS '복합운송시장구조3005컬럼속성10';
   COMMENT ON COLUMN "IFTMS3005"."CUST_PWD_UPD_TM" IS '복합운송시장구조3005컬럼속성11';
   COMMENT ON COLUMN "IFTMS3005"."DELE_AU_SUBS_RK" IS '복합운송시장구조3005컬럼속성12';
   COMMENT ON COLUMN "IFTMS3005"."EZ_MAIL_NOTICE_FLG" IS '복합운송시장구조3005컬럼속성13';
   COMMENT ON COLUMN "IFTMS3005"."GENDER_CLS" IS '복합운송시장구조3005컬럼속성14';
   COMMENT ON COLUMN "IFTMS3005"."IDENTIFICATION_DT" IS '복합운송시장구조3005컬럼속성15';
   COMMENT ON COLUMN "IFTMS3005"."IDENTIFICATION_LEVEL" IS '복합운송시장구조3005컬럼속성16';
   COMMENT ON COLUMN "IFTMS3005"."INVALID_DT" IS '복합운송시장구조3005컬럼속성17';
   COMMENT ON COLUMN "IFTMS3005"."INVALID_FLG" IS '복합운송시장구조3005컬럼속성18';
   COMMENT ON COLUMN "IFTMS3005"."PWD_INITIAL_CHANGE_CLS" IS '복합운송시장구조3005컬럼속성19';
   COMMENT ON TABLE "IFTMS3005"  IS '복합운송시장구조3005';


  CREATE TABLE "IFTMS3006" 
   (	"ACTIVE_DT" VARCHAR2(100 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"SUBS_CLS" VARCHAR2(10 BYTE), 
	"SUBS_ID" VARCHAR2(10 BYTE), 
	"SUBS_LINK_STATUS_CD" VARCHAR2(10 BYTE), 
	"YM" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3006"."ACTIVE_DT" IS '복합운송시장구조3006컬럼속성1';
   COMMENT ON COLUMN "IFTMS3006"."ACTIVE_TM" IS '복합운송시장구조3006컬럼속성2';
   COMMENT ON COLUMN "IFTMS3006"."CUST_ID" IS '복합운송시장구조3006컬럼속성3';
   COMMENT ON COLUMN "IFTMS3006"."INVALID_DT" IS '복합운송시장구조3006컬럼속성4';
   COMMENT ON COLUMN "IFTMS3006"."INVALID_FLG" IS '복합운송시장구조3006컬럼속성5';
   COMMENT ON COLUMN "IFTMS3006"."INVALID_TM" IS '복합운송시장구조3006컬럼속성6';
   COMMENT ON COLUMN "IFTMS3006"."SUBS_CLS" IS '복합운송시장구조3006컬럼속성7';
   COMMENT ON COLUMN "IFTMS3006"."SUBS_ID" IS '복합운송시장구조3006컬럼속성8';
   COMMENT ON COLUMN "IFTMS3006"."SUBS_LINK_STATUS_CD" IS '복합운송시장구조3006컬럼속성9';
   COMMENT ON COLUMN "IFTMS3006"."YM" IS '복합운송시장구조3006컬럼속성10';
   COMMENT ON TABLE "IFTMS3006"  IS '복합운송시장구조3006';


  CREATE TABLE "IFTMS3007" 
   (	"ACTIVE_DT" VARCHAR2(100 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"DELE_SUBS_ID" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"SUBS_CLS" VARCHAR2(10 BYTE), 
	"YM" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "IFTMS3007"."ACTIVE_DT" IS '복합운송시장구조3007컬럼속성1';
   COMMENT ON COLUMN "IFTMS3007"."ACTIVE_TM" IS '복합운송시장구조3007컬럼속성2';
   COMMENT ON COLUMN "IFTMS3007"."CUST_ID" IS '복합운송시장구조3007컬럼속성3';
   COMMENT ON COLUMN "IFTMS3007"."DELE_SUBS_ID" IS '복합운송시장구조3007컬럼속성4';
   COMMENT ON COLUMN "IFTMS3007"."INVALID_DT" IS '복합운송시장구조3007컬럼속성5';
   COMMENT ON COLUMN "IFTMS3007"."INVALID_FLG" IS '복합운송시장구조3007컬럼속성6';
   COMMENT ON COLUMN "IFTMS3007"."INVALID_TM" IS '복합운송시장구조3007컬럼속성7';
   COMMENT ON COLUMN "IFTMS3007"."SUBS_CLS" IS '복합운송시장구조3007컬럼속성8';
   COMMENT ON COLUMN "IFTMS3007"."YM" IS '복합운송시장구조3007컬럼속성9';
   COMMENT ON TABLE "IFTMS3007"  IS '복합운송시장구조3007';


  CREATE TABLE "K_MONTH_AUID" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"AU_ID_PWD_UPD_DT" VARCHAR2(10 BYTE), 
	"AU_ID_PWD_UPD_TM" VARCHAR2(10 BYTE), 
	"PWD_INITIAL_CHANGE_CLS" VARCHAR2(10 BYTE), 
	"APPLY_LOCK_CLS" VARCHAR2(10 BYTE), 
	"APPLY_LOCK_REASON_CLS" VARCHAR2(10 BYTE), 
	"AU_ID_TRANS_DETER_CLS" VARCHAR2(10 BYTE), 
	"ALIAS_AU_ID_CHG_CNT" NUMBER(10,0), 
	"AU_ID_INTERGRATE_SP_CNT" NUMBER(10,0), 
	"IOT_ID_CLS" VARCHAR2(10 BYTE), 
	"ACTIVE_DT" VARCHAR2(10 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE), 
	"CHURN_IN_DT" VARCHAR2(10 BYTE), 
	"CHURN_IN_SUBS_RK" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "K_MONTH_AUID"."ACQ_DT" IS 'K월AUID컬럼속성1';
   COMMENT ON COLUMN "K_MONTH_AUID"."YM" IS 'K월AUID컬럼속성2';
   COMMENT ON COLUMN "K_MONTH_AUID"."AU_ID" IS 'K월AUID컬럼속성3';
   COMMENT ON COLUMN "K_MONTH_AUID"."AU_ID_PWD_UPD_DT" IS 'K월AUID컬럼속성4';
   COMMENT ON COLUMN "K_MONTH_AUID"."AU_ID_PWD_UPD_TM" IS 'K월AUID컬럼속성5';
   COMMENT ON COLUMN "K_MONTH_AUID"."PWD_INITIAL_CHANGE_CLS" IS 'K월AUID컬럼속성6';
   COMMENT ON COLUMN "K_MONTH_AUID"."APPLY_LOCK_CLS" IS 'K월AUID컬럼속성7';
   COMMENT ON COLUMN "K_MONTH_AUID"."APPLY_LOCK_REASON_CLS" IS 'K월AUID컬럼속성8';
   COMMENT ON COLUMN "K_MONTH_AUID"."AU_ID_TRANS_DETER_CLS" IS 'K월AUID컬럼속성9';
   COMMENT ON COLUMN "K_MONTH_AUID"."ALIAS_AU_ID_CHG_CNT" IS 'K월AUID컬럼속성10';
   COMMENT ON COLUMN "K_MONTH_AUID"."AU_ID_INTERGRATE_SP_CNT" IS 'K월AUID컬럼속성11';
   COMMENT ON COLUMN "K_MONTH_AUID"."IOT_ID_CLS" IS 'K월AUID컬럼속성12';
   COMMENT ON COLUMN "K_MONTH_AUID"."ACTIVE_DT" IS 'K월AUID컬럼속성13';
   COMMENT ON COLUMN "K_MONTH_AUID"."ACTIVE_TM" IS 'K월AUID컬럼속성14';
   COMMENT ON COLUMN "K_MONTH_AUID"."INVALID_DT" IS 'K월AUID컬럼속성15';
   COMMENT ON COLUMN "K_MONTH_AUID"."INVALID_TM" IS 'K월AUID컬럼속성16';
   COMMENT ON COLUMN "K_MONTH_AUID"."INVALID_FLG" IS 'K월AUID컬럼속성17';
   COMMENT ON COLUMN "K_MONTH_AUID"."CHURN_IN_DT" IS 'K월AUID컬럼속성18';
   COMMENT ON COLUMN "K_MONTH_AUID"."CHURN_IN_SUBS_RK" IS 'K월AUID컬럼속성19';
   COMMENT ON TABLE "K_MONTH_AUID"  IS 'K_월AUID';


  CREATE TABLE "K_MONTH_CUST_INF" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"SUBS_REGION_CLS" VARCHAR2(10 BYTE), 
	"SUBS_REGION_CD" VARCHAR2(10 BYTE), 
	"SVC_STATUS_L_CLS" VARCHAR2(10 BYTE), 
	"SVC_STATUS_S_CLS" VARCHAR2(10 BYTE), 
	"OLD_BILL_CD" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"SUBS_AGE" NUMBER(10,0), 
	"SUBS_STUDENT_AGE" NUMBER(10,0), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"JOIN_ACCEPT_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"JOIN_DELIVERY_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"AF_TRANS_SUBS_REGION_CLS" VARCHAR2(10 BYTE), 
	"AF_TRANS_SUBS_REGION_CD" VARCHAR2(10 BYTE), 
	"AF_TRANS_JOIN_ACCEPT_SV_CD" VARCHAR2(10 BYTE), 
	"AF_TRANS_JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"LAST_UIM_MODEL_SALE_DT" VARCHAR2(10 BYTE), 
	"LAST_UIM_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LATEST_UIM_MODEL_SALE_DT" VARCHAR2(10 BYTE), 
	"LATEST_UIM_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LAST_INSERT_DT" VARCHAR2(10 BYTE), 
	"LAST_INSERT_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"LATEST_INSERT_DT" VARCHAR2(10 BYTE), 
	"LATEST_INSERT_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"SUBS_DIV_FLG" VARCHAR2(10 BYTE), 
	"MVNO_CLS" VARCHAR2(10 BYTE), 
	"TARGET_STUDENT_AGE" NUMBER(10,0), 
	"TARGET_AGE" NUMBER(10,0), 
	"DEMO_CLS" VARCHAR2(10 BYTE), 
	"PAY_GROUP" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"CUR_DSC_OP4_CD" VARCHAR2(10 BYTE), 
	"COLLABO_COMPANY_FLG" VARCHAR2(10 BYTE), 
	"USED_MODEL_CLS" VARCHAR2(10 BYTE), 
	"USE_MODEL_START_DT" VARCHAR2(10 BYTE), 
	"SVC_CLS" VARCHAR2(10 BYTE), 
	"EZWEB_CLS" VARCHAR2(10 BYTE), 
	"SMVL_GROUP_CD" VARCHAR2(10 BYTE), 
	"SMVL_START_YM" VARCHAR2(10 BYTE), 
	"SMVL_ABO_YM" VARCHAR2(10 BYTE), 
	"SMVL_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_APPLI_FLG" VARCHAR2(10 BYTE), 
	"SMVL_ABO_REASON" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_CLS" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_START_DT" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_END_DT" VARCHAR2(10 BYTE), 
	"SMVL_ROUTER_DSC_ABO_REASON" VARCHAR2(10 BYTE), 
	"SMVL_APPLI_ACCEPT_DT" VARCHAR2(10 BYTE), 
	"SMVL_ACCEPT_SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"SMVL_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"SMVL_AUTO_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_LINK_CLS" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_START_DT" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_END_M" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_END_PLAN_M" VARCHAR2(10 BYTE), 
	"SMVL_SP_DSC_CLS_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"NEW_DSC_OP4CD" VARCHAR2(10 BYTE), 
	"LATEST_USE_MODEL_EQUIP_RK" VARCHAR2(10 BYTE), 
	"LATEST_USE_MODEL_EQUIP_SYS_RK" VARCHAR2(10 BYTE), 
	"PCKT_SINGLE_CLS" VARCHAR2(10 BYTE), 
	"INTEGRATE_BILL_ACCOUNT" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "K_MONTH_CUST_INF"."ACQ_DT" IS 'K_월고객정보컬럼속성1';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_RK" IS 'K_월고객정보컬럼속성2';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."YM" IS 'K_월고객정보컬럼속성3';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_REGION_CLS" IS 'K_월고객정보컬럼속성4';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_REGION_CD" IS 'K_월고객정보컬럼속성5';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SVC_STATUS_L_CLS" IS 'K_월고객정보컬럼속성6';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SVC_STATUS_S_CLS" IS 'K_월고객정보컬럼속성7';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."OLD_BILL_CD" IS 'K_월고객정보컬럼속성8';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_TYPE" IS 'K_월고객정보컬럼속성9';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_AGE" IS 'K_월고객정보컬럼속성10';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_STUDENT_AGE" IS 'K_월고객정보컬럼속성11';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_GENDER_CLS" IS 'K_월고객정보컬럼속성12';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."FIRST_CHRG_START_DT" IS 'K_월고객정보컬럼속성13';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."JOIN_ACCEPT_SUPERVISOR_CD" IS 'K_월고객정보컬럼속성14';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."JOIN_ACCEPT_SHOP_CD" IS 'K_월고객정보컬럼속성15';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."JOIN_DELIVERY_SUPERVISOR_CD" IS 'K_월고객정보컬럼속성16';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."JOIN_DELIVERY_SHOP_CD" IS 'K_월고객정보컬럼속성17';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."AF_TRANS_SUBS_REGION_CLS" IS 'K_월고객정보컬럼속성18';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."AF_TRANS_SUBS_REGION_CD" IS 'K_월고객정보컬럼속성19';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."AF_TRANS_JOIN_ACCEPT_SV_CD" IS 'K_월고객정보컬럼속성20';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."AF_TRANS_JOIN_ACCEPT_SHOP_CD" IS 'K_월고객정보컬럼속성21';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LAST_UIM_MODEL_SALE_DT" IS 'K_월고객정보컬럼속성22';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LAST_UIM_EQUIP_SYS_RK" IS 'K_월고객정보컬럼속성23';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_UIM_MODEL_SALE_DT" IS 'K_월고객정보컬럼속성24';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_UIM_EQUIP_SYS_RK" IS 'K_월고객정보컬럼속성25';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LAST_INSERT_DT" IS 'K_월고객정보컬럼속성26';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LAST_INSERT_EQUIP_SYS_RK" IS 'K_월고객정보컬럼속성27';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_INSERT_DT" IS 'K_월고객정보컬럼속성28';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_INSERT_EQUIP_SYS_RK" IS 'K_월고객정보컬럼속성29';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SUBS_DIV_FLG" IS 'K_월고객정보컬럼속성30';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."MVNO_CLS" IS 'K_월고객정보컬럼속성31';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."TARGET_STUDENT_AGE" IS 'K_월고객정보컬럼속성32';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."TARGET_AGE" IS 'K_월고객정보컬럼속성33';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."DEMO_CLS" IS 'K_월고객정보컬럼속성34';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."PAY_GROUP" IS 'K_월고객정보컬럼속성35';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."CUR_PRICE_PLAN_CD" IS 'K_월고객정보컬럼속성36';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."CUR_DSC_OP4_CD" IS 'K_월고객정보컬럼속성37';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."COLLABO_COMPANY_FLG" IS 'K_월고객정보컬럼속성38';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."USED_MODEL_CLS" IS 'K_월고객정보컬럼속성39';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."USE_MODEL_START_DT" IS 'K_월고객정보컬럼속성40';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SVC_CLS" IS 'K_월고객정보컬럼속성41';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."EZWEB_CLS" IS 'K_월고객정보컬럼속성42';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_GROUP_CD" IS 'K_월고객정보컬럼속성43';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_START_YM" IS 'K_월고객정보컬럼속성44';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ABO_YM" IS 'K_월고객정보컬럼속성45';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_APPLY_FLG" IS 'K_월고객정보컬럼속성46';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_APPLI_FLG" IS 'K_월고객정보컬럼속성47';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ABO_REASON" IS 'K_월고객정보컬럼속성48';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ROUTER_DSC_CLS" IS 'K_월고객정보컬럼속성49';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ROUTER_DSC_START_DT" IS 'K_월고객정보컬럼속성50';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ROUTER_DSC_END_DT" IS 'K_월고객정보컬럼속성51';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ROUTER_DSC_ABO_REASON" IS 'K_월고객정보컬럼속성52';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_APPLI_ACCEPT_DT" IS 'K_월고객정보컬럼속성53';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ACCEPT_SUPERVISOR_CD" IS 'K_월고객정보컬럼속성54';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_ACCEPT_SHOP_CD" IS 'K_월고객정보컬럼속성55';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_AUTO_APPLY_FLG" IS 'K_월고객정보컬럼속성56';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_LINK_CLS" IS 'K_월고객정보컬럼속성57';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_SP_DSC_APPLY_FLG" IS 'K_월고객정보컬럼속성58';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_SP_DSC_START_DT" IS 'K_월고객정보컬럼속성59';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_SP_DSC_END_M" IS 'K_월고객정보컬럼속성60';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_SP_DSC_END_PLAN_M" IS 'K_월고객정보컬럼속성61';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."SMVL_SP_DSC_CLS_CD" IS 'K_월고객정보컬럼속성62';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."NEW_PRICE_PLAN_CD" IS 'K_월고객정보컬럼속성63';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."NEW_DSC_OP4CD" IS 'K_월고객정보컬럼속성64';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_USE_MODEL_EQUIP_RK" IS 'K_월고객정보컬럼속성65';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."LATEST_USE_MODEL_EQUIP_SYS_RK" IS 'K_월고객정보컬럼속성66';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."PCKT_SINGLE_CLS" IS 'K_월고객정보컬럼속성67';
   COMMENT ON COLUMN "K_MONTH_CUST_INF"."INTEGRATE_BILL_ACCOUNT" IS 'K_월고객정보컬럼속성68';
   COMMENT ON TABLE "K_MONTH_CUST_INF"  IS 'K_월고객정보';


  CREATE TABLE "K_MONTH_DELE_SUBS" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"SUBS_CLS" VARCHAR2(10 BYTE), 
	"DELE_SUBS_ID" VARCHAR2(10 BYTE), 
	"ACTIVE_DT" VARCHAR2(10 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."ACQ_DT" IS 'K_월삭제대래자컬럼속성1';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."YM" IS 'K_월삭제대래자컬럼속성2';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."CUST_ID" IS 'K_월삭제대래자컬럼속성3';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."SUBS_CLS" IS 'K_월삭제대래자컬럼속성4';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."DELE_SUBS_ID" IS 'K_월삭제대래자컬럼속성5';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."ACTIVE_DT" IS 'K_월삭제대래자컬럼속성6';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."ACTIVE_TM" IS 'K_월삭제대래자컬럼속성7';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."INVALID_DT" IS 'K_월삭제대래자컬럼속성8';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."INVALID_TM" IS 'K_월삭제대래자컬럼속성9';
   COMMENT ON COLUMN "K_MONTH_DELE_SUBS"."INVALID_FLG" IS 'K_월삭제대래자컬럼속성10';
   COMMENT ON TABLE "K_MONTH_DELE_SUBS"  IS 'K_월삭제대래자';


  CREATE TABLE "K_MONTH_SITE_CUST" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"CUST_CLS" VARCHAR2(10 BYTE), 
	"BIRTH_DT" VARCHAR2(10 BYTE), 
	"GENDER_CLS" VARCHAR2(10 BYTE), 
	"IDENTIFICATION_LEVEL" VARCHAR2(10 BYTE), 
	"IDENTIFICATION_DT" VARCHAR2(10 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"CUST_PWD_UPD_DT" VARCHAR2(10 BYTE), 
	"CUST_PWD_UPD_TM" VARCHAR2(10 BYTE), 
	"PWD_INITIAL_CHANGE_CLS" VARCHAR2(10 BYTE), 
	"CUST_MAIL1_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"CUST_MAIL2_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"EZ_MAIL_NOTICE_FLG" VARCHAR2(10 BYTE), 
	"DELE_AU_SUBS_RK" VARCHAR2(10 BYTE), 
	"APPROVAL_TICKET_ID" VARCHAR2(10 BYTE), 
	"CUST_FIRST_REGIST_DT" VARCHAR2(10 BYTE), 
	"ACTIVE_DT" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."ACQ_DT" IS 'K_월별사이트고객컬럼속성1';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."YM" IS 'K_월별사이트고객컬럼속성2';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_ID" IS 'K_월별사이트고객컬럼속성3';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_CLS" IS 'K_월별사이트고객컬럼속성4';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."BIRTH_DT" IS 'K_월별사이트고객컬럼속성5';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."GENDER_CLS" IS 'K_월별사이트고객컬럼속성6';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."IDENTIFICATION_LEVEL" IS 'K_월별사이트고객컬럼속성7';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."IDENTIFICATION_DT" IS 'K_월별사이트고객컬럼속성8';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."AU_ID" IS 'K_월별사이트고객컬럼속성9';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_PWD_UPD_DT" IS 'K_월별사이트고객컬럼속성10';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_PWD_UPD_TM" IS 'K_월별사이트고객컬럼속성11';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."PWD_INITIAL_CHANGE_CLS" IS 'K_월별사이트고객컬럼속성12';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_MAIL1_NOTICE_FLG" IS 'K_월별사이트고객컬럼속성13';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_MAIL2_NOTICE_FLG" IS 'K_월별사이트고객컬럼속성14';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."EZ_MAIL_NOTICE_FLG" IS 'K_월별사이트고객컬럼속성15';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."DELE_AU_SUBS_RK" IS 'K_월별사이트고객컬럼속성16';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."APPROVAL_TICKET_ID" IS 'K_월별사이트고객컬럼속성17';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."CUST_FIRST_REGIST_DT" IS 'K_월별사이트고객컬럼속성18';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."ACTIVE_DT" IS 'K_월별사이트고객컬럼속성19';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."INVALID_DT" IS 'K_월별사이트고객컬럼속성20';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST"."INVALID_FLG" IS 'K_월별사이트고객컬럼속성21';
   COMMENT ON TABLE "K_MONTH_SITE_CUST"  IS 'K_월별사이트고객';


  CREATE TABLE "K_MONTH_SITE_CUST_LINK" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"SUBS_CLS" VARCHAR2(10 BYTE), 
	"SUBS_ID" VARCHAR2(10 BYTE), 
	"LINK_DS" VARCHAR2(10 BYTE), 
	"ACTIVE_DT" VARCHAR2(10 BYTE), 
	"ACTIVE_TM" VARCHAR2(10 BYTE), 
	"INVALID_DT" VARCHAR2(10 BYTE), 
	"INVALID_TM" VARCHAR2(10 BYTE), 
	"SUBS_LINK_STATUS_CD" VARCHAR2(10 BYTE), 
	"INVALID_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."ACQ_DT" IS 'K_월별사이트고객린크컬럼속성1';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."YM" IS 'K_월별사이트고객린크컬럼속성2';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."CUST_ID" IS 'K_월별사이트고객린크컬럼속성3';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."SUBS_CLS" IS 'K_월별사이트고객린크컬럼속성4';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."SUBS_ID" IS 'K_월별사이트고객린크컬럼속성5';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."LINK_DS" IS 'K_월별사이트고객린크컬럼속성6';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."ACTIVE_DT" IS 'K_월별사이트고객린크컬럼속성7';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."ACTIVE_TM" IS 'K_월별사이트고객린크컬럼속성8';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."INVALID_DT" IS 'K_월별사이트고객린크컬럼속성9';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."INVALID_TM" IS 'K_월별사이트고객린크컬럼속성10';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."SUBS_LINK_STATUS_CD" IS 'K_월별사이트고객린크컬럼속성11';
   COMMENT ON COLUMN "K_MONTH_SITE_CUST_LINK"."INVALID_FLG" IS 'K_월별사이트고객린크컬럼속성12';
   COMMENT ON TABLE "K_MONTH_SITE_CUST_LINK"  IS 'K_월별사이트고객린크';


  CREATE TABLE "MONTH_0_KEY" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"CUR_CLOSE_FLG" VARCHAR2(10 BYTE), 
	"DELE_AU_SUBS_JOIN_FLG" VARCHAR2(10 BYTE), 
	"M" VARCHAR2(10 BYTE), 
	"MONTH_SUSPENSION_FLG" VARCHAR2(10 BYTE), 
	"MONTH_SVC_FLG" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"SUSPENSION_CLOSE_FLG" VARCHAR2(10 BYTE), 
	"Y" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_0_KEY"."ACQ_DT" IS '월별0KEY컬럼속성1';
   COMMENT ON COLUMN "MONTH_0_KEY"."AU_ID" IS '월별0KEY컬럼속성2';
   COMMENT ON COLUMN "MONTH_0_KEY"."CUR_CLOSE_FLG" IS '월별0KEY컬럼속성3';
   COMMENT ON COLUMN "MONTH_0_KEY"."DELE_AU_SUBS_JOIN_FLG" IS '월별0KEY컬럼속성4';
   COMMENT ON COLUMN "MONTH_0_KEY"."M" IS '월별0KEY컬럼속성5';
   COMMENT ON COLUMN "MONTH_0_KEY"."MONTH_SUSPENSION_FLG" IS '월별0KEY컬럼속성6';
   COMMENT ON COLUMN "MONTH_0_KEY"."MONTH_SVC_FLG" IS '월별0KEY컬럼속성7';
   COMMENT ON COLUMN "MONTH_0_KEY"."SUBS_RK" IS '월별0KEY컬럼속성8';
   COMMENT ON COLUMN "MONTH_0_KEY"."SUBS_TYPE" IS '월별0KEY컬럼속성9';
   COMMENT ON COLUMN "MONTH_0_KEY"."SUSPENSION_CLOSE_FLG" IS '월별0KEY컬럼속성10';
   COMMENT ON COLUMN "MONTH_0_KEY"."Y" IS '월별0KEY컬럼속성11';
   COMMENT ON TABLE "MONTH_0_KEY"  IS '월별0KEY';


  CREATE TABLE "MONTH_1_GENDER_AGE" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"M" VARCHAR2(10 BYTE), 
	"SUBS_AGE" VARCHAR2(10 BYTE), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"SUBS_STUDENT_AGE" VARCHAR2(10 BYTE), 
	"USER_AGE" VARCHAR2(10 BYTE), 
	"USER_STUDENT_AGE" VARCHAR2(10 BYTE), 
	"Y" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."ACQ_DT" IS '월별1성별연령컬럼속성1';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."AU_ID" IS '월별1성별연령컬럼속성2';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."M" IS '월별1성별연령컬럼속성3';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."SUBS_AGE" IS '월별1성별연령컬럼속성4';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."SUBS_GENDER_CLS" IS '월별1성별연령컬럼속성5';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."SUBS_STUDENT_AGE" IS '월별1성별연령컬럼속성6';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."USER_AGE" IS '월별1성별연령컬럼속성7';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."USER_STUDENT_AGE" IS '월별1성별연령컬럼속성8';
   COMMENT ON COLUMN "MONTH_1_GENDER_AGE"."Y" IS '월별1성별연령컬럼속성9';
   COMMENT ON TABLE "MONTH_1_GENDER_AGE"  IS '월별1성별연령';


  CREATE TABLE "MONTH_2_HOUSE_AREA" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_PREF_CD" VARCHAR2(10 BYTE), 
	"M" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_PREF_CD" VARCHAR2(10 BYTE), 
	"Y" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."ACQ_DT" IS '컬럼속성1';
   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."AU_ID" IS '컬럼속성2';
   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."LATEST_DELIVERY_PREF_CD" IS '컬럼속성3';
   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."M" IS '컬럼속성4';
   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."NEW_JOIN_ACCEPT_PREF_CD" IS '컬럼속성5';
   COMMENT ON COLUMN "MONTH_2_HOUSE_AREA"."Y" IS '컬럼속성6';
   COMMENT ON TABLE "MONTH_2_HOUSE_AREA"  IS '월2주택면적';


  CREATE TABLE "MONTH_32_MOBILE_USE_SITU" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"AU_HOME_DSC_REGIST_FLG" VARCHAR2(10 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"CLOSE_DT" VARCHAR2(10 BYTE), 
	"CLOSE_REASON" VARCHAR2(10 BYTE), 
	"CONTACT_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"FROM_COMPANY_CD" VARCHAR2(10 BYTE), 
	"JOIN_REGION_CLS" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_CHANNEL1" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_CHANNEL2" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_MVNO_CLS" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CHANNEL1" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CHANNEL2" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CITY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_MVNO_CLS" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"M" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CHANNEL1" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CHANNEL2" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CITY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_MVNO_CLS" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_REGIST_DT" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"PRIORITY_JOINER_FLG" VARCHAR2(10 BYTE), 
	"SVC_STATUS_GROUP_CLS" VARCHAR2(10 BYTE), 
	"TO_COMPANY_CD" VARCHAR2(10 BYTE), 
	"Y" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."ACQ_DT" IS '컬럼속성1';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."AU_HOME_DSC_REGIST_FLG" IS '컬럼속성2';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."AU_ID" IS '컬럼속성3';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."CLOSE_DT" IS '컬럼속성4';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."CLOSE_REASON" IS '컬럼속성5';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."CONTACT_CLS" IS '컬럼속성6';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."FIRST_CHRG_START_DT" IS '컬럼속성7';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."FROM_COMPANY_CD" IS '컬럼속성8';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."JOIN_REGION_CLS" IS '컬럼속성9';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_ACCEPT_CHANNEL1" IS '컬럼속성10';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_ACCEPT_CHANNEL2" IS '컬럼속성11';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_ACCEPT_MVNO_CLS" IS '컬럼속성12';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_ACCEPT_SHOP_CD" IS '컬럼속성13';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_ACCEPT_SV_AGENCY_CD" IS '컬럼속성14';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_CHANNEL1" IS '컬럼속성15';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_CHANNEL2" IS '컬럼속성16';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_CITY_CD" IS '컬럼속성17';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_MVNO_CLS" IS '컬럼속성18';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_SHOP_CD" IS '컬럼속성19';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."LATEST_DELIVERY_SV_AGENCY_CD" IS '컬럼속성20';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."M" IS '컬럼속성21';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_CHANNEL1" IS '컬럼속성22';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_CHANNEL2" IS '컬럼속성23';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_CITY_CD" IS '컬럼속성24';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_MVNO_CLS" IS '컬럼속성25';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_SHOP_CD" IS '컬럼속성26';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_ACCEPT_SV_AGENCY_CD" IS '컬럼속성27';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_DELIVERY_SHOP_CD" IS '컬럼속성28';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_JOIN_DELIVERY_SV_AGENCY_CD" IS '컬럼속성29';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_PRICE_PLAN_CD" IS '컬럼속성30';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_PRICE_PLAN_REGIST_DT" IS '컬럼속성31';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."NEW_PRICE_PLAN_START_DT" IS '컬럼속성32';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."PRIORITY_JOINER_FLG" IS '컬럼속성33';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."SVC_STATUS_GROUP_CLS" IS '컬럼속성34';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."TO_COMPANY_CD" IS '컬럼속성35';
   COMMENT ON COLUMN "MONTH_32_MOBILE_USE_SITU"."Y" IS '컬럼속성36';
   COMMENT ON TABLE "MONTH_32_MOBILE_USE_SITU"  IS '월별32모바일사용현황';


  CREATE TABLE "MONTH_AU_CUST_AUID_MST" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"AU_ID" VARCHAR2(10 BYTE), 
	"CUST_ID" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"LINK_CLS" VARCHAR2(10 BYTE), 
	"DELE_AU_SUBS_JOIN_FLG" VARCHAR2(10 BYTE), 
	"PWD_INITIAL_CHANGE_CLS" VARCHAR2(10 BYTE), 
	"DELE_SUBS_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."ACQ_DT" IS '월별AU고객AUID마스터컬럼속성1';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."AU_ID" IS '월별AU고객AUID마스터컬럼속성2';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."CUST_ID" IS '월별AU고객AUID마스터컬럼속성3';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."SUBS_RK" IS '월별AU고객AUID마스터컬럼속성4';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."LINK_CLS" IS '월별AU고객AUID마스터컬럼속성5';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."DELE_AU_SUBS_JOIN_FLG" IS '월별AU고객AUID마스터컬럼속성6';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."PWD_INITIAL_CHANGE_CLS" IS '월별AU고객AUID마스터컬럼속성7';
   COMMENT ON COLUMN "MONTH_AU_CUST_AUID_MST"."DELE_SUBS_FLG" IS '월별AU고객AUID마스터컬럼속성8';
   COMMENT ON TABLE "MONTH_AU_CUST_AUID_MST"  IS '월별AU고객AUID마스터';


  CREATE TABLE "MONTH_CUST_INF_BASE" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"JOIN_REGION_CLS" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"CONTACT_CLS" VARCHAR2(10 BYTE), 
	"SUBS_AGE" NUMBER(10,0), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_USE_PRD" NUMBER(10,0), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_REGIST_DT" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"SVC_STATUS_L_CLS" VARCHAR2(10 BYTE), 
	"SUSPENSION_DT" VARCHAR2(10 BYTE), 
	"CLOSE_DT" VARCHAR2(10 BYTE), 
	"CLOSE_REASON" VARCHAR2(10 BYTE), 
	"AU_HOME_DSC_REGIST_FLG" VARCHAR2(10 BYTE), 
	"PRIORITY_JOINER_FLG" VARCHAR2(10 BYTE), 
	"SUBS_STUDENT_AGE" NUMBER(10,0), 
	"FROM_COMPANY_CD" VARCHAR2(10 BYTE), 
	"TO_COMPANY_CD" VARCHAR2(10 BYTE), 
	"PERMISSION_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"USER_AGE" NUMBER(10,0), 
	"USER_STUDENT_AGE" NUMBER(10,0), 
	"SVC_STATUS_GROUP_CLS" VARCHAR2(10 BYTE), 
	"SUSPENSION_CLOSE_FLG" VARCHAR2(10 BYTE), 
	"SUBS_DEPART_FLG" VARCHAR2(10 BYTE), 
	"SIMPLE_USAGE_CLS" VARCHAR2(10 BYTE), 
	"SIMPLE_USAGE_PRD" NUMBER(10,0), 
	"SPT_SPC_USAGE_RENEWAL_PRD" NUMBER(10,0)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."ACQ_DT" IS '월별기본고객정보컬럼속성1';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."JOIN_REGION_CLS" IS '월별기본고객정보컬럼속성2';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_RK" IS '월별기본고객정보컬럼속성3';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_TYPE" IS '월별기본고객정보컬럼속성4';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CONTACT_CLS" IS '월별기본고객정보컬럼속성5';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_AGE" IS '월별기본고객정보컬럼속성6';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_GENDER_CLS" IS '월별기본고객정보컬럼속성7';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CUR_PRICE_PLAN_CD" IS '월별기본고객정보컬럼속성8';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CUR_PRICE_PLAN_START_DT" IS '월별기본고객정보컬럼속성9';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CUR_PRICE_PLAN_USE_PRD" IS '월별기본고객정보컬럼속성10';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."NEW_PRICE_PLAN_CD" IS '월별기본고객정보컬럼속성11';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."NEW_PRICE_PLAN_REGIST_DT" IS '월별기본고객정보컬럼속성12';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."NEW_PRICE_PLAN_START_DT" IS '월별기본고객정보컬럼속성13';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SVC_STATUS_L_CLS" IS '월별기본고객정보컬럼속성14';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUSPENSION_DT" IS '월별기본고객정보컬럼속성15';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CLOSE_DT" IS '월별기본고객정보컬럼속성16';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."CLOSE_REASON" IS '월별기본고객정보컬럼속성17';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."AU_HOME_DSC_REGIST_FLG" IS '월별기본고객정보컬럼속성18';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."PRIORITY_JOINER_FLG" IS '월별기본고객정보컬럼속성19';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_STUDENT_AGE" IS '월별기본고객정보컬럼속성20';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."FROM_COMPANY_CD" IS '월별기본고객정보컬럼속성21';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."TO_COMPANY_CD" IS '월별기본고객정보컬럼속성22';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."PERMISSION_CLS" IS '월별기본고객정보컬럼속성23';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."FIRST_CHRG_START_DT" IS '월별기본고객정보컬럼속성24';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."USER_AGE" IS '월별기본고객정보컬럼속성25';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."USER_STUDENT_AGE" IS '월별기본고객정보컬럼속성26';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SVC_STATUS_GROUP_CLS" IS '월별기본고객정보컬럼속성27';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUSPENSION_CLOSE_FLG" IS '월별기본고객정보컬럼속성28';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SUBS_DEPART_FLG" IS '월별기본고객정보컬럼속성29';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SIMPLE_USAGE_CLS" IS '월별기본고객정보컬럼속성30';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SIMPLE_USAGE_PRD" IS '월별기본고객정보컬럼속성31';
   COMMENT ON COLUMN "MONTH_CUST_INF_BASE"."SPT_SPC_USAGE_RENEWAL_PRD" IS '월별기본고객정보컬럼속성32';
   COMMENT ON TABLE "MONTH_CUST_INF_BASE"  IS '월별기본고객정보';


  CREATE TABLE "MONTH_CUST_INF_SHOP" 
   (	"ACQ_DT" VARCHAR2(200 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CHANNEL1" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CHANNEL2" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_MVNO_CLS" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_PREF_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_CITY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_CHANNEL1" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_CHANNEL2" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_MVNO_CLS" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_PREF_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_CITY_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_CHANNEL1" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_CHANNEL2" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_MVNO_CLS" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_PREF_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_CITY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CHANNEL1" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CHANNEL2" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_MVNO_CLS" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_PREF_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_CITY_CD" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."ACQ_DT" IS '획득시간';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."SUBS_RK" IS '대리자RK';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_SV_AGENCY_CD" IS '신규가입승인서비스대행코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_SHOP_CD" IS '신규가입승인샵코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_CHANNEL1" IS '신규가입승인채널1';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_CHANNEL2" IS '신규가입승인채널2';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_MVNO_CLS" IS '신규가입승인통신사등급';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_PREF_CD" IS '신규가입승인프리코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_ACCEPT_CITY_CD" IS '신규가입승인도시코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_SV_AGENCY_CD" IS '신규가입인도서비스대행코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_SHOP_CD" IS '신규가입인도샵코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_CHANNEL1" IS '신규가입인도채널1';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_CHANNEL2" IS '신규가입인도채널2';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_MVNO_CLS" IS '신규가입인도통신사등급';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_PREF_CD" IS '신규가입인도프리코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."NEW_JOIN_DELIVERY_CITY_CD" IS '신규가입인도도시코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_SV_AGENCY_CD" IS '최신승인서비스대행코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_SHOP_CD" IS '최신승인샵코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_CHANNEL1" IS '최신승인채널1';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_CHANNEL2" IS '최신승인채널2';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_MVNO_CLS" IS '최신승인통신사등급';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_PREF_CD" IS '최신승인프리코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_ACCEPT_CITY_CD" IS '최신승인도시코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_SV_AGENCY_CD" IS '최신인도서비스대행코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_SHOP_CD" IS '최신인도샵코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_CHANNEL1" IS '최신인도채널1';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_CHANNEL2" IS '최신인도채널2';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_MVNO_CLS" IS '최신인도통신사등급';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_PREF_CD" IS '최신인도프리코드';
   COMMENT ON COLUMN "MONTH_CUST_INF_SHOP"."LATEST_DELIVERY_CITY_CD" IS '최신인도도시코드';
   COMMENT ON TABLE "MONTH_CUST_INF_SHOP"  IS '월별고객정보샵';


  CREATE TABLE "MONTH_SHOP_MST" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"SHOP_CD" VARCHAR2(10 BYTE), 
	"SHOP_NAME" VARCHAR2(10 BYTE), 
	"SHOP_SHORT_NAME" VARCHAR2(10 BYTE), 
	"REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_NAME" VARCHAR2(10 BYTE), 
	"SHOP_HANDLE_CD" VARCHAR2(10 BYTE), 
	"SHOP_POSTAL_CD" VARCHAR2(10 BYTE), 
	"SHOP_PREF_CD" VARCHAR2(10 BYTE), 
	"SHOP_CITY_CD" VARCHAR2(10 BYTE), 
	"SHOP_CLS" VARCHAR2(10 BYTE), 
	"INSTAL_SALE_CLS" VARCHAR2(10 BYTE), 
	"AU_AGENCY_CLS" VARCHAR2(10 BYTE), 
	"MVNO_CLS" VARCHAR2(10 BYTE), 
	"GROUP_CD_SV" VARCHAR2(10 BYTE), 
	"GROUP_CD_SHOP" VARCHAR2(10 BYTE), 
	"GROUP_CLS" VARCHAR2(10 BYTE), 
	"DIST_AF_SHOP" VARCHAR2(10 BYTE), 
	"MONOPOLY_CLS" VARCHAR2(10 BYTE), 
	"SALES_CHANNEL1" VARCHAR2(10 BYTE), 
	"SALES_CHANNEL2" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "MONTH_SHOP_MST"."ACQ_DT" IS '월별샵마스터컬럼속성1';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SUPERVISOR_CD" IS '월별샵마스터컬럼속성2';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_CD" IS '월별샵마스터컬럼속성3';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_NAME" IS '월별샵마스터컬럼속성4';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_SHORT_NAME" IS '월별샵마스터컬럼속성5';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."REGION_CD" IS '월별샵마스터컬럼속성6';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_REGION_CD" IS '월별샵마스터컬럼속성7';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_REGION_NAME" IS '월별샵마스터컬럼속성8';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_HANDLE_CD" IS '월별샵마스터컬럼속성9';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_POSTAL_CD" IS '월별샵마스터컬럼속성10';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_PREF_CD" IS '월별샵마스터컬럼속성11';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_CITY_CD" IS '월별샵마스터컬럼속성12';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SHOP_CLS" IS '월별샵마스터컬럼속성13';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."INSTAL_SALE_CLS" IS '월별샵마스터컬럼속성14';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."AU_AGENCY_CLS" IS '월별샵마스터컬럼속성15';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."MVNO_CLS" IS '월별샵마스터컬럼속성16';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."GROUP_CD_SV" IS '월별샵마스터컬럼속성17';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."GROUP_CD_SHOP" IS '월별샵마스터컬럼속성18';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."GROUP_CLS" IS '월별샵마스터컬럼속성19';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."DIST_AF_SHOP" IS '월별샵마스터컬럼속성20';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."MONOPOLY_CLS" IS '월별샵마스터컬럼속성21';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SALES_CHANNEL1" IS '월별샵마스터컬럼속성22';
   COMMENT ON COLUMN "MONTH_SHOP_MST"."SALES_CHANNEL2" IS '월별샵마스터컬럼속성23';
   COMMENT ON TABLE "MONTH_SHOP_MST"  IS '월별샵마스터';


  CREATE TABLE "REDSHIFT_MST" 
   (	"AU_ID" VARCHAR2(320 BYTE), 
	"SUBS_RK" VARCHAR2(32 BYTE), 
	"ITEM_SUBS_ID" VARCHAR2(40 BYTE), 
	"JOIN_DT" DATE, 
	"JOIN_TM" VARCHAR2(8 BYTE), 
	"CLOSE_DT" DATE, 
	"CLOSE_TM" VARCHAR2(8 BYTE), 
	"FIRST_ACTIVATION_DT" DATE, 
	"FIRST_ACTIVATION_DT_I" DATE, 
	"FREE_TRIAL_FLG" VARCHAR2(4 BYTE), 
	"TICKET_FLG" VARCHAR2(4 BYTE), 
	"AUTO_CLOSE_FLG" VARCHAR2(4 BYTE), 
	"Z_FLG" VARCHAR2(4 BYTE), 
	"SUBS_TYPE" VARCHAR2(4 BYTE), 
	"CS_RESULT_FLG" VARCHAR2(4 BYTE), 
	"JOIN_ROUTE" VARCHAR2(4 BYTE), 
	"JOIN_CLS" VARCHAR2(8 BYTE), 
	"JOIN_REGION_CLS" VARCHAR2(4 BYTE), 
	"JOIN_OS_CLS" VARCHAR2(4 BYTE), 
	"JOIN_DV_CLS" VARCHAR2(4 BYTE), 
	"JOIN_EQUIP_RK" VARCHAR2(12 BYTE), 
	"CLOSE_OS_CLS" VARCHAR2(4 BYTE), 
	"CLOSE_DV_CLS" VARCHAR2(4 BYTE), 
	"CLOSE_EQUIP_RK" VARCHAR2(12 BYTE), 
	"CHARGE_OS_CLS" VARCHAR2(4 BYTE), 
	"CHARGE_DV_CLS" VARCHAR2(4 BYTE), 
	"CHARGE_EQUIP_RK" VARCHAR2(12 BYTE), 
	"NOW_OS_CLS" VARCHAR2(4 BYTE), 
	"NOW_DV_CLS" VARCHAR2(4 BYTE), 
	"NOW_EQUIP_RK" VARCHAR2(12 BYTE), 
	"SFA_DATE" DATE, 
	"SIN_FLG" VARCHAR2(4 BYTE), 
	"SFA_APPLICATION_NO" VARCHAR2(36 BYTE), 
	"SFA_SHOP_CD" VARCHAR2(12 BYTE), 
	"SFA_SUPERVISOR_CD" VARCHAR2(16 BYTE), 
	"APPLICATION_NO" VARCHAR2(36 BYTE), 
	"SHOP_CD" VARCHAR2(12 BYTE), 
	"SUPERVISOR_CD" VARCHAR2(16 BYTE), 
	"FT_RETIRE_FLG" VARCHAR2(4 BYTE), 
	"JOIN_CNT" NUMBER(24,0), 
	"PAST_JOIN_FLG" VARCHAR2(4 BYTE), 
	"JOIN_FLG" VARCHAR2(4 BYTE), 
	"SUPERVISOR_SYSTEM_ID" VARCHAR2(24 BYTE), 
	"REGION_NM13" VARCHAR2(40 BYTE), 
	"SHOP_BRANCH_CD" VARCHAR2(12 BYTE), 
	"SHOP_BRANCH_NM" VARCHAR2(80 BYTE), 
	"AGENCY_CD" VARCHAR2(16 BYTE), 
	"AGENCY_NM" VARCHAR2(200 BYTE), 
	"SUPERVISOR_NM" VARCHAR2(200 BYTE), 
	"SHOP_NM" VARCHAR2(200 BYTE), 
	"CHANNEL_NM" VARCHAR2(48 BYTE), 
	"SUBS_STATUS_CLS" VARCHAR2(4 BYTE), 
	"STUDENT_AGE" NUMBER(24,0), 
	"AGE_RNG" VARCHAR2(32 BYTE), 
	"GENDER_CLS" VARCHAR2(40 BYTE), 
	"AU_FIRST_ACTIVATION_DT" DATE, 
	"EQUIP_SYS_RK" VARCHAR2(12 BYTE), 
	"EQUIP_MODEL_CD" VARCHAR2(80 BYTE), 
	"SMART_PHONE_FLG" VARCHAR2(4 BYTE), 
	"EQUIP_TYPE" VARCHAR2(24 BYTE), 
	"OS_CLS" VARCHAR2(28 BYTE), 
	"PAYMENT_CLS" VARCHAR2(4 BYTE), 
	"CUR_PRICE_PLAN_RK" VARCHAR2(16 BYTE), 
	"ENTRY_COUNTY_NM" VARCHAR2(32 BYTE), 
	"ENTRY_POSTAL_CD" VARCHAR2(32 BYTE), 
	"JOIN_DV_IDDISCRDIV" VARCHAR2(4 BYTE), 
	"NOW_DV_IDDISCRDIV" VARCHAR2(4 BYTE), 
	"CLOSE_DV_IDDISCRDIV" VARCHAR2(4 BYTE)
   )
   ;

   COMMENT ON COLUMN "REDSHIFT_MST"."AU_ID" IS '컬럼속성1';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUBS_RK" IS '컬럼속성2';
   COMMENT ON COLUMN "REDSHIFT_MST"."ITEM_SUBS_ID" IS '컬럼속성3';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_DT" IS '컬럼속성4';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_TM" IS '컬럼속성5';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_DT" IS '컬럼속성6';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_TM" IS '컬럼속성7';
   COMMENT ON COLUMN "REDSHIFT_MST"."FIRST_ACTIVATION_DT" IS '컬럼속성8';
   COMMENT ON COLUMN "REDSHIFT_MST"."FIRST_ACTIVATION_DT_I" IS '컬럼속성9';
   COMMENT ON COLUMN "REDSHIFT_MST"."FREE_TRIAL_FLG" IS '컬럼속성10';
   COMMENT ON COLUMN "REDSHIFT_MST"."TICKET_FLG" IS '컬럼속성11';
   COMMENT ON COLUMN "REDSHIFT_MST"."AUTO_CLOSE_FLG" IS '컬럼속성12';
   COMMENT ON COLUMN "REDSHIFT_MST"."Z_FLG" IS '컬럼속성13';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUBS_TYPE" IS '컬럼속성14';
   COMMENT ON COLUMN "REDSHIFT_MST"."CS_RESULT_FLG" IS '컬럼속성15';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_ROUTE" IS '컬럼속성16';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_CLS" IS '컬럼속성17';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_REGION_CLS" IS '컬럼속성18';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_OS_CLS" IS '컬럼속성19';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_DV_CLS" IS '컬럼속성20';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_EQUIP_RK" IS '컬럼속성21';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_OS_CLS" IS '컬럼속성22';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_DV_CLS" IS '컬럼속성23';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_EQUIP_RK" IS '컬럼속성24';
   COMMENT ON COLUMN "REDSHIFT_MST"."CHARGE_OS_CLS" IS '컬럼속성25';
   COMMENT ON COLUMN "REDSHIFT_MST"."CHARGE_DV_CLS" IS '컬럼속성26';
   COMMENT ON COLUMN "REDSHIFT_MST"."CHARGE_EQUIP_RK" IS '컬럼속성27';
   COMMENT ON COLUMN "REDSHIFT_MST"."NOW_OS_CLS" IS '컬럼속성28';
   COMMENT ON COLUMN "REDSHIFT_MST"."NOW_DV_CLS" IS '컬럼속성29';
   COMMENT ON COLUMN "REDSHIFT_MST"."NOW_EQUIP_RK" IS '컬럼속성30';
   COMMENT ON COLUMN "REDSHIFT_MST"."SFA_DATE" IS '컬럼속성31';
   COMMENT ON COLUMN "REDSHIFT_MST"."SIN_FLG" IS '컬럼속성32';
   COMMENT ON COLUMN "REDSHIFT_MST"."SFA_APPLICATION_NO" IS '컬럼속성33';
   COMMENT ON COLUMN "REDSHIFT_MST"."SFA_SHOP_CD" IS '컬럼속성34';
   COMMENT ON COLUMN "REDSHIFT_MST"."SFA_SUPERVISOR_CD" IS '컬럼속성35';
   COMMENT ON COLUMN "REDSHIFT_MST"."APPLICATION_NO" IS '컬럼속성36';
   COMMENT ON COLUMN "REDSHIFT_MST"."SHOP_CD" IS '컬럼속성37';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUPERVISOR_CD" IS '컬럼속성38';
   COMMENT ON COLUMN "REDSHIFT_MST"."FT_RETIRE_FLG" IS '컬럼속성39';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_CNT" IS '컬럼속성40';
   COMMENT ON COLUMN "REDSHIFT_MST"."PAST_JOIN_FLG" IS '컬럼속성41';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_FLG" IS '컬럼속성42';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUPERVISOR_SYSTEM_ID" IS '컬럼속성43';
   COMMENT ON COLUMN "REDSHIFT_MST"."REGION_NM13" IS '컬럼속성44';
   COMMENT ON COLUMN "REDSHIFT_MST"."SHOP_BRANCH_CD" IS '컬럼속성45';
   COMMENT ON COLUMN "REDSHIFT_MST"."SHOP_BRANCH_NM" IS '컬럼속성46';
   COMMENT ON COLUMN "REDSHIFT_MST"."AGENCY_CD" IS '컬럼속성47';
   COMMENT ON COLUMN "REDSHIFT_MST"."AGENCY_NM" IS '컬럼속성48';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUPERVISOR_NM" IS '컬럼속성49';
   COMMENT ON COLUMN "REDSHIFT_MST"."SHOP_NM" IS '컬럼속성50';
   COMMENT ON COLUMN "REDSHIFT_MST"."CHANNEL_NM" IS '컬럼속성51';
   COMMENT ON COLUMN "REDSHIFT_MST"."SUBS_STATUS_CLS" IS '컬럼속성52';
   COMMENT ON COLUMN "REDSHIFT_MST"."STUDENT_AGE" IS '컬럼속성53';
   COMMENT ON COLUMN "REDSHIFT_MST"."AGE_RNG" IS '컬럼속성54';
   COMMENT ON COLUMN "REDSHIFT_MST"."GENDER_CLS" IS '컬럼속성55';
   COMMENT ON COLUMN "REDSHIFT_MST"."AU_FIRST_ACTIVATION_DT" IS '컬럼속성56';
   COMMENT ON COLUMN "REDSHIFT_MST"."EQUIP_SYS_RK" IS '컬럼속성57';
   COMMENT ON COLUMN "REDSHIFT_MST"."EQUIP_MODEL_CD" IS '컬럼속성58';
   COMMENT ON COLUMN "REDSHIFT_MST"."SMART_PHONE_FLG" IS '컬럼속성59';
   COMMENT ON COLUMN "REDSHIFT_MST"."EQUIP_TYPE" IS '컬럼속성60';
   COMMENT ON COLUMN "REDSHIFT_MST"."OS_CLS" IS '컬럼속성61';
   COMMENT ON COLUMN "REDSHIFT_MST"."PAYMENT_CLS" IS '컬럼속성62';
   COMMENT ON COLUMN "REDSHIFT_MST"."CUR_PRICE_PLAN_RK" IS '컬럼속성63';
   COMMENT ON COLUMN "REDSHIFT_MST"."ENTRY_COUNTY_NM" IS '컬럼속성64';
   COMMENT ON COLUMN "REDSHIFT_MST"."ENTRY_POSTAL_CD" IS '컬럼속성65';
   COMMENT ON COLUMN "REDSHIFT_MST"."JOIN_DV_IDDISCRDIV" IS '컬럼속성66';
   COMMENT ON COLUMN "REDSHIFT_MST"."NOW_DV_IDDISCRDIV" IS '컬럼속성67';
   COMMENT ON COLUMN "REDSHIFT_MST"."CLOSE_DV_IDDISCRDIV" IS '컬럼속성68';
   COMMENT ON TABLE "REDSHIFT_MST"  IS 'REDSHIFT마스터';


  CREATE TABLE "T_MONTH_CUST_INF" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"YM" VARCHAR2(10 BYTE), 
	"JOIN_REGION_CLS" VARCHAR2(10 BYTE), 
	"SUBS_RK" VARCHAR2(10 BYTE), 
	"BILL_CD" VARCHAR2(10 BYTE), 
	"SUBS_TYPE" VARCHAR2(10 BYTE), 
	"AU_TEL_NO_H" VARCHAR2(10 BYTE), 
	"SUBS_POSTAL_CD" VARCHAR2(10 BYTE), 
	"SUBS_PREF_CD" VARCHAR2(10 BYTE), 
	"JOIN_CITY_CD" VARCHAR2(10 BYTE), 
	"CONTACT_CLS" VARCHAR2(10 BYTE), 
	"SUBS_AGE" NUMBER(10,0), 
	"SUBS_GENDER_CLS" VARCHAR2(10 BYTE), 
	"TARGET_BIRTH_DT" VARCHAR2(10 BYTE), 
	"TAX_FREE_CLS" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"CUR_PRICE_PLAN_USE_PRD" NUMBER(10,0), 
	"NEW_PRICE_PLAN_CD" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_REGIST_DT" VARCHAR2(10 BYTE), 
	"NEW_PRICE_PLAN_START_DT" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"NEW_JOIN_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_ACCEPT_SHOP_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SV_AGENCY_CD" VARCHAR2(10 BYTE), 
	"LATEST_DELIVERY_SHOP_CD" VARCHAR2(10 BYTE), 
	"LUMP_CLS" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(10 BYTE), 
	"SERIAL_NO" VARCHAR2(10 BYTE), 
	"EQUIP_RK" VARCHAR2(10 BYTE), 
	"USE_MODEL_START_DT" VARCHAR2(10 BYTE), 
	"USE_MODEL_USE_PERIOD" NUMBER(10,0), 
	"ANSIN_APPLY_CLS" VARCHAR2(10 BYTE), 
	"CHRG_START_DT" VARCHAR2(10 BYTE), 
	"COUNTING_START_DT" VARCHAR2(10 BYTE), 
	"SVC_STATUS_L_CLS" VARCHAR2(10 BYTE), 
	"SVC_STATUS_S_CLS" VARCHAR2(10 BYTE), 
	"SUSPENSION_DT" VARCHAR2(10 BYTE), 
	"RE_USE_DT" VARCHAR2(10 BYTE), 
	"SUBS_TRANS_DT" VARCHAR2(10 BYTE), 
	"SUBS_REOPEN_DT" VARCHAR2(10 BYTE), 
	"CLOSE_DT" VARCHAR2(10 BYTE), 
	"CLOSE_REASON" VARCHAR2(10 BYTE), 
	"OPERATION_DAYS" NUMBER(10,0), 
	"USE_PRD_TOTAL" NUMBER(10,0), 
	"MODEL_CHANGE_FLG" VARCHAR2(10 BYTE), 
	"SVC_CLS" VARCHAR2(10 BYTE), 
	"CALL_WIDE_FLG" VARCHAR2(10 BYTE), 
	"GROUP_DSC_FLG" VARCHAR2(10 BYTE), 
	"TYAKU_BUSI_FLG" VARCHAR2(10 BYTE), 
	"MULTI_Y_DSC_CLS" VARCHAR2(10 BYTE), 
	"WIN_MULTI_CABLE_DSC_FLG" VARCHAR2(10 BYTE), 
	"AU_HOME_DSC_REGIST_FLG" VARCHAR2(10 BYTE), 
	"PRIORITY_JOINER_FLG" VARCHAR2(10 BYTE), 
	"PRICE_CALL_STOP_TOTAL_CNT" NUMBER(10,0), 
	"TEMP_STOP" NUMBER(10,0), 
	"MODEL_CHANGE_CNT" NUMBER(10,0), 
	"MODEL_TROUBLE_CNT" NUMBER(10,0), 
	"TROUBLE_CNT_TOTAL" NUMBER(10,0), 
	"USED_MODEL_CLS" VARCHAR2(10 BYTE), 
	"WIDE_SPT_APPLY_FLG" VARCHAR2(10 BYTE), 
	"SUBS_STUDENT_AGE" NUMBER(10,0), 
	"MARU_BUSI_DSC_FLG" VARCHAR2(10 BYTE), 
	"OTHER_COMPANY_JOIN_CLS" VARCHAR2(10 BYTE), 
	"FROM_COMPANY_CD" VARCHAR2(10 BYTE), 
	"TO_COMPANY_CD" VARCHAR2(10 BYTE), 
	"G_CALL_DSC_CLS" VARCHAR2(10 BYTE), 
	"PERMISSION_CLS" VARCHAR2(10 BYTE), 
	"HITORI_FLG" VARCHAR2(10 BYTE), 
	"MARU_BUSI_CO_CLS" VARCHAR2(10 BYTE), 
	"SHOP_PURCHASE_METHOD" VARCHAR2(10 BYTE), 
	"RESULT_TRANS_DT" VARCHAR2(10 BYTE), 
	"BF_TRANS_RESULT_CLS" VARCHAR2(10 BYTE), 
	"AF_TRANS_RESULT_CLS" VARCHAR2(10 BYTE), 
	"FIRST_CHRG_START_DT" VARCHAR2(10 BYTE), 
	"COLLABO_COMPANY_FLG" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "T_MONTH_CUST_INF"."ACQ_DT" IS 'T_월별고객정보컬럼속성1';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."YM" IS 'T_월별고객정보컬럼속성2';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."JOIN_REGION_CLS" IS 'T_월별고객정보컬럼속성3';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_RK" IS 'T_월별고객정보컬럼속성4';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."BILL_CD" IS 'T_월별고객정보컬럼속성5';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_TYPE" IS 'T_월별고객정보컬럼속성6';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."AU_TEL_NO_H" IS 'T_월별고객정보컬럼속성7';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_POSTAL_CD" IS 'T_월별고객정보컬럼속성8';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_PREF_CD" IS 'T_월별고객정보컬럼속성9';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."JOIN_CITY_CD" IS 'T_월별고객정보컬럼속성10';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CONTACT_CLS" IS 'T_월별고객정보컬럼속성11';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_AGE" IS 'T_월별고객정보컬럼속성12';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_GENDER_CLS" IS 'T_월별고객정보컬럼속성13';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TARGET_BIRTH_DT" IS 'T_월별고객정보컬럼속성14';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TAX_FREE_CLS" IS 'T_월별고객정보컬럼속성15';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CUR_PRICE_PLAN_CD" IS 'T_월별고객정보컬럼속성16';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CUR_PRICE_PLAN_START_DT" IS 'T_월별고객정보컬럼속성17';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CUR_PRICE_PLAN_USE_PRD" IS 'T_월별고객정보컬럼속성18';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_PRICE_PLAN_CD" IS 'T_월별고객정보컬럼속성19';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_PRICE_PLAN_REGIST_DT" IS 'T_월별고객정보컬럼속성20';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_PRICE_PLAN_START_DT" IS 'T_월별고객정보컬럼속성21';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_JOIN_ACCEPT_SV_AGENCY_CD" IS 'T_월별고객정보컬럼속성22';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_JOIN_ACCEPT_SHOP_CD" IS 'T_월별고객정보컬럼속성23';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_JOIN_DELIVERY_SV_AGENCY_CD" IS 'T_월별고객정보컬럼속성24';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."NEW_JOIN_DELIVERY_SHOP_CD" IS 'T_월별고객정보컬럼속성25';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."LATEST_ACCEPT_SV_AGENCY_CD" IS 'T_월별고객정보컬럼속성26';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."LATEST_ACCEPT_SHOP_CD" IS 'T_월별고객정보컬럼속성27';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."LATEST_DELIVERY_SV_AGENCY_CD" IS 'T_월별고객정보컬럼속성28';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."LATEST_DELIVERY_SHOP_CD" IS 'T_월별고객정보컬럼속성29';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."LUMP_CLS" IS 'T_월별고객정보컬럼속성30';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TYPE" IS 'T_월별고객정보컬럼속성31';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SERIAL_NO" IS 'T_월별고객정보컬럼속성32';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."EQUIP_RK" IS 'T_월별고객정보컬럼속성33';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."USE_MODEL_START_DT" IS 'T_월별고객정보컬럼속성34';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."USE_MODEL_USE_PERIOD" IS 'T_월별고객정보컬럼속성35';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."ANSIN_APPLY_CLS" IS 'T_월별고객정보컬럼속성36';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CHRG_START_DT" IS 'T_월별고객정보컬럼속성37';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."COUNTING_START_DT" IS 'T_월별고객정보컬럼속성38';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SVC_STATUS_L_CLS" IS 'T_월별고객정보컬럼속성39';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SVC_STATUS_S_CLS" IS 'T_월별고객정보컬럼속성40';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUSPENSION_DT" IS 'T_월별고객정보컬럼속성41';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."RE_USE_DT" IS 'T_월별고객정보컬럼속성42';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_TRANS_DT" IS 'T_월별고객정보컬럼속성43';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_REOPEN_DT" IS 'T_월별고객정보컬럼속성44';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CLOSE_DT" IS 'T_월별고객정보컬럼속성45';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CLOSE_REASON" IS 'T_월별고객정보컬럼속성46';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."OPERATION_DAYS" IS 'T_월별고객정보컬럼속성47';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."USE_PRD_TOTAL" IS 'T_월별고객정보컬럼속성48';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MODEL_CHANGE_FLG" IS 'T_월별고객정보컬럼속성49';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SVC_CLS" IS 'T_월별고객정보컬럼속성50';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."CALL_WIDE_FLG" IS 'T_월별고객정보컬럼속성51';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."GROUP_DSC_FLG" IS 'T_월별고객정보컬럼속성52';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TYAKU_BUSI_FLG" IS 'T_월별고객정보컬럼속성53';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MULTI_Y_DSC_CLS" IS 'T_월별고객정보컬럼속성54';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."WIN_MULTI_CABLE_DSC_FLG" IS 'T_월별고객정보컬럼속성55';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."AU_HOME_DSC_REGIST_FLG" IS 'T_월별고객정보컬럼속성56';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."PRIORITY_JOINER_FLG" IS 'T_월별고객정보컬럼속성57';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."PRICE_CALL_STOP_TOTAL_CNT" IS 'T_월별고객정보컬럼속성58';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TEMP_STOP" IS 'T_월별고객정보컬럼속성59';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MODEL_CHANGE_CNT" IS 'T_월별고객정보컬럼속성60';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MODEL_TROUBLE_CNT" IS 'T_월별고객정보컬럼속성61';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TROUBLE_CNT_TOTAL" IS 'T_월별고객정보컬럼속성62';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."USED_MODEL_CLS" IS 'T_월별고객정보컬럼속성63';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."WIDE_SPT_APPLY_FLG" IS 'T_월별고객정보컬럼속성64';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SUBS_STUDENT_AGE" IS 'T_월별고객정보컬럼속성65';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MARU_BUSI_DSC_FLG" IS 'T_월별고객정보컬럼속성66';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."OTHER_COMPANY_JOIN_CLS" IS 'T_월별고객정보컬럼속성67';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."FROM_COMPANY_CD" IS 'T_월별고객정보컬럼속성68';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."TO_COMPANY_CD" IS 'T_월별고객정보컬럼속성69';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."G_CALL_DSC_CLS" IS 'T_월별고객정보컬럼속성70';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."PERMISSION_CLS" IS 'T_월별고객정보컬럼속성71';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."HITORI_FLG" IS 'T_월별고객정보컬럼속성72';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."MARU_BUSI_CO_CLS" IS 'T_월별고객정보컬럼속성73';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."SHOP_PURCHASE_METHOD" IS 'T_월별고객정보컬럼속성74';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."RESULT_TRANS_DT" IS 'T_월별고객정보컬럼속성75';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."BF_TRANS_RESULT_CLS" IS 'T_월별고객정보컬럼속성76';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."AF_TRANS_RESULT_CLS" IS 'T_월별고객정보컬럼속성77';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."FIRST_CHRG_START_DT" IS 'T_월별고객정보컬럼속성78';
   COMMENT ON COLUMN "T_MONTH_CUST_INF"."COLLABO_COMPANY_FLG" IS 'T_월별고객정보컬럼속성79';
   COMMENT ON TABLE "T_MONTH_CUST_INF"  IS 'T_월별고객정보';


  CREATE TABLE "T_MONTH_SHOP_MST" 
   (	"ACQ_DT" VARCHAR2(100 BYTE), 
	"SUPERVISOR_CD" VARCHAR2(10 BYTE), 
	"SHOP_CD" VARCHAR2(10 BYTE), 
	"SHOP_NAME" VARCHAR2(10 BYTE), 
	"SHOP_SHORT_NAME" VARCHAR2(10 BYTE), 
	"REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_CD" VARCHAR2(10 BYTE), 
	"SHOP_REGION_NAME" VARCHAR2(10 BYTE), 
	"SHOP_HANDLE_CD" VARCHAR2(10 BYTE), 
	"SHOP_POSTAL_CD" VARCHAR2(10 BYTE), 
	"SHOP_PREF_CD" VARCHAR2(10 BYTE), 
	"SHOP_CITY_CD" VARCHAR2(10 BYTE), 
	"SHOP_CLS" VARCHAR2(10 BYTE), 
	"INSTAL_SALE_CLS" VARCHAR2(10 BYTE), 
	"AU_AGENCY_CLS" VARCHAR2(10 BYTE), 
	"MVNO_CLS" VARCHAR2(10 BYTE), 
	"GROUP_CD_SV" VARCHAR2(10 BYTE), 
	"GROUP_CD_SHOP" VARCHAR2(10 BYTE), 
	"GROUP_CLS" VARCHAR2(10 BYTE), 
	"DIST_AF_SHOP" VARCHAR2(10 BYTE), 
	"MONOPOLY_CLS" VARCHAR2(10 BYTE)
   ) 
   ;

   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."ACQ_DT" IS '컬럼속성1';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SUPERVISOR_CD" IS '컬럼속성2';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_CD" IS '컬럼속성3';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_NAME" IS '컬럼속성4';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_SHORT_NAME" IS '컬럼속성5';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."REGION_CD" IS '컬럼속성6';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_REGION_CD" IS '컬럼속성7';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_REGION_NAME" IS '컬럼속성8';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_HANDLE_CD" IS '컬럼속성9';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_POSTAL_CD" IS '컬럼속성10';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_PREF_CD" IS '컬럼속성11';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_CITY_CD" IS '컬럼속성12';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."SHOP_CLS" IS '컬럼속성13';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."INSTAL_SALE_CLS" IS '컬럼속성14';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."AU_AGENCY_CLS" IS '컬럼속성15';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."MVNO_CLS" IS '컬럼속성16';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."GROUP_CD_SV" IS '컬럼속성17';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."GROUP_CD_SHOP" IS '컬럼속성18';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."GROUP_CLS" IS '컬럼속성19';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."DIST_AF_SHOP" IS '컬럼속성20';
   COMMENT ON COLUMN "T_MONTH_SHOP_MST"."MONOPOLY_CLS" IS '컬럼속성21';
   COMMENT ON TABLE "T_MONTH_SHOP_MST"  IS '월별샵마스터';


CREATE TABLE TBL1 (
  COL1 NUMBER(22) DEFAULT 1
,
  COL2 NUMBER(22),
  COL3 NUMBER(22)
);

CREATE TABLE TBL2 (
  COL1 NUMBER(22),
  COL2 NUMBER(22),
  COL3 NUMBER(22)
);