CREATE TABLE "SAMPLE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(512), 
	"REG_USER" VARCHAR2(20), 
	"USE_YN" CHAR(1)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
;